void testing_training_validation(){

	TCanvas *cst = new TCanvas("cst","stacked hists",208,31,600,468);
  	gPad->SetLogy();

	float lumi = 1.;
  	gStyle->SetOptStat(0);


  	//Bg weights and cuts
  	TString WeightExpression ="";
  	WeightExpression += "1";

  
  	//store total number of fake events and nonfake events    
  	double fake_events_iso = 0.0;
  	double nonfake_events_iso = 0.0;

	/////////////////////////////
  	//   		Testing        //
  	/////////////////////////////

	float fake_events_bdt_test = 0.0;
	float nonfake_events_bdt_test = 0.0;

  	//Takes testing data histo from rootfile generated by training
	TFile *input_bdt_test = TFile::Open( "/cms/mchristos/ANN/FireMVA/class_perf/fire_MVA_TT_NoIso.root" ); 
	std::cout << "--- Using background input file: " << input_bdt_test->GetName() <<         std::endl;


  	//Get histos
	TH1F *fake_bdt_test_histo = (TH1F*)input_bdt_test->Get("dl/Method_BDT/BDT/MVA_BDT_B");
	TH1F *nonfake_bdt_test_histo = (TH1F*)input_bdt_test->Get("dl/Method_BDT/BDT/MVA_BDT_S");

	Double_t norm_fake_test = fake_bdt_test_histo->Integral();
	fake_bdt_test_histo->Scale(1/norm_fake_test);

	Double_t norm_nonfake_test = nonfake_bdt_test_histo->Integral();
	nonfake_bdt_test_histo->Scale(1/norm_nonfake_test);


	fake_events_bdt_test += fake_bdt_test_histo->Integral()*lumi;
	fake_bdt_test_histo->Scale(lumi);


	nonfake_events_bdt_test += nonfake_bdt_test_histo->Integral()*lumi;
	nonfake_bdt_test_histo->Scale(lumi);


	cout<<"fake Events (BDT normalized): "<<fake_events_bdt_test<<endl;
	cout<<"nonfake Events (BDT normalized): "<<nonfake_events_bdt_test<<endl;

	/////////////////////////////
  	//   		Training       //
  	/////////////////////////////

	float fake_events_bdt_train = 0.0;
	float nonfake_events_bdt_train = 0.0;

  	//Takes testing data histo from rootfile generated by training
	TFile *input_bdt_train = TFile::Open( "/cms/mchristos/ANN/FireMVA/class_perf/fire_MVA_TT_NoIso.root" ); 
	std::cout << "--- Using background input file: " << input_bdt_train->GetName() <<         std::endl;


  	//Get histos
	TH1F *fake_bdt_train_histo = (TH1F*)input_bdt_train->Get("dl/Method_BDT/BDT/MVA_BDT_Train_B");
	TH1F *nonfake_bdt_train_histo = (TH1F*)input_bdt_train->Get("dl/Method_BDT/BDT/MVA_BDT_Train_S");

	Double_t norm_fake_train = fake_bdt_train_histo->Integral();
	fake_bdt_train_histo->Scale(1/norm_fake_train);

	Double_t norm_nonfake_train = nonfake_bdt_train_histo->Integral();
	nonfake_bdt_train_histo->Scale(1/norm_nonfake_train);


	fake_events_bdt_train += fake_bdt_train_histo->Integral()*lumi;
	fake_bdt_train_histo->Scale(lumi);


	nonfake_events_bdt_train += nonfake_bdt_train_histo->Integral()*lumi;
	nonfake_bdt_train_histo->Scale(lumi);


	cout<<"fake Events (BDT normalized): "<<fake_events_bdt_train<<endl;
	cout<<"nonfake Events (BDT normalized): "<<nonfake_events_bdt_train<<endl;

	
	/////////////////////////
	///    Validation    ////
	/////////////////////////

	float fake_events_val = 0.0;
	float nonfake_events_val = 0.0;

  	//Get skimmed TTrees (copied from /cms/multilepton-2/hsaka/Workspace/pyPlotter-2018Maxi/pyPlotter/FIREMVA/)
	TFile *fake_input_val = TFile::Open( "/cms/mchristos/ANN/FireMVA/outFiles/BDTNoIso_TT_FakeMuonTree.root" ); 
	std::cout << "--- Using fakes input file: " << fake_input_val->GetName() <<         std::endl;

	TFile *nonfake_input_val = TFile::Open( "/cms/mchristos/ANN/FireMVA/outFiles/BDTNoIso_TT_NonFakeMuonTree.root" ); 
	std::cout << "--- Using nonfakes input file: " << nonfake_input_val->GetName() <<         std::endl;

	TTree *fake_val = (TTree*)fake_input_val->Get("rootTupleTreeVeryLoose/tree");
	TTree *nonfake_val = (TTree*)nonfake_input_val->Get("rootTupleTreeVeryLoose/tree");

	

  	//Histos to store vallation 
	TH1D *fake_val_histo= new TH1D("fake_val_histo","fake_val_histo",40,-1,1);
	TH1D *nonfake_val_histo= new TH1D("nonfake_val_histo","nonfake_val_histo",40,-1,1);

	fake_val->Draw("(BDT)>>fake_val_histo",WeightExpression);
	nonfake_val->Draw("(BDT)>>nonfake_val_histo",WeightExpression);

	Double_t norm_fake_val = fake_val_histo->GetEntries();
	fake_val_histo->Scale(1/norm_fake_val);

	Double_t norm_nonfake_val = nonfake_val_histo->GetEntries();
	nonfake_val_histo->Scale(1/norm_nonfake_val);

  	//default lumi set to 1 for skimmed files
	fake_events_val += fake_val_histo->Integral()*lumi;
	fake_val_histo->Scale(lumi);

	nonfake_events_val += nonfake_val_histo->Integral()*lumi;
	nonfake_val_histo->Scale(lumi);


	cout<<"fake Events: "<<fake_events_val<<endl;
	cout<<"nonfake Events: "<<nonfake_events_val<<endl;

	//Draw Isolation histograms for fakes and non-fakes
  	

  	nonfake_bdt_test_histo->Draw("HIST");
  	nonfake_bdt_test_histo->SetLineWidth(2);
  	nonfake_bdt_test_histo->SetLineColor(kBlue);
  	nonfake_bdt_test_histo->SetFillColor(38);

  	nonfake_bdt_train_histo->Draw("SAME P");
  	nonfake_bdt_train_histo->SetLineWidth(1);
  	nonfake_bdt_train_histo->SetMarkerStyle(21);
  	nonfake_bdt_train_histo->SetMarkerSize(.7);
  	nonfake_bdt_train_histo->SetMarkerColor(kBlue);
  	nonfake_bdt_train_histo->SetLineColor(kBlue);

  	fake_bdt_train_histo->Draw("SAME P");
  	fake_bdt_train_histo->SetLineWidth(1);
  	fake_bdt_train_histo->SetMarkerStyle(21);
  	fake_bdt_train_histo->SetMarkerSize(.7);
  	fake_bdt_train_histo->SetMarkerColor(kRed);
  	fake_bdt_train_histo->SetLineColor(kRed);

  	fake_bdt_test_histo->Draw("SAME HIST");
  	fake_bdt_test_histo->SetLineWidth(2);
  	fake_bdt_test_histo->SetLineColor(kRed);
  	fake_bdt_test_histo->SetFillColor(kRed);
   	fake_bdt_test_histo->SetFillStyle(3554);
   	//nonfake_bdt_test_histo->SetFillStyle(3554);

   	nonfake_val_histo->Draw("SAME HISTP");
  	nonfake_val_histo->SetLineWidth(2);
  	nonfake_val_histo->SetMarkerStyle(33);
  	nonfake_val_histo->SetMarkerSize(1.5);
  	nonfake_val_histo->SetMarkerColor(kBlue+3);
  	nonfake_val_histo->SetLineColor(kBlue+3);
  
  	fake_val_histo->Draw("SAME HISTP");
  	fake_val_histo->SetLineWidth(2);
  	fake_val_histo->SetMarkerStyle(33);
  	fake_val_histo->SetMarkerSize(1.5);
  	fake_val_histo->SetMarkerColor(kRed+3);
  	fake_val_histo->SetLineColor(kRed+3);
  	

  	nonfake_bdt_test_histo->GetXaxis()->SetTitle("BDT Score");
  	nonfake_bdt_test_histo->SetTitle("BDT Testing, Training, & Validation");

  	cst->Update();

  	TLegend *legend=new TLegend(0.5,0.5,.9,.9);
  	legend->AddEntry(fake_bdt_train_histo,"Fakes - Training");
  	legend->AddEntry(nonfake_bdt_train_histo,"NonFakes - Training");
  	legend->AddEntry(fake_bdt_test_histo,"Fakes - Testing");
  	legend->AddEntry(nonfake_bdt_test_histo,"NonFakes - Testing");
  	legend->AddEntry(fake_val_histo,"Fakes - Validation");
  	legend->AddEntry(nonfake_val_histo,"NonFakes - Validation");
  	legend->SetBorderSize(0);
  	legend->Draw();

  	cst->SaveAs("TT_fakes.png");



}