// Class: ReadShrinkage 3
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::Shrinkage 3
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.14/07       [396807]
Creator        : mchristos
Date           : Wed Nov 14 21:56:19 2018
Host           : Linux cmsbuild02.cern.ch 2.6.32-754.3.5.el6.x86_64 #1 SMP Wed Aug 15 08:57:36 CEST 2018 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /cms/mchristos/ANN/FireMVA/2017
Training events: 158971
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "150" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "2.5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
Shrinkage: "3.000000e+00" [Learning rate for GradBoost algorithm]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "5" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 20
MuonPt                        MuonPt                        MuonPt                        MuonPt                                                          'F'    [10.0003871918,309.485809326]
abs(MuonEta)                  abs_MuonEta_                  abs(MuonEta)                  abs(MuonEta)                                                    'F'    [5.86361784372e-06,2.39989900589]
MuonDXY                       MuonDXY                       MuonDXY                       MuonDXY                                                         'F'    [3.86541465502e-09,0.04999172315]
MuonDZ                        MuonDZ                        MuonDZ                        MuonDZ                                                          'F'    [2.31312702326e-09,0.0999953448772]
MuonSIP3D                     MuonSIP3D                     MuonSIP3D                     MuonSIP3D                                                       'F'    [0.00528861023486,84.1137466431]
MuonPtRatio                   MuonPtRatio                   MuonPtRatio                   MuonPtRatio                                                     'F'    [-1,1.42276537418]
MuonPtRel                     MuonPtRel                     MuonPtRel                     MuonPtRel                                                       'F'    [-1,63.2444343567]
MuonJetLRM                    MuonJetLRM                    MuonJetLRM                    MuonJetLRM                                                      'F'    [-1,0.342095643282]
MuonJetFD                     MuonJetFD                     MuonJetFD                     MuonJetFD                                                       'F'    [-1,1]
MuonJetInOutRatio             MuonJetInOutRatio             MuonJetInOutRatio             MuonJetInOutRatio                                               'F'    [-9999,1]
MuonJetZest                   MuonJetZest                   MuonJetZest                   MuonJetZest                                                     'F'    [-1,1]
MuonJetNoOfConst              MuonJetNoOfConst              MuonJetNoOfConst              MuonJetNoOfConst                                                'F'    [0,63]
MuonJetCSV                    MuonJetCSV                    MuonJetCSV                    MuonJetCSV                                                      'F'    [0,0.999629497528]
MuonRelPFIsoPUCorr            MuonRelPFIsoPUCorr            MuonRelPFIsoPUCorr            MuonRelPFIsoPUCorr                                              'F'    [0,0.999982357025]
MuonRelTrkIso                 MuonRelTrkIso                 MuonRelTrkIso                 MuonRelTrkIso                                                   'F'    [0,69.4224243164]
MuonPFChargedHadronIso        MuonPFChargedHadronIso        MuonPFChargedHadronIso        MuonPFChargedHadronIso                                          'F'    [0,147.538024902]
MuonPFNeutralHadronIso        MuonPFNeutralHadronIso        MuonPFNeutralHadronIso        MuonPFNeutralHadronIso                                          'F'    [0,68.6367034912]
MuonPFPhotonIso               MuonPFPhotonIso               MuonPFPhotonIso               MuonPFPhotonIso                                                 'F'    [0,128.854370117]
MuonJetElectronEnergyFraction MuonJetElectronEnergyFraction MuonJetElectronEnergyFraction MuonJetElectronEnergyFraction                                   'F'    [0,0.836917221546]
MuonJetMuonEnergyFraction     MuonJetMuonEnergyFraction     MuonJetMuonEnergyFraction     MuonJetMuonEnergyFraction                                       'F'    [0,1.00000011921]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new Shrinkage 3Node
   
#ifndef Shrinkage 3Node__def
#define Shrinkage 3Node__def
   
class Shrinkage 3Node {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   Shrinkage 3Node ( Shrinkage 3Node* left,Shrinkage 3Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~Shrinkage 3Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   Shrinkage 3Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   Shrinkage 3Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   Shrinkage 3Node*   fLeft;     // pointer to the left daughter node
   Shrinkage 3Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   Shrinkage 3Node::~Shrinkage 3Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool Shrinkage 3Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool Shrinkage 3Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadShrinkage 3 : public IClassifierReader {

 public:

   // constructor
   ReadShrinkage 3( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadShrinkage 3" ),
        fNvars( 20 ),
        fIsNormalised( false )
   {
      // the training input variables
      const char* inputVars[] = { "MuonPt", "abs(MuonEta)", "MuonDXY", "MuonDZ", "MuonSIP3D", "MuonPtRatio", "MuonPtRel", "MuonJetLRM", "MuonJetFD", "MuonJetInOutRatio", "MuonJetZest", "MuonJetNoOfConst", "MuonJetCSV", "MuonRelPFIsoPUCorr", "MuonRelTrkIso", "MuonPFChargedHadronIso", "MuonPFNeutralHadronIso", "MuonPFPhotonIso", "MuonJetElectronEnergyFraction", "MuonJetMuonEnergyFraction" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;
      fVmin[16] = 0;
      fVmax[16] = 0;
      fVmin[17] = 0;
      fVmax[17] = 0;
      fVmin[18] = 0;
      fVmax[18] = 0;
      fVmin[19] = 0;
      fVmax[19] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';
      fType[19] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadShrinkage 3() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[20];
   double fVmax[20];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[20];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<Shrinkage 3Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadShrinkage 3::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      Shrinkage 3Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(Shrinkage 3Node*)current->GetRight();
         else current=(Shrinkage 3Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadShrinkage 3::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952336,2.71402) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.327738,-1.03357) , 
13, 0.285681, 1, 0, 0.854618,0.354618) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0254606,-2.84724) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.497541,-0.0147517) , 
5, 0.687248, 1, 0, 0.058959,-0.441041) , 
12, 0.571217, 1, 0, 0.5,-4.7281e-15)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897255,0.584366) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436943,-7.08725) , 
15, 1.88412, 1, 0, 0.800175,-0.019321) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507449,5.94384) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0264194,0.61338) , 
12, 0.190406, 1, 0, 0.0750928,0.046063) , 
13, 0.285709, 1, 0, 0.5,0.00774715)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897255,-1.33115) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436943,8066.92) , 
15, 1.88412, 1, 0, 0.800175,0.085338) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507449,-13602.9) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0264194,-1.02343) , 
12, 0.190406, 1, 0, 0.0750928,-0.0721027) , 
13, 0.285709, 1, 0, 0.5,0.0201595)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897255,2.11039) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436943,-1.65937e+34) , 
15, 1.88412, 1, 0, 0.800175,-0.0936358) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507449,5.06885e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0264194,2.9104) , 
12, 0.190406, 1, 0, 0.0750928,0.0664716) , 
13, 0.285709, 1, 0, 0.5,-0.0273533)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897255,-4.5876) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436943,1.28771e+34) , 
15, 1.88412, 1, 0, 0.800175,0.0762082) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.327689,-39.0916) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00816444,-2.24326) , 
12, 0.571217, 1, 0, 0.0750928,-0.396147) , 
13, 0.285709, 1, 0, 0.5,-0.119341)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.936253,6.69934) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0846777,865.847) , 
12, 0.80918, 1, 0, 0.830734,0.639193) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55676,-29.3021) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0313275,5.16712) , 
12, 0.190406, 1, 0, 0.090684,-0.0133482) , 
13, 0.238091, 1, 0, 0.5,0.347567)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.944098,37740.4) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.291489,-8.88852e+27) , 
13, 0.333294, 1, 0, 0.854618,0.0563583) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.19934,-24.6846) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00816444,-260.955) , 
13, 0.285709, 1, 0, 0.058959,-0.79252) , 
12, 0.571217, 1, 0, 0.5,-0.321979)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45438,-7.78429e+21) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0731798,-1.77015e+22) , 
13, 0.142855, 1, 0, 0.117176,-0.0609578) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.972006,2.97852e+19) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.724681,1.54741e+20) , 
13, 0.0473137, 1, 0, 0.872104,0.0896671) , 
5, 0.615177, 1, 0, 0.5,0.0154241)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897255,3.0252e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436943,1.28771e+34) , 
15, 1.88412, 1, 0, 0.800175,0.1138) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507449,-4.92003e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0264194,-2.01754e+33) , 
12, 0.190406, 1, 0, 0.0750928,-0.0702766) , 
13, 0.285709, 1, 0, 0.5,0.0375947)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.940095,-6.92103e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.132333,-2.10022e+34) , 
12, 0.713983, 1, 0, 0.800175,-0.199825) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507449,-4.92003e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0264194,2.34417e+33) , 
12, 0.190406, 1, 0, 0.0750928,-0.0260931) , 
13, 0.285709, 1, 0, 0.5,-0.127902)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897255,9.89382e+34) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436943,-3.38781e+33) , 
15, 1.88412, 1, 0, 0.800175,0.68378) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507449,5.06885e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0264194,-8.6385e+34) , 
12, 0.190406, 1, 0, 0.0750928,-0.823721) , 
13, 0.285709, 1, 0, 0.5,0.059693)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45438,-5.2703e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0731798,-2.97641e+33) , 
13, 0.142855, 1, 0, 0.117176,-0.0701637) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.942088,2.37707e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.391351,4.8414e+33) , 
15, 2.92032, 1, 0, 0.872104,0.0596956) , 
5, 0.615177, 1, 0, 0.5,-0.00431206)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952337,-2.54865e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.19934,-8.875e+33) , 
12, 0.571186, 1, 0, 0.800175,-0.0817503) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39547,4.02038e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0129199,1.06814e+33) , 
12, 0.380811, 1, 0, 0.0750928,0.051546) , 
13, 0.285709, 1, 0, 0.5,-0.0265672)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.830586,3.81325e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.191916,-2.22582e+33) , 
17, 6.13592, 1, 0, 0.756181,0.010936) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.393764,-7.19226e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0153184,-1.16713e+33) , 
13, 0.190473, 1, 0, 0.101438,-0.089596) , 
4, 4.01045, 1, 0, 0.5,-0.0283991)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.847374,-2.52437e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.053425,-1.64224e+33) , 
12, 0.761622, 1, 0, 0.70176,-0.0117116) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.37098,-5.63172e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0167449,-1.5682e+33) , 
13, 0.142855, 1, 0, 0.0743182,-0.0938981) , 
2, 0.00476112, 1, 0, 0.5,-0.0381394)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.932938,-1.80843e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.102747,-7.51181e+33) , 
12, 0.761582, 1, 0, 0.800175,-0.0666978) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507449,-1.30141e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0264194,2.34417e+33) , 
12, 0.190406, 1, 0, 0.0750928,0.010563) , 
13, 0.285709, 1, 0, 0.5,-0.0347128)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.932938,-1.76585e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.102747,-7.51181e+33) , 
12, 0.761582, 1, 0, 0.800175,-0.0663931) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507449,-1.30141e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0264194,2.34417e+33) , 
12, 0.190406, 1, 0, 0.0750928,0.010563) , 
13, 0.285709, 1, 0, 0.5,-0.0345342)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.986001,-1.56815e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.68047,5.35597e+33) , 
13, 0.0476134, 1, 0, 0.84354,0.0385043) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.294588,-6.69452e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0129874,-8.30139e+32) , 
13, 0.142855, 1, 0, 0.051502,-0.0727523) , 
12, 0.618818, 1, 0, 0.5,-0.00975233)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674222,-7.42703e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.119833,-4.08473e+33) , 
13, 0.142855, 1, 0, 0.240341,-0.0751413) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.987364,5.46598e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.830464,-7.16033e+32) , 
2, 0.00237287, 1, 0, 0.966603,-0.00198739) , 
5, 0.730547, 1, 0, 0.5,-0.0489867)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976005,-5.08399e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.527393,2.42316e+33) , 
13, 0.0952269, 1, 0, 0.81845,0.0135528) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228333,-6.40337e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00950648,-9.99787e+32) , 
13, 0.142855, 1, 0, 0.037008,-0.0761839) , 
12, 0.714021, 1, 0, 0.5,-0.0230163)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.857008,1.20226e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0312431,-8.43769e+32) , 
12, 0.761469, 1, 0, 0.756181,0.00246973) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459633,-6.25805e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0197833,-1.08188e+33) , 
13, 0.142855, 1, 0, 0.101438,-0.0786695) , 
4, 4.01045, 1, 0, 0.5,-0.0292776)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.758491,-7.63148e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.136262,-3.05231e+33) , 
13, 0.142855, 1, 0, 0.311971,-0.062339) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.982356,-3.70408e+31) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.971286,5.43255e+32) , 
0, 52.7859, 1, 0, 0.980432,0.00754704) , 
8, 0.809524, 1, 0, 0.5,-0.042681)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.859073,1.70199e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.371831,-8.52333e+32) , 
2, 0.00475286, 1, 0, 0.81845,0.00601394) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228333,-6.40337e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00950648,-9.99787e+32) , 
13, 0.142855, 1, 0, 0.037008,-0.0761839) , 
12, 0.714021, 1, 0, 0.5,-0.027483)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.903085,-2.29541e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302364,9.76631e+32) , 
17, 6.13592, 1, 0, 0.854618,0.00565213) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.271789,-4.15548e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.011545,-1.07033e+32) , 
13, 0.190473, 1, 0, 0.058959,-0.0401073) , 
12, 0.571217, 1, 0, 0.5,-0.0147424)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.788396,-1.4916e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.118917,-2.24327e+33) , 
2, 0.00476112, 1, 0, 0.620313,-0.0128197) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.452091,-1.87227e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.013879,-1.12014e+33) , 
12, 0.237968, 1, 0, 0.0668481,-0.0577285) , 
17, 6.13592, 1, 0, 0.5,-0.022582)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.771096,1.75104e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.666813,7.91039e+32) , 
7, 0.150368, 1, 0, 0.763158,0.00717232) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.422865,-3.20148e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0178687,7.04103e+32) , 
13, 0.285709, 1, 0, 0.158334,-0.0240706) , 
2, 0.00238056, 1, 0, 0.5,-0.00642143)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.974492,-1.17096e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.480053,1.99054e+33) , 
13, 0.0476134, 1, 0, 0.70176,0.00506605) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.235982,-2.37692e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00886613,3.47611e+32) , 
13, 0.285709, 1, 0, 0.0743182,-0.0264653) , 
2, 0.00476112, 1, 0, 0.5,-0.00507317)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.745122,1.37665e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.308332,-2.21138e+33) , 
17, 2.33716, 1, 0, 0.620313,-0.0111119) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.452091,-1.94406e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.013879,-9.40944e+32) , 
12, 0.237968, 1, 0, 0.0668481,-0.0556566) , 
17, 6.13592, 1, 0, 0.5,-0.0207951)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897255,-5.88491e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436943,3.29586e+33) , 
15, 1.88412, 1, 0, 0.800175,-0.0185278) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507449,-1.22724e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0264194,2.34417e+33) , 
12, 0.190406, 1, 0, 0.0750928,0.0113143) , 
13, 0.285709, 1, 0, 0.5,-0.00617354)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897255,-4.63932e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436943,1.53656e+33) , 
15, 1.88412, 1, 0, 0.800175,-0.022204) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507449,-1.14432e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0264194,2.34417e+33) , 
12, 0.190406, 1, 0, 0.0750928,0.0121544) , 
13, 0.285709, 1, 0, 0.5,-0.00798006)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.884476,-7.89965e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.403896,-2.85343e+33) , 
13, 0.149654, 1, 0, 0.800175,-0.0260729) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507449,-1.11727e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0264194,2.34417e+33) , 
12, 0.190406, 1, 0, 0.0750928,0.0124283) , 
13, 0.285709, 1, 0, 0.5,-0.0101339)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897255,-3.96523e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436943,1.33583e+33) , 
15, 1.88412, 1, 0, 0.800175,-0.0188165) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507449,-1.1165e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0264194,2.34417e+33) , 
12, 0.190406, 1, 0, 0.0750928,0.0124361) , 
13, 0.285709, 1, 0, 0.5,-0.00587832)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.892205,-1.34344e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.42897,-2.44089e+33) , 
13, 0.136049, 1, 0, 0.800175,-0.018429) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507449,-9.11187e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0264194,2.34417e+33) , 
12, 0.190406, 1, 0, 0.0750928,0.0145159) , 
13, 0.285709, 1, 0, 0.5,-0.00479018)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897255,-3.55703e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436943,2.10693e+33) , 
15, 1.88412, 1, 0, 0.800175,-0.0103773) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.292895,2.16841e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00620476,4.6534e+32) , 
12, 0.66642, 1, 0, 0.0750928,0.0266796) , 
13, 0.285709, 1, 0, 0.5,0.0049638)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.971389,-3.87187e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457245,-1.87354e+33) , 
15, 3.99366, 1, 0, 0.930866,-0.0221537) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459133,-1.04741e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0264194,2.34417e+33) , 
13, 0.285709, 1, 0, 0.177668,0.00950643) , 
12, 0.190406, 1, 0, 0.5,-0.00404254)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.971389,-2.89355e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457245,-1.70054e+33) , 
15, 3.99366, 1, 0, 0.930866,-0.0194996) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0580814,-3.09972e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499794,1.86287e+33) , 
10, 0.47121, 1, 0, 0.177668,0.0113841) , 
12, 0.190406, 1, 0, 0.5,-0.0018326)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.873381,2.53013e+31) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.396047,-1.75547e+33) , 
17, 3.29777, 1, 0, 0.800175,-0.0123815) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.292895,2.04244e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00620476,4.6534e+32) , 
12, 0.66642, 1, 0, 0.0750928,0.0254035) , 
13, 0.285709, 1, 0, 0.5,0.00326102)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.209757,-2.0276e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.891984,7.06232e+32) , 
10, 0.52381, 1, 0, 0.513108,-0.00613224) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.183396,1.67021e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.614446,8.27178e+32) , 
10, 0.413332, 1, 0, 0.377075,0.043269) , 
7, 0.150368, 1, 0, 0.5,-0.00137205)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897255,-2.82385e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436943,1.80103e+33) , 
15, 1.88412, 1, 0, 0.800175,-0.00731953) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.177804,1.9974e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0232589,1.04402e+32) , 
15, 7.02562, 1, 0, 0.0750928,0.0212909) , 
13, 0.285709, 1, 0, 0.5,0.00452484)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.884476,2.19473e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.403896,-1.68698e+33) , 
13, 0.149654, 1, 0, 0.800175,-0.0105018) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507449,-6.36952e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0264194,2.34417e+33) , 
12, 0.190406, 1, 0, 0.0750928,0.0172939) , 
13, 0.285709, 1, 0, 0.5,0.00100526)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.874864,-1.16062e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0305336,3.28312e+32) , 
12, 0.713962, 1, 0, 0.620171,-0.00632648) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.316975,1.63577e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.728866,7.24295e+32) , 
6, 5.1176, 1, 0, 0.352105,0.0220779) , 
7, 0.0864584, 1, 0, 0.5,0.00640687)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897255,-2.40727e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436943,1.11022e+33) , 
15, 1.88412, 1, 0, 0.800175,-0.009282) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507449,-5.61842e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0264194,2.34417e+33) , 
12, 0.190406, 1, 0, 0.0750928,0.0180548) , 
13, 0.285709, 1, 0, 0.5,0.00203508)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.971389,-6.97318e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457245,-7.15939e+32) , 
15, 3.99366, 1, 0, 0.930866,-0.013849) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0838168,8.51812e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.692521,1.35864e+33) , 
10, 0.559342, 1, 0, 0.177668,0.0162046) , 
12, 0.190406, 1, 0, 0.5,0.00334314)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.940095,-2.62704e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.132333,1.42744e+33) , 
12, 0.713983, 1, 0, 0.800175,-0.00858459) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.292895,1.79812e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00620476,4.6534e+32) , 
12, 0.66642, 1, 0, 0.0750928,0.0229286) , 
13, 0.285709, 1, 0, 0.5,0.00446147)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.971389,-1.04858e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457245,-9.48728e+32) , 
15, 3.99366, 1, 0, 0.930866,-0.0103244) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.176728,4.71168e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.180784,1.57599e+33) , 
7, 0.128186, 1, 0, 0.177668,0.0150076) , 
12, 0.190406, 1, 0, 0.5,0.00416669)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897255,-2.53973e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436943,1.98618e+33) , 
15, 1.88412, 1, 0, 0.800175,-0.00396128) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507449,-5.73594e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0264194,2.34417e+33) , 
12, 0.190406, 1, 0, 0.0750928,0.0179357) , 
13, 0.285709, 1, 0, 0.5,0.0051038)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.971389,-5.56442e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457245,-6.04617e+32) , 
15, 3.99366, 1, 0, 0.930866,-0.0113776) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0838168,8.20493e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.692521,1.267e+33) , 
10, 0.559342, 1, 0, 0.177668,0.0153032) , 
12, 0.190406, 1, 0, 0.5,0.00388511)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.940095,-2.21259e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.132333,1.25676e+33) , 
12, 0.713983, 1, 0, 0.800175,-0.00684014) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.292895,1.81965e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00620476,4.6534e+32) , 
12, 0.66642, 1, 0, 0.0750928,0.0231467) , 
13, 0.285709, 1, 0, 0.5,0.00557403)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897255,-2.29168e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436943,1.9579e+33) , 
15, 1.88412, 1, 0, 0.800175,-0.00238862) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507449,-6.11087e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0264194,2.34417e+33) , 
12, 0.190406, 1, 0, 0.0750928,0.0175559) , 
13, 0.285709, 1, 0, 0.5,0.00586817)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.944307,-2.01632e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.292939,1.30346e+33) , 
13, 0.285681, 1, 0, 0.83226,-0.00516921) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.315796,1.7181e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0151619,2.04771e+32) , 
13, 0.0952364, 1, 0, 0.0443087,0.0191233) , 
12, 0.66642, 1, 0, 0.5,0.00507433)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976809,2.83075e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507657,-1.21197e+33) , 
13, 0.285665, 1, 0, 0.930866,-0.00910259) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.176728,5.38086e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.180784,1.51329e+33) , 
7, 0.128186, 1, 0, 0.177668,0.0150385) , 
12, 0.190406, 1, 0, 0.5,0.00470727)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897255,-2.04897e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436943,1.84516e+33) , 
15, 1.88412, 1, 0, 0.800175,-0.00145849) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507449,-5.75375e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0264194,2.34417e+33) , 
12, 0.190406, 1, 0, 0.0750928,0.0179177) , 
13, 0.285709, 1, 0, 0.5,0.006563)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.940094,-2.09553e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.272676,1.41978e+33) , 
13, 0.285681, 1, 0, 0.81845,-0.00478302) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.277683,1.73613e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0126238,2.15103e+32) , 
13, 0.0952364, 1, 0, 0.037008,0.0200796) , 
12, 0.714021, 1, 0, 0.5,0.00534889)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976809,2.83058e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507657,-1.03722e+33) , 
13, 0.285665, 1, 0, 0.930866,-0.0073903) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.176728,6.97099e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.180784,1.52179e+33) , 
7, 0.128186, 1, 0, 0.177668,0.0162665) , 
12, 0.190406, 1, 0, 0.5,0.00614252)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897255,-1.89452e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436943,1.75523e+33) , 
15, 1.88412, 1, 0, 0.800175,-0.000996805) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507449,-5.73594e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0264194,2.34417e+33) , 
12, 0.190406, 1, 0, 0.0750928,0.0179357) , 
13, 0.285709, 1, 0, 0.5,0.00684102)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.948397,-1.93062e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.309846,1.36432e+33) , 
13, 0.285681, 1, 0, 0.84354,-0.00419398) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.294588,1.94124e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0129874,1.16083e+32) , 
13, 0.142855, 1, 0, 0.051502,0.0198912) , 
12, 0.618818, 1, 0, 0.5,0.00625278)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976809,3.04882e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507657,-6.11087e+32) , 
13, 0.285665, 1, 0, 0.930866,-0.00300061) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.176728,6.85485e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.180784,1.47186e+33) , 
7, 0.128186, 1, 0, 0.177668,0.0158153) , 
12, 0.190406, 1, 0, 0.5,0.007763)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897255,-1.82162e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436943,1.62446e+33) , 
15, 1.88412, 1, 0, 0.800175,-0.00141094) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507449,-5.75375e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0264194,2.34417e+33) , 
12, 0.190406, 1, 0, 0.0750928,0.0179177) , 
13, 0.285709, 1, 0, 0.5,0.00659087)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.940094,-2.00417e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.272676,1.42456e+33) , 
13, 0.285681, 1, 0, 0.81845,-0.00410253) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.277683,1.51918e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0126238,3.30158e+32) , 
13, 0.0952364, 1, 0, 0.037008,0.0190311) , 
12, 0.714021, 1, 0, 0.5,0.00532479)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976809,3.25751e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507657,-1.03722e+33) , 
13, 0.285665, 1, 0, 0.930866,-0.00697194) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.364703,2.24892e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00643631,5.126e+31) , 
12, 0.884026, 1, 0, 0.177668,0.0168624) , 
12, 0.190406, 1, 0, 0.5,0.00666248)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897255,-1.75262e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436943,1.34245e+33) , 
15, 1.88412, 1, 0, 0.800175,-0.00293527) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507449,-5.73594e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0264194,2.3405e+33) , 
12, 0.190406, 1, 0, 0.0750928,0.0178985) , 
13, 0.285709, 1, 0, 0.5,0.00568967)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.940095,-2.05588e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.132333,1.39483e+33) , 
12, 0.713983, 1, 0, 0.800175,-0.00473059) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.25211,1.57307e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00437088,3.08309e+32) , 
12, 0.761622, 1, 0, 0.0750928,0.0190581) , 
13, 0.285709, 1, 0, 0.5,0.00511763)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.830586,-1.08907e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.191916,7.45725e+32) , 
17, 6.13592, 1, 0, 0.756181,-0.00236534) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459633,1.77496e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0197833,7.0509e+31) , 
13, 0.142855, 1, 0, 0.101438,0.0197798) , 
4, 4.01045, 1, 0, 0.5,0.00629938)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540335,1.39071e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.395026,7.58943e+32) , 
7, 0.150368, 1, 0, 0.526468,0.009552) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0557935,-3.68594e+32) , 
18, 0.0398532, 1, 0, 0.5,0.00746911)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976809,3.88736e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507657,-1.57324e+33) , 
13, 0.285665, 1, 0, 0.930866,-0.0116073) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459133,-8.77645e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0264194,2.28225e+33) , 
13, 0.285709, 1, 0, 0.177668,0.010297) , 
12, 0.190406, 1, 0, 0.5,0.000923024)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.948397,-1.26821e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.309846,6.66128e+32) , 
13, 0.285681, 1, 0, 0.84354,-0.00445892) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.294588,1.49908e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0129874,4.40055e+31) , 
13, 0.142855, 1, 0, 0.051502,0.0149194) , 
12, 0.618818, 1, 0, 0.5,0.00394625)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.765273,-4.40583e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.102924,9.8912e+32) , 
4, 4.01045, 1, 0, 0.513108,0.00254566) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.872979,-1.30283e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.197915,8.66467e+32) , 
12, 0.190374, 1, 0, 0.377075,0.0320398) , 
7, 0.150368, 1, 0, 0.5,0.00538765)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.50421,1.436e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.621469,4.42986e+32) , 
1, 2.05706, 1, 0, 0.513108,0.00272224) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.872979,-1.28068e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.197915,8.20066e+32) , 
12, 0.190374, 1, 0, 0.377075,0.0301168) , 
7, 0.150368, 1, 0, 0.5,0.00536192)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.50421,4.80235e+31) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.621469,4.09784e+32) , 
1, 2.05706, 1, 0, 0.513108,0.0021246) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.872979,-1.27285e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.197915,7.54164e+32) , 
12, 0.190374, 1, 0, 0.377075,0.0272827) , 
7, 0.150368, 1, 0, 0.5,0.00454878)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.50421,-6.05836e+30) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.621469,3.94161e+32) , 
1, 2.05706, 1, 0, 0.513108,0.00180111) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.872979,-1.24434e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.197915,7.06561e+32) , 
12, 0.190374, 1, 0, 0.377075,0.025335) , 
7, 0.150368, 1, 0, 0.5,0.00406879)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484357,5.96054e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0420978,-3.44513e+32) , 
18, 0.0398532, 1, 0, 0.457669,0.00118164) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.911153,2.18794e+31) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.710226,5.85272e+32) , 
7, 0.0972572, 1, 0, 0.85225,0.0237339) , 
6, 5.11852, 1, 0, 0.5,0.00360104)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.79284,-8.5802e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0319218,7.69347e+32) , 
12, 0.714021, 1, 0, 0.457669,-0.000416552) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.911153,2.06579e+31) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.710226,5.57535e+32) , 
7, 0.0972572, 1, 0, 0.85225,0.0226019) , 
6, 5.11852, 1, 0, 0.5,0.00205287)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897255,-2.36122e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436943,2.12886e+33) , 
15, 1.88412, 1, 0, 0.800175,-0.00166283) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507449,-1.05374e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0264194,2.15666e+33) , 
12, 0.190406, 1, 0, 0.0750928,0.0111724) , 
13, 0.285709, 1, 0, 0.5,0.00365079)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897255,-1.75351e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436943,1.10689e+33) , 
15, 1.88412, 1, 0, 0.800175,-0.00462734) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.25211,1.45703e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00437088,3.08309e+32) , 
12, 0.761622, 1, 0, 0.0750928,0.0178827) , 
13, 0.285709, 1, 0, 0.5,0.00469153)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.861808,-1.88062e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.111779,2.9356e+32) , 
13, 0.523748, 1, 0, 0.756181,-0.0109335) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459633,1.66888e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0197833,-4.00947e+30) , 
13, 0.142855, 1, 0, 0.101438,0.0178441) , 
4, 4.01045, 1, 0, 0.5,0.000326307)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.451592,9.27614e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.959222,-1.30128e+33) , 
5, 0.615177, 1, 0, 0.854618,-0.00282701) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.325821,1.45654e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0145975,1.5193e+32) , 
13, 0.142855, 1, 0, 0.058959,0.0151346) , 
12, 0.571217, 1, 0, 0.5,0.00517832)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.903085,-1.07371e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302364,4.00244e+32) , 
17, 6.13592, 1, 0, 0.854618,-0.0050951) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.325821,1.26121e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0145975,1.30414e+32) , 
13, 0.142855, 1, 0, 0.058959,0.0130942) , 
12, 0.571217, 1, 0, 0.5,0.00301171)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.102687,4.28902e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.545451,1.39409e+33) , 
8, 0.619048, 1, 0, 0.240341,0.0118993) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.988214,-2.7597e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.697991,1.16503e+32) , 
12, 0.47591, 1, 0, 0.966603,-0.00187047) , 
5, 0.730547, 1, 0, 0.5,0.00697621)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.932938,-1.00895e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.252149,3.85713e+32) , 
13, 0.285681, 1, 0, 0.801141,-0.00428123) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.181836,1.12624e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00738073,-6.11064e+31) , 
13, 0.142855, 1, 0, 0.0280166,0.0114676) , 
12, 0.761622, 1, 0, 0.5,0.00185313)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.184995,-5.10727e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.857495,7.15744e+31) , 
5, 0.499807, 1, 0, 0.756181,-0.00302539) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459633,1.17138e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0197833,-7.66999e+31) , 
13, 0.142855, 1, 0, 0.101438,0.0117328) , 
4, 4.01045, 1, 0, 0.5,0.00274903)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.989382,-7.5697e+30) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.908562,-2.91763e+32) , 
13, 0.0474533, 1, 0, 0.960116,-0.0134605) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.655404,-3.00997e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.351456,1.33716e+33) , 
7, 0.0651668, 1, 0, 0.452678,0.00479222) , 
12, 0.0476014, 1, 0, 0.5,0.00309001)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.500139,-1.36726e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.966895,-2.86824e+32) , 
8, 0.714286, 1, 0, 0.801141,-0.0113624) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.181836,7.30392e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00738073,-1.17811e+32) , 
13, 0.142855, 1, 0, 0.0280166,0.00659528) , 
12, 0.761622, 1, 0, 0.5,-0.00436769)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595749,1.11316e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0216254,-2.95532e+32) , 
4, 15.2367, 1, 0, 0.526468,0.00363316) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0557935,-2.34146e+32) , 
18, 0.0398532, 1, 0, 0.5,0.00244693)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.834521,-1.20369e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.243835,-3.53077e+32) , 
4, 8.01562, 1, 0, 0.801141,-0.0106939) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.181836,5.48769e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00738073,-1.49731e+32) , 
13, 0.142855, 1, 0, 0.0280166,0.00429619) , 
12, 0.761622, 1, 0, 0.5,-0.00485509)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.218539,6.77699e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.875687,-5.93039e+32) , 
10, 0.52381, 1, 0, 0.457669,0.0003977) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459232,3.61481e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.97545,6.90112e+31) , 
10, 0.653143, 1, 0, 0.85225,0.0168282) , 
6, 5.11852, 1, 0, 0.5,0.00216036)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.664656,-8.48466e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0697447,4.06477e+32) , 
2, 0.00476112, 1, 0, 0.457669,-0.00207629) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.911153,1.64202e+31) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.710226,3.3877e+32) , 
7, 0.0972572, 1, 0, 0.85225,0.0138846) , 
6, 5.11852, 1, 0, 0.5,-0.000364004)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.942471,5.029e+30) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.269229,1.34612e+33) , 
13, 0.0952362, 1, 0, 0.599859,0.00686774) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.102916,-4.59293e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00316315,7.61625e+31) , 
13, 0.285709, 1, 0, 0.0290786,-0.00918372) , 
4, 12.0208, 1, 0, 0.5,0.0040595)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.366436,-6.94765e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.931165,-3.93505e+32) , 
8, 0.619048, 1, 0, 0.81845,-0.00770283) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228333,5.61493e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00950648,-2.02482e+32) , 
13, 0.142855, 1, 0, 0.037008,0.00369448) , 
12, 0.714021, 1, 0, 0.5,-0.00305825)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.905534,1.15858e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.144405,-6.26926e+32) , 
13, 0.142855, 1, 0, 0.478152,-0.0035865) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503572,3.2993e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.783674,2.82166e+32) , 
6, 4.29525, 1, 0, 0.532444,0.00637876) , 
1, 1.14281, 1, 0, 0.5,0.000423672)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897255,-2.79155e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436943,2.41811e+33) , 
15, 1.88412, 1, 0, 0.800175,-0.00267245) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507449,-1.35887e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0264194,1.96376e+33) , 
12, 0.190406, 1, 0, 0.0750928,0.00612747) , 
13, 0.285709, 1, 0, 0.5,0.000970606)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897255,-1.73857e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436943,7.97751e+32) , 
15, 1.88412, 1, 0, 0.800175,-0.00673268) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507449,-4.99089e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0264194,1.61282e+33) , 
12, 0.190406, 1, 0, 0.0750928,0.011282) , 
13, 0.285709, 1, 0, 0.5,0.000725156)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.830586,-1.6869e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.191916,5.20176e+32) , 
17, 6.13592, 1, 0, 0.756181,-0.00803775) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459633,1.48943e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0197833,9.45227e+31) , 
13, 0.142855, 1, 0, 0.101438,0.0169768) , 
4, 4.01045, 1, 0, 0.5,0.00174968)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587119,1.03439e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0848351,1.20483e+33) , 
12, 0.142804, 1, 0, 0.117176,0.0190514) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.930152,-1.05342e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.368212,5.53891e+32) , 
2, 0.00474987, 1, 0, 0.872104,-0.00413107) , 
5, 0.615177, 1, 0, 0.5,0.00729558)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.810156,9.1651e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.985639,8.9151e+31) , 
10, 0.52381, 1, 0, 0.94006,0.0135926) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.737063,-9.28693e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.055937,1.05799e+33) , 
12, 0.591618, 1, 0, 0.302042,0.000786117) , 
12, 0.142804, 1, 0, 0.5,0.00475959)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897255,-1.70825e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436943,1.42381e+33) , 
15, 1.88412, 1, 0, 0.800175,-0.0020355) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507449,-4.35906e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0264194,1.54284e+33) , 
12, 0.190406, 1, 0, 0.0750928,0.0112131) , 
13, 0.285709, 1, 0, 0.5,0.00344925)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.906171,-1.24298e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.157008,6.56933e+32) , 
13, 0.285681, 1, 0, 0.70176,-0.0036225) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430577,9.8146e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0232949,2.55752e+32) , 
13, 0.0952364, 1, 0, 0.0743182,0.0161352) , 
2, 0.00476112, 1, 0, 0.5,0.00273077)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.968172,2.73246e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.228289,1.14625e+33) , 
12, 0.713962, 1, 0, 0.888627,0.0124937) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.43603,-7.59071e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0813768,1.8654e+32) , 
13, 0.265302, 1, 0, 0.14631,-0.00458614) , 
13, 0.142855, 1, 0, 0.5,0.00355187)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.765273,1.25002e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.652589,-7.12975e+32) , 
7, 0.150368, 1, 0, 0.756181,-0.00405064) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459633,1.17062e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0197833,2.69002e+31) , 
13, 0.142855, 1, 0, 0.101438,0.012835) , 
4, 4.01045, 1, 0, 0.5,0.0025562)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.923146,5.75295e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.462625,-1.04316e+33) , 
12, 0.217602, 1, 0, 0.801141,-0.00321389) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.181836,8.00987e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00738073,1.6894e+32) , 
13, 0.142855, 1, 0, 0.0280166,0.0104426) , 
12, 0.761622, 1, 0, 0.5,0.00210548)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.91339,-3.43197e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.207283,-5.51772e+32) , 
13, 0.523748, 1, 0, 0.854618,-0.00677091) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.325821,7.46183e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0145975,2.27163e+32) , 
13, 0.142855, 1, 0, 0.058959,0.00915849) , 
12, 0.571217, 1, 0, 0.5,0.000328681)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.752084,6.89276e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.174337,4.39221e+32) , 
13, 0.0476182, 1, 0, 0.240341,0.00736609) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.990981,-9.68136e+31) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.788081,-4.53445e+32) , 
12, 0.285546, 1, 0, 0.966603,-0.00645427) , 
5, 0.730547, 1, 0, 0.5,0.00242492)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.711156,-5.87145e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.596534,-4.34657e+32) , 
7, 0.150368, 1, 0, 0.70176,-0.00631605) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.50172,4.224e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0345644,2.99595e+32) , 
13, 0.0476182, 1, 0, 0.0743182,0.00941593) , 
2, 0.00476112, 1, 0, 0.5,-0.00125728)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.627091,1.18403e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.10924,-7.21008e+31) , 
9, 0.428571, 1, 0, 0.217694,0.00805242) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.960025,-6.51441e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.190874,2.61786e+32) , 
12, 0.76156, 1, 0, 0.888386,-0.00388217) , 
10, 0.52381, 1, 0, 0.5,0.00302894)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.549417,5.05675e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.090581,3.93941e+32) , 
13, 0.0476182, 1, 0, 0.117176,0.00765401) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.978309,4.23378e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.582171,-6.5624e+32) , 
12, 0.19039, 1, 0, 0.872104,-0.00192573) , 
5, 0.615177, 1, 0, 0.5,0.00279612)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.893256,2.61387e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.747329,-8.91326e+32) , 
7, 0.0864584, 1, 0, 0.84354,-0.00466525) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.294588,5.37671e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0129874,1.97193e+32) , 
13, 0.142855, 1, 0, 0.051502,0.00710505) , 
12, 0.618818, 1, 0, 0.5,0.00044002)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.227892,7.64747e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.381509,4.71349e+32) , 
6, 4.19324, 1, 0, 0.240341,0.00806842) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.990485,-4.58281e+31) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.767386,-3.6492e+32) , 
12, 0.333137, 1, 0, 0.966603,-0.00481788) , 
5, 0.730547, 1, 0, 0.5,0.0034612)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.834521,-7.13264e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.243835,-3.20417e+32) , 
4, 8.01562, 1, 0, 0.801141,-0.00710069) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.135101,4.63934e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0120379,-7.68366e+29) , 
12, 0.840973, 1, 0, 0.0280166,0.00498662) , 
12, 0.761622, 1, 0, 0.5,-0.00239254)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.419398,1.37511e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.981784,-1.512e+32) , 
8, 0.809524, 1, 0, 0.620313,0.00655829) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.187631,-4.48758e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0440095,1.96089e+32) , 
13, 0.285709, 1, 0, 0.0668481,-0.00487441) , 
17, 6.13592, 1, 0, 0.5,0.00407304)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.980816,8.95901e+31) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.615266,-1.58471e+33) , 
13, 0.0476134, 1, 0, 0.801141,-0.0102704) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.126899,3.58299e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0101831,-1.88505e+32) , 
12, 0.852306, 1, 0, 0.0280166,0.00182807) , 
12, 0.761622, 1, 0, 0.5,-0.00555792)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897255,-2.3977e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436943,2.314e+33) , 
15, 1.88412, 1, 0, 0.800175,-0.000598939) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.223834,1.44103e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0030712,2.04273e+32) , 
12, 0.809224, 1, 0, 0.0750928,0.0166667) , 
13, 0.285709, 1, 0, 0.5,0.00654882)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.974492,1.66464e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.480053,-1.62827e+33) , 
13, 0.0476134, 1, 0, 0.70176,-0.00903587) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.37098,8.77102e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0167449,1.50097e+32) , 
13, 0.142855, 1, 0, 0.0743182,0.0133963) , 
2, 0.00476112, 1, 0, 0.5,-0.0018226)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.620853,1.05475e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0515761,1.09737e+33) , 
12, 0.190406, 1, 0, 0.117176,0.0183105) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.944357,-3.35206e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166506,2.58579e+32) , 
12, 0.76156, 1, 0, 0.872104,-0.00063369) , 
5, 0.615177, 1, 0, 0.5,0.00870388)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.27821,5.64583e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.579439,6.1699e+32) , 
6, 4.19324, 1, 0, 0.311971,0.00689439) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.994101,-3.94131e+31) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.856979,-2.47712e+32) , 
12, 0.285296, 1, 0, 0.980432,-0.00428069) , 
8, 0.809524, 1, 0, 0.5,0.00375099)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.763037,-1.19854e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.749462,6.57588e+31) , 
0, 24.2618, 1, 0, 0.756181,-0.00780389) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459633,6.89379e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0197833,-7.1509e+31) , 
13, 0.142855, 1, 0, 0.101438,0.00662234) , 
4, 4.01045, 1, 0, 0.5,-0.00215934)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897255,-1.77448e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436943,1.45386e+33) , 
15, 1.88412, 1, 0, 0.800175,-0.00229447) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507449,-4.88163e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0264194,1.65087e+33) , 
12, 0.190406, 1, 0, 0.0750928,0.0117781) , 
13, 0.285709, 1, 0, 0.5,0.00353138)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.752084,1.17078e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.174337,3.22951e+32) , 
13, 0.0476182, 1, 0, 0.240341,0.0097501) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.991796,-1.29181e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.810044,-2.29841e+32) , 
12, 0.237955, 1, 0, 0.966603,-0.00421116) , 
5, 0.730547, 1, 0, 0.5,0.00475855)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.836948,-1.23856e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.197555,3.6527e+32) , 
17, 6.13592, 1, 0, 0.763158,-0.00648298) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.585431,9.60351e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0362726,-6.39355e+31) , 
13, 0.142855, 1, 0, 0.158334,0.00863998) , 
2, 0.00238056, 1, 0, 0.5,9.69949e-05)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976809,1.10993e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.459149,-1.32823e+33) , 
12, 0.190395, 1, 0, 0.800175,-0.00156222) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.223834,1.27022e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0030712,2.04273e+32) , 
12, 0.809224, 1, 0, 0.0750928,0.0149364) , 
13, 0.285709, 1, 0, 0.5,0.00526799)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.981765,7.77744e+31) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59119,-1.5752e+33) , 
13, 0.0952269, 1, 0, 0.854618,-0.0113288) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.325821,1.00129e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0145975,3.02924e+32) , 
13, 0.142855, 1, 0, 0.058959,0.0122718) , 
12, 0.571217, 1, 0, 0.5,-0.000810245)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.848478,1.58348e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.122942,1.13223e+33) , 
12, 0.190406, 1, 0, 0.311971,0.015846) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.994101,-1.17207e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.856979,-2.09503e+32) , 
12, 0.285296, 1, 0, 0.980432,-0.00487084) , 
8, 0.809524, 1, 0, 0.5,0.0100186)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.826547,-1.20249e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.722081,-7.28533e+32) , 
7, 0.150368, 1, 0, 0.81845,-0.0136679) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228333,4.25676e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00950648,1.41706e+32) , 
13, 0.142855, 1, 0, 0.037008,0.00583877) , 
12, 0.714021, 1, 0, 0.5,-0.00571863)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897255,-1.44424e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436943,1.40125e+33) , 
15, 1.88412, 1, 0, 0.800175,-0.000307669) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0517044,7.6874e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34869,5.58727e+32) , 
10, 0.52381, 1, 0, 0.0750928,0.0134471) , 
13, 0.285709, 1, 0, 0.5,0.00538662)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.765273,-3.28125e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.652589,-4.69434e+32) , 
7, 0.150368, 1, 0, 0.756181,-0.00549451) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.393764,1.37324e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0153184,-1.59815e+32) , 
13, 0.190473, 1, 0, 0.101438,0.0130055) , 
4, 4.01045, 1, 0, 0.5,0.001744)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.549417,8.13209e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.090581,2.12646e+32) , 
13, 0.0476182, 1, 0, 0.117176,0.00872807) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.90888,-7.28875e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.322117,2.26649e+32) , 
13, 0.283882, 1, 0, 0.872104,-0.00415333) , 
5, 0.615177, 1, 0, 0.5,0.00219591)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526683,1.31822e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.501199,-7.29945e+31) , 
0, 24.2629, 1, 0, 0.513108,0.00577887) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.872979,1.65799e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.197915,-6.05051e+32) , 
12, 0.190374, 1, 0, 0.377075,-0.0191169) , 
7, 0.150368, 1, 0, 0.5,0.00337997)    );
  // itree = 125
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.973192,7.3967e+31) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499894,-1.54614e+33) , 
13, 0.0952269, 1, 0, 0.801141,-0.0101128) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.135101,3.52247e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0120379,1.12294e+32) , 
12, 0.840973, 1, 0, 0.0280166,0.00500143) , 
12, 0.761622, 1, 0, 0.5,-0.00422563)    );
  // itree = 126
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897255,-1.11269e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436943,1.47882e+33) , 
15, 1.88412, 1, 0, 0.800175,0.00262012) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.327689,1.39989e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00816444,5.44013e+32) , 
12, 0.571217, 1, 0, 0.0750928,0.0196914) , 
13, 0.285709, 1, 0, 0.5,0.00968743)    );
  // itree = 127
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.974492,4.04713e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.480053,-1.27833e+33) , 
13, 0.0476134, 1, 0, 0.70176,-0.00540009) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.313589,1.04488e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0130354,-7.08789e+30) , 
13, 0.190473, 1, 0, 0.0743182,0.0135344) , 
2, 0.00476112, 1, 0, 0.5,0.000688475)    );
  // itree = 128
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.473876,2.17692e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00696332,2.00339e+32) , 
12, 0.856825, 1, 0, 0.240341,0.0155172) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.983171,-3.36194e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.850853,3.04295e+32) , 
13, 0.0942927, 1, 0, 0.966603,-0.000374162) , 
5, 0.730547, 1, 0, 0.5,0.00983557)    );
  // itree = 129
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561766,-3.34536e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.982369,-6.19387e+31) , 
5, 0.730547, 1, 0, 0.801141,-0.0234058) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.181836,2.55132e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00738073,5.30304e+30) , 
13, 0.142855, 1, 0, 0.0280166,0.00280395) , 
12, 0.761622, 1, 0, 0.5,-0.0131968)    );
  // itree = 130
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.610503,4.95005e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0260738,3.44254e+32) , 
12, 0.66642, 1, 0, 0.240341,0.0345577) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.975875,-2.82277e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.876587,2.47675e+32) , 
17, 2.79509, 1, 0, 0.966603,-0.000405868) , 
5, 0.730547, 1, 0, 0.5,0.0220573)    );
  // itree = 131
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.96184,-1.49853e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392778,-4.64172e+33) , 
13, 0.190454, 1, 0, 0.83226,-0.0445251) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.156139,-2.99373e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00620476,4.6534e+32) , 
13, 0.285709, 1, 0, 0.0443087,0.00165058) , 
12, 0.66642, 1, 0, 0.5,-0.025054)    );
  // itree = 132
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.937873,-4.33386e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.314333,5.68537e+32) , 
2, 0.00474987, 1, 0, 0.858845,0.00109342) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.551522,2.7918e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0237198,5.69299e+32) , 
12, 0.285608, 1, 0, 0.113819,0.0292642) , 
13, 0.190473, 1, 0, 0.5,0.014662)    );
  // itree = 133
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.74615,-2.09152e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0642399,2.18168e+32) , 
12, 0.285608, 1, 0, 0.240341,-0.012228) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.983171,2.22106e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.850853,8.80579e+32) , 
13, 0.0942927, 1, 0, 0.966603,0.012934) , 
5, 0.730547, 1, 0, 0.5,-0.0032319)    );
  // itree = 134
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.963273,8.87405e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.385786,1.39673e+33) , 
15, 3.99366, 1, 0, 0.906442,0.0199349) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.35917,-9.92367e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0168461,1.15081e+33) , 
13, 0.285709, 1, 0, 0.124062,0.00127904) , 
12, 0.285608, 1, 0, 0.5,0.0102433)    );
  // itree = 135
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.983189,1.21946e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.545346,-6.88383e+32) , 
13, 0.238054, 1, 0, 0.94006,-0.00765601) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.14551,5.4408e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.882789,6.80423e+32) , 
5, 0.700555, 1, 0, 0.302042,0.00744512) , 
12, 0.142804, 1, 0, 0.5,0.00275969)    );
  // itree = 136
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.677763,-1.28858e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.197032,2.89826e+32) , 
17, 2.4931, 1, 0, 0.499924,-0.00819117) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526363,2.45942e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.306506,2.81821e+32) , 
7, 0.103148, 1, 0, 0.50008,0.00452914) , 
0, 24.2616, 1, 0, 0.5,-0.00197515)    );
  // itree = 137
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.83821,2.26015e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.17019,1.02537e+33) , 
4, 3.69919, 1, 0, 0.620313,0.0067055) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.331594,-2.96845e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00763393,8.4755e+31) , 
12, 0.475936, 1, 0, 0.0668481,-0.00409157) , 
17, 6.13592, 1, 0, 0.5,0.00435842)    );
  // itree = 138
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.858843,3.29105e+31) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350804,-7.53744e+32) , 
13, 0.190468, 1, 0, 0.800175,-0.00515845) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507449,-5.879e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0264194,9.92517e+32) , 
12, 0.190406, 1, 0, 0.0750928,0.00409871) , 
13, 0.285709, 1, 0, 0.5,-0.0013261)    );
  // itree = 139
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.971389,-5.87932e+31) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457245,8.83649e+32) , 
15, 3.99366, 1, 0, 0.930866,0.00808304) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.176728,5.49324e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.180784,-1.01077e+33) , 
7, 0.128186, 1, 0, 0.177668,-0.00338279) , 
12, 0.190406, 1, 0, 0.5,0.00152402)    );
  // itree = 140
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.64037,6.38472e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0302901,-2.94873e+32) , 
4, 8.01562, 1, 0, 0.481,0.0019407) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.850785,-7.42914e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0943256,1.74748e+32) , 
12, 0.618785, 1, 0, 0.554781,-0.00925236) , 
1, 1.48565, 1, 0, 0.5,-0.000941752)    );
  // itree = 141
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.893256,8.17635e+31) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.747329,-1.66661e+33) , 
7, 0.0864584, 1, 0, 0.84354,-0.0117372) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0228106,5.48612e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.371336,-3.02549e+32) , 
10, 0.559342, 1, 0, 0.051502,0.00237906) , 
12, 0.618818, 1, 0, 0.5,-0.00561438)    );
  // itree = 142
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0680913,3.74389e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.886603,-5.0553e+32) , 
5, 0.615177, 1, 0, 0.620171,-0.000996821) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.871398,1.64451e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.157758,6.27329e+32) , 
12, 0.190406, 1, 0, 0.352105,0.0212525) , 
7, 0.0864584, 1, 0, 0.5,0.00897729)    );
  // itree = 143
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.739315,4.53326e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564703,-2.35419e+32) , 
0, 24.2629, 1, 0, 0.620171,0.00165634) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.852535,-8.87136e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.124563,-6.34912e+31) , 
12, 0.238007, 1, 0, 0.352105,-0.00889291) , 
7, 0.0864584, 1, 0, 0.5,-0.00307276)    );
  // itree = 144
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897255,-1.44852e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436943,9.547e+32) , 
15, 1.88412, 1, 0, 0.800175,-0.00353391) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0517044,6.02915e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34869,4.5321e+32) , 
10, 0.52381, 1, 0, 0.0750928,0.0106984) , 
13, 0.285709, 1, 0, 0.5,0.00235809)    );
  // itree = 145
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.609508,7.6828e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.967128,5.97962e+32) , 
19, 0.619048, 1, 0, 0.935478,0.0172789) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.758318,-9.52267e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0456565,2.31352e+32) , 
12, 0.380811, 1, 0, 0.283964,-0.00452306) , 
13, 0.0476182, 1, 0, 0.5,0.00270627)    );
  // itree = 146
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532828,1.53513e+33) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.959737,5.80003e+32) , 
19, 0.619048, 1, 0, 0.879791,0.0170904) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.282541,-6.07568e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.011855,6.68321e+32) , 
13, 0.285709, 1, 0, 0.0901887,0.000529693) , 
12, 0.428413, 1, 0, 0.5,0.00912487)    );
  // itree = 147
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.929717,-4.34168e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.240103,-1.15876e+33) , 
13, 0.523748, 1, 0, 0.879791,-0.012871) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435181,7.93369e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0211035,-1.04518e+32) , 
13, 0.142855, 1, 0, 0.0901887,0.00600593) , 
12, 0.428413, 1, 0, 0.5,-0.00379138)    );
  // itree = 148
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.721448,-1.1327e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0824008,5.02988e+32) , 
2, 0.00476112, 1, 0, 0.526468,0.00173172) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0557935,2.30088e+32) , 
18, 0.0398532, 1, 0, 0.5,0.00259924)    );
  // itree = 149
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976809,8.63365e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.459149,-1.10111e+33) , 
12, 0.190395, 1, 0, 0.800175,-0.00170135) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0517044,2.01405e+32) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34869,4.60383e+32) , 
10, 0.52381, 1, 0, 0.0750928,0.00670381) , 
13, 0.285709, 1, 0, 0.5,0.00177828)    );
   return;
};
 
// Clean up
inline void ReadShrinkage 3::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadShrinkage 3::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
