// Class: ReadMinNodeSize 10
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::MinNodeSize 10
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.14/07       [396807]
Creator        : mchristos
Date           : Wed Nov 14 21:11:05 2018
Host           : Linux cmsbuild02.cern.ch 2.6.32-754.3.5.el6.x86_64 #1 SMP Wed Aug 15 08:57:36 CEST 2018 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /cms/mchristos/ANN/FireMVA/2017
Training events: 158971
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "150" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "10.0%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "5" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 20
MuonPt                        MuonPt                        MuonPt                        MuonPt                                                          'F'    [10.0003871918,309.485809326]
abs(MuonEta)                  abs_MuonEta_                  abs(MuonEta)                  abs(MuonEta)                                                    'F'    [5.86361784372e-06,2.39989900589]
MuonDXY                       MuonDXY                       MuonDXY                       MuonDXY                                                         'F'    [3.86541465502e-09,0.04999172315]
MuonDZ                        MuonDZ                        MuonDZ                        MuonDZ                                                          'F'    [2.31312702326e-09,0.0999953448772]
MuonSIP3D                     MuonSIP3D                     MuonSIP3D                     MuonSIP3D                                                       'F'    [0.00528861023486,84.1137466431]
MuonPtRatio                   MuonPtRatio                   MuonPtRatio                   MuonPtRatio                                                     'F'    [-1,1.42276537418]
MuonPtRel                     MuonPtRel                     MuonPtRel                     MuonPtRel                                                       'F'    [-1,63.2444343567]
MuonJetLRM                    MuonJetLRM                    MuonJetLRM                    MuonJetLRM                                                      'F'    [-1,0.342095643282]
MuonJetFD                     MuonJetFD                     MuonJetFD                     MuonJetFD                                                       'F'    [-1,1]
MuonJetInOutRatio             MuonJetInOutRatio             MuonJetInOutRatio             MuonJetInOutRatio                                               'F'    [-9999,1]
MuonJetZest                   MuonJetZest                   MuonJetZest                   MuonJetZest                                                     'F'    [-1,1]
MuonJetNoOfConst              MuonJetNoOfConst              MuonJetNoOfConst              MuonJetNoOfConst                                                'F'    [0,63]
MuonJetCSV                    MuonJetCSV                    MuonJetCSV                    MuonJetCSV                                                      'F'    [0,0.999629497528]
MuonRelPFIsoPUCorr            MuonRelPFIsoPUCorr            MuonRelPFIsoPUCorr            MuonRelPFIsoPUCorr                                              'F'    [0,0.999982357025]
MuonRelTrkIso                 MuonRelTrkIso                 MuonRelTrkIso                 MuonRelTrkIso                                                   'F'    [0,69.4224243164]
MuonPFChargedHadronIso        MuonPFChargedHadronIso        MuonPFChargedHadronIso        MuonPFChargedHadronIso                                          'F'    [0,147.538024902]
MuonPFNeutralHadronIso        MuonPFNeutralHadronIso        MuonPFNeutralHadronIso        MuonPFNeutralHadronIso                                          'F'    [0,68.6367034912]
MuonPFPhotonIso               MuonPFPhotonIso               MuonPFPhotonIso               MuonPFPhotonIso                                                 'F'    [0,128.854370117]
MuonJetElectronEnergyFraction MuonJetElectronEnergyFraction MuonJetElectronEnergyFraction MuonJetElectronEnergyFraction                                   'F'    [0,0.836917221546]
MuonJetMuonEnergyFraction     MuonJetMuonEnergyFraction     MuonJetMuonEnergyFraction     MuonJetMuonEnergyFraction                                       'F'    [0,1.00000011921]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new MinNodeSize 10Node
   
#ifndef MinNodeSize 10Node__def
#define MinNodeSize 10Node__def
   
class MinNodeSize 10Node {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   MinNodeSize 10Node ( MinNodeSize 10Node* left,MinNodeSize 10Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~MinNodeSize 10Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   MinNodeSize 10Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   MinNodeSize 10Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   MinNodeSize 10Node*   fLeft;     // pointer to the left daughter node
   MinNodeSize 10Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   MinNodeSize 10Node::~MinNodeSize 10Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool MinNodeSize 10Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool MinNodeSize 10Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMinNodeSize 10 : public IClassifierReader {

 public:

   // constructor
   ReadMinNodeSize 10( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadMinNodeSize 10" ),
        fNvars( 20 ),
        fIsNormalised( false )
   {
      // the training input variables
      const char* inputVars[] = { "MuonPt", "abs(MuonEta)", "MuonDXY", "MuonDZ", "MuonSIP3D", "MuonPtRatio", "MuonPtRel", "MuonJetLRM", "MuonJetFD", "MuonJetInOutRatio", "MuonJetZest", "MuonJetNoOfConst", "MuonJetCSV", "MuonRelPFIsoPUCorr", "MuonRelTrkIso", "MuonPFChargedHadronIso", "MuonPFNeutralHadronIso", "MuonPFPhotonIso", "MuonJetElectronEnergyFraction", "MuonJetMuonEnergyFraction" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;
      fVmin[16] = 0;
      fVmax[16] = 0;
      fVmin[17] = 0;
      fVmax[17] = 0;
      fVmin[18] = 0;
      fVmax[18] = 0;
      fVmin[19] = 0;
      fVmax[19] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';
      fType[19] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadMinNodeSize 10() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[20];
   double fVmax[20];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[20];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<MinNodeSize 10Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadMinNodeSize 10::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      MinNodeSize 10Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(MinNodeSize 10Node*)current->GetRight();
         else current=(MinNodeSize 10Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadMinNodeSize 10::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.967891,0.935782) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.432046,-0.135908) , 
13, 0.190454, 1, 0, 0.854618,0.354618) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.17427,-0.65146) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00697059,-0.986059) , 
13, 0.333327, 1, 0, 0.058959,-0.441041) , 
12, 0.571217, 1, 0, 0.5,-4.7281e-15)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0665757,-0.533749) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.216449,-0.225816) , 
10, 0.38713, 1, 0, 0.117176,-0.120109) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.683094,0.184362) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.930836,0.576688) , 
10, 0.523, 1, 0, 0.872104,0.123388) , 
5, 0.615177, 1, 0, 0.5,0.00336866)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.945701,0.342826) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.852535,0.519944) , 
7, 0.0864584, 1, 0, 0.917362,0.0695267) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.562628,0.097634) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0363486,-0.469258) , 
13, 0.142855, 1, 0, 0.143532,-0.0574816) , 
12, 0.238007, 1, 0, 0.5,0.00102531)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.831879,0.275537) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.310601,-0.170109) , 
11, 16.8571, 1, 0, 0.70176,0.0173861) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.152554,-0.421449) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00463026,-0.501858) , 
13, 0.476182, 1, 0, 0.0743182,-0.0498235) , 
2, 0.00476112, 1, 0, 0.5,-0.00422582)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.875793,0.348469) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.321835,-0.201864) , 
15, 1.67269, 1, 0, 0.693498,0.0127213) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0280607,-0.490849) , 
15, 7.02562, 1, 0, 0.5,-0.00220256)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.814857,-0.100892) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.610374,0.271267) , 
7, 0.0864584, 1, 0, 0.737564,0.0100366) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.00182307,-0.46888) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0172448,-0.50026) , 
8, 0.523424, 1, 0, 0.00960304,-0.0243307) , 
12, 0.856825, 1, 0, 0.5,-0.00117885)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649036,-0.184563) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0321634,0.00240262) , 
12, 0.571217, 1, 0, 0.240341,-0.01063) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.993138,0.293908) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.914635,0.263655) , 
12, 0.142773, 1, 0, 0.966603,0.0137097) , 
5, 0.730547, 1, 0, 0.5,-0.00192789)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.923856,-0.0389501) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.19417,0.180555) , 
13, 0.190472, 1, 0, 0.65526,0.00677026) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0471151,-0.359815) , 
4, 8.01562, 1, 0, 0.5,0.000766659)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.786277,0.229327) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390187,-0.12731) , 
17, 1.46073, 1, 0, 0.620313,0.00459481) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0668481,-0.322256) , 
17, 6.13592, 1, 0, 0.5,-0.000704789)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.487915,0.0647537) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.427359,-0.240384) , 
0, 22.3668, 1, 0, 0.457669,-0.00299158) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.85225,0.458894) , 
6, 5.11852, 1, 0, 0.5,-8.42758e-05)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897167,0.0517639) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.691032,-0.343096) , 
3, 0.00476042, 1, 0, 0.854618,-0.00460583) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.172887,0.277737) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00702561,-0.277477) , 
12, 0.877234, 1, 0, 0.058959,0.00614471) , 
12, 0.571217, 1, 0, 0.5,0.000185593)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.339508,-0.0906485) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.980936,0.176796) , 
8, 0.809524, 1, 0, 0.554633,-0.00296911) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.281905,0.154339) , 
16, 3.26841, 1, 0, 0.5,-0.000325211)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.388115,0.126008) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0113087,-0.0421295) , 
12, 0.714021, 1, 0, 0.117176,0.00616851) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.972006,0.0535062) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.724681,-0.170426) , 
13, 0.0473137, 1, 0, 0.872104,-0.0057413) , 
5, 0.615177, 1, 0, 0.5,0.000129044)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0986307,-0.0912414) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0253109,-0.197685) , 
13, 0.666655, 1, 0, 0.0618775,-0.00660262) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.717652,-0.0488075) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.619936,0.236811) , 
7, 0.112162, 1, 0, 0.699124,0.00314126) , 
5, 0.499807, 1, 0, 0.5,9.65386e-05)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.916023,0.00487165) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.627611,-0.218316) , 
13, 0.0906998, 1, 0, 0.858845,-0.00404983) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.276453,0.183028) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0541254,-0.044356) , 
13, 0.383214, 1, 0, 0.113819,0.00438505) , 
13, 0.190473, 1, 0, 0.5,1.28605e-05)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.719547,-0.124437) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0624524,0.0211983) , 
12, 0.238007, 1, 0, 0.194467,-0.00349005) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.941082,0.171895) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.910138,-0.109653) , 
0, 38.5248, 1, 0, 0.932039,0.00513238) , 
8, 0.714286, 1, 0, 0.5,8.17113e-05)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.872526,-0.0219703) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.378958,0.22806) , 
11, 16.8571, 1, 0, 0.763158,0.00450632) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581099,-0.157125) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0318308,-0.0400704) , 
12, 0.666384, 1, 0, 0.158334,-0.005241) , 
2, 0.00238056, 1, 0, 0.5,0.000265277)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.938562,0.0735962) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.280977,-0.0624033) , 
12, 0.142804, 1, 0, 0.488594,-0.00141785) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.599046,0.148617) , 
1, 1.94278, 1, 0, 0.5,-1.788e-05)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.329451,-0.0757169) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.992345,0.21295) , 
5, 0.845916, 1, 0, 0.476231,-0.00304391) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.873717,-0.0182492) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.150953,0.0969582) , 
13, 0.142854, 1, 0, 0.522923,0.00301172) , 
1, 0.914251, 1, 0, 0.5,3.87805e-05)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.825838,0.0976388) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.193204,-0.139664) , 
15, 3.01085, 1, 0, 0.693498,0.00200506) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0280607,-0.141874) , 
15, 7.02562, 1, 0, 0.5,2.52716e-05)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674222,-0.150038) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.977526,-0.0165746) , 
5, 0.730547, 1, 0, 0.888627,-0.00476093) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.481079,0.090415) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0129874,-0.0391438) , 
12, 0.618818, 1, 0, 0.14631,0.0042783) , 
13, 0.142855, 1, 0, 0.5,-2.86011e-05)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.945701,0.0659782) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.852535,-0.16274) , 
7, 0.0864584, 1, 0, 0.917362,-0.00365919) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.427934,0.104396) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0234769,-0.0568879) , 
12, 0.782024, 1, 0, 0.143532,0.00324018) , 
12, 0.238007, 1, 0, 0.5,6.19541e-05)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0494205,-0.0156507) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.117054,0.151567) , 
5, 0.428185, 1, 0, 0.0824122,0.00447695) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.71802,-0.0829265) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.618999,0.0398776) , 
7, 0.0972519, 1, 0, 0.693081,-0.00190946) , 
19, 0.52381, 1, 0, 0.5,0.000109793)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.160025,0.0694458) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.05059,-0.290594) , 
9, 0.714286, 1, 0, 0.105178,-0.00365156) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.565466,0.150917) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.910415,-0.0511188) , 
10, 0.523, 1, 0, 0.815599,0.00290999) , 
8, 0.619048, 1, 0, 0.5,-4.9259e-06)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.070828,0.108243) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.287142,-0.0575116) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.954059,0.0502148) , 
5, 0.705459, 1, 0, 0.624623,-0.00162073) , 
19, 0.476191, 1, 0, 0.5,-0.000150486)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.936489,-0.0649259) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.154887,0.0479226) , 
12, 0.571186, 1, 0, 0.744078,-0.00160928) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0216404,-0.107782) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0922217,0.15748) , 
10, 0.333333, 1, 0, 0.0545346,0.00290471) , 
13, 0.380946, 1, 0, 0.5,-1.14605e-05)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.791668,0.0503439) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.992497,0.0235108) , 
5, 0.730547, 1, 0, 0.930866,0.00270929) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.258287,-0.156275) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.144515,0.0488925) , 
3, 0.00476172, 1, 0, 0.177668,-0.00210422) , 
12, 0.190406, 1, 0, 0.5,-4.42722e-05)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.7208,-0.00958864) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.128982,0.149276) , 
2, 0.00465512, 1, 0, 0.599859,0.0011087) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0290786,-0.237644) , 
4, 12.0208, 1, 0, 0.5,-3.3923e-05)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.896395,0.043804) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.150779,-0.0450975) , 
12, 0.428413, 1, 0, 0.656356,0.00100766) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0453575,-0.111045) , 
2, 0.00714168, 1, 0, 0.5,-8.79086e-05)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.990135,0.00804951) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.72681,-0.0602899) , 
13, 0.0952216, 1, 0, 0.917362,-0.00283495) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0472274,0.00703916) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.435052,0.0788688) , 
10, 0.47121, 1, 0, 0.143532,0.00240564) , 
12, 0.238007, 1, 0, 0.5,-8.46244e-06)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.716009,0.0417145) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0391055,-0.0835657) , 
15, 5.34138, 1, 0, 0.498516,0.00103769) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505116,-0.100125) , 
0, 38.5228, 1, 0, 0.5,2.12398e-05)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.955483,0.00298947) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.521572,-0.0916994) , 
2, 0.00237494, 1, 0, 0.858845,-0.00211013) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431987,0.0752964) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.011545,-0.110971) , 
12, 0.571217, 1, 0, 0.113819,0.00225934) , 
13, 0.190473, 1, 0, 0.5,-5.55862e-06)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.847436,-0.0691726) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.861992,0.0281392) , 
0, 24.2618, 1, 0, 0.854618,-0.00255702) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.118182,0.104158) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00277219,-0.150688) , 
12, 0.938432, 1, 0, 0.058959,0.00309991) , 
12, 0.571217, 1, 0, 0.5,-3.57774e-05)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.380731,-0.0281325) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.746426,0.121127) , 
6, 4.29525, 1, 0, 0.43291,-0.000657531) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.996212,0.360724) , 
8, 0.904762, 1, 0, 0.5,-1.91952e-05)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.120276,0.0874519) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.110204,-0.0769038) , 
16, 3.26841, 1, 0, 0.117176,0.00254124) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.683094,0.0601948) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.930836,-0.129798) , 
10, 0.523, 1, 0, 0.872104,-0.00216848) , 
5, 0.615177, 1, 0, 0.5,0.00015294)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.627091,0.198108) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.10924,-0.143489) , 
9, 0.428571, 1, 0, 0.217694,-0.00185765) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.937446,-0.00960712) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.807073,0.0980056) , 
7, 0.0713314, 1, 0, 0.888386,0.00276945) , 
10, 0.52381, 1, 0, 0.5,8.99757e-05)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430588,0.0445156) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0147186,0.0385273) , 
12, 0.618818, 1, 0, 0.117176,0.00256841) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679559,-0.111647) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.966395,0.0598889) , 
8, 0.767965, 1, 0, 0.872104,-0.00238649) , 
5, 0.615177, 1, 0, 0.5,5.57807e-05)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.944537,0.0514368) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.869553,-0.156476) , 
13, 0.0226752, 1, 0, 0.913953,-0.0024503) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0935094,-0.00780618) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.676567,0.102765) , 
5, 0.641544, 1, 0, 0.197898,0.00189313) , 
13, 0.0952364, 1, 0, 0.5,6.06474e-05)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.896282,0.0235292) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.145765,-0.0912061) , 
12, 0.428377, 1, 0, 0.65526,-0.000950367) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0471151,0.131712) , 
4, 8.01562, 1, 0, 0.5,0.000132955)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.990135,0.0354791) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.72681,-0.056976) , 
13, 0.0952216, 1, 0, 0.917362,-0.00219877) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.148741,-0.0237531) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.133545,0.11015) , 
7, 0.112164, 1, 0, 0.143532,0.0018039) , 
12, 0.238007, 1, 0, 0.5,-3.99443e-05)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.799742,0.065326) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.582726,-0.0105489) , 
3, 0.00136039, 1, 0, 0.672664,0.00110928) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417977,-0.0906126) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0108498,0.233344) , 
12, 0.856825, 1, 0, 0.152738,-0.00225415) , 
3, 0.00952337, 1, 0, 0.5,-7.694e-06)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.185055,0.00153458) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.879632,-0.154919) , 
10, 0.52381, 1, 0, 0.478993,-0.00252778) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.437632,-0.0156627) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.570676,0.0429417) , 
6, 2.05926, 1, 0, 0.507104,0.000783094) , 
1, 0.457128, 1, 0, 0.5,-5.36174e-05)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.914782,0.0184893) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.203356,-0.0737821) , 
12, 0.33321, 1, 0, 0.70176,-0.000970052) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.112247,0.137384) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0363822,-0.176445) , 
0, 22.3668, 1, 0, 0.0743182,0.00217574) , 
2, 0.00476112, 1, 0, 0.5,4.15081e-05)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.773996,-0.0134675) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.339821,0.0546166) , 
3, 0.00476169, 1, 0, 0.623981,0.000920705) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0338582,-0.142012) , 
2, 0.00952224, 1, 0, 0.5,-5.15318e-05)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674898,0.0805805) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.52685,-0.0930166) , 
0, 38.524, 1, 0, 0.620171,0.00138068) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.347226,-0.114645) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.361868,0.103571) , 
7, 0.135151, 1, 0, 0.352105,-0.00175874) , 
7, 0.0864584, 1, 0, 0.5,-2.6687e-05)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266022,-0.0468) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00311208,0.00257345) , 
12, 0.856825, 1, 0, 0.105178,-0.00238306) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.831411,-0.00858063) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.779129,0.0789772) , 
7, 0.081214, 1, 0, 0.815599,0.00198444) , 
8, 0.619048, 1, 0, 0.5,4.42098e-05)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.796478,0.037925) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0200753,-0.0951952) , 
12, 0.761622, 1, 0, 0.481,0.000923155) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529177,-0.0919128) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.576613,0.0455617) , 
0, 20.6788, 1, 0, 0.554781,-0.00257641) , 
1, 1.48565, 1, 0, 0.5,2.19418e-05)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.967891,-0.100333) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.432046,0.0238308) , 
13, 0.190454, 1, 0, 0.854618,-0.00182255) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.135262,0.0771223) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00417913,-0.0689863) , 
12, 0.918032, 1, 0, 0.058959,0.00226438) , 
12, 0.571217, 1, 0, 0.5,-1.03772e-06)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.854236,-0.0222032) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.775473,0.111859) , 
16, 1.39059, 1, 0, 0.830734,0.00145089) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.190548,-0.0671963) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0455706,0.0141752) , 
13, 0.455784, 1, 0, 0.090684,-0.0016247) , 
13, 0.238091, 1, 0, 0.5,7.63882e-05)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.264419,0.00185461) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.903059,-0.0752412) , 
10, 0.609632, 1, 0, 0.381467,-0.000623117) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.988298,0.162561) , 
19, 0.857143, 1, 0, 0.5,4.24149e-05)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0834386,0.0192901) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30495,-0.0476974) , 
10, 0.386194, 1, 0, 0.166916,-0.00114574) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.902326,-0.0381578) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.853271,0.0931546) , 
7, 0.0692013, 1, 0, 0.885683,0.00148368) , 
19, 0.666667, 1, 0, 0.5,7.27579e-05)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.054777,-0.0492552) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.813111,-0.00765123) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.102569,0.0691209) , 
13, 0.333326, 1, 0, 0.640889,0.000684766) , 
8, 0.52381, 1, 0, 0.5,4.24436e-05)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.833844,-0.0453233) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.221309,0.000867481) , 
12, 0.142804, 1, 0, 0.311971,-0.000712546) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.983551,-0.0432763) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.976904,0.170172) , 
11, 7.28571, 1, 0, 0.980432,0.00177262) , 
8, 0.809524, 1, 0, 0.5,-1.35039e-05)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430588,0.0309617) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0147186,0.000133277) , 
12, 0.618818, 1, 0, 0.117176,0.00144755) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.642171,-0.0557836) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.954319,0.0107137) , 
8, 0.742184, 1, 0, 0.872104,-0.00127888) , 
5, 0.615177, 1, 0, 0.5,6.4977e-05)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0861005,-0.0284473) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.541097,0.0474098) , 
5, 0.56573, 1, 0, 0.240341,0.000848857) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.965729,-0.210488) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.96713,0.0461864) , 
0, 24.2623, 1, 0, 0.966603,-0.00149612) , 
5, 0.730547, 1, 0, 0.5,1.0461e-05)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.714636,0.04404) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.052032,-0.0782682) , 
15, 4.47501, 1, 0, 0.499924,0.0014292) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.192527,-0.0713179) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.985039,0.0979504) , 
5, 0.780156, 1, 0, 0.50008,-0.00126031) , 
0, 24.2616, 1, 0, 0.5,0.000114921)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.944405,-0.0258305) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.916478,-0.132773) , 
1, 1.48512, 1, 0, 0.935478,-0.00224624) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.106097,0.000724833) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.779882,0.0456499) , 
5, 0.641544, 1, 0, 0.283964,0.00113565) , 
13, 0.0476182, 1, 0, 0.5,1.42482e-05)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0986307,0.0356939) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0253109,0.138356) , 
13, 0.666655, 1, 0, 0.0618775,0.0026821) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.25561,-0.0562677) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.868146,0.00595107) , 
8, 0.65222, 1, 0, 0.699124,-0.00115371) , 
5, 0.499807, 1, 0, 0.5,4.48894e-05)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.816186,-0.0340082) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.135098,0.046635) , 
2, 0.00476111, 1, 0, 0.658904,-0.00090365) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.247194,0.106241) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0349867,-0.107839) , 
17, 6.13592, 1, 0, 0.139931,0.0019428) , 
11, 18, 1, 0, 0.5,-3.20966e-05)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.697434,0.0115615) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.227339,-0.135993) , 
17, 3.50574, 1, 0, 0.620313,-0.000898479) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0668481,0.0833592) , 
17, 6.13592, 1, 0, 0.5,-8.95807e-06)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.045906,-0.0483708) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.158604,0.0360284) , 
8, 0.498247, 1, 0, 0.117176,0.00101134) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.937665,0.01148) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.667789,-0.0528369) , 
3, 0.00476169, 1, 0, 0.872104,-0.00101347) , 
5, 0.615177, 1, 0, 0.5,-1.54409e-05)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.94915,-0.0484285) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435885,-0.0133401) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.346515,0.046468) , 
7, 0.130327, 1, 0, 0.418499,0.000315381) , 
12, 0.0952028, 1, 0, 0.5,2.52652e-06)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266022,-0.0300684) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00311208,0.0766842) , 
12, 0.856825, 1, 0, 0.105178,-0.00133613) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.883955,-0.04143) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.761735,0.0355217) , 
7, 0.0541442, 1, 0, 0.815599,0.00108021) , 
8, 0.619048, 1, 0, 0.5,6.7674e-06)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.463561,0.0343262) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.92997,-0.00635666) , 
10, 0.428571, 1, 0, 0.81845,0.000903326) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0588033,-0.115244) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0207882,0.0866176) , 
4, 7.62921, 1, 0, 0.037008,-0.00130014) , 
12, 0.714021, 1, 0, 0.5,5.37972e-06)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.82476,0.053301) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.49534,-0.0117686) , 
2, 0.000566785, 1, 0, 0.60004,0.000414764) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0273308,-0.0954938) , 
2, 0.0119028, 1, 0, 0.5,-3.54892e-05)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.990135,0.028408) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.72681,-0.0408925) , 
13, 0.0952216, 1, 0, 0.917362,-0.00150116) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.038294,-0.00354264) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.463177,0.0468439) , 
8, 0.63534, 1, 0, 0.143532,0.00128381) , 
12, 0.238007, 1, 0, 0.5,8.99851e-07)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.905081,0.00606861) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.395031,-0.0447026) , 
3, 0.00952337, 1, 0, 0.800175,-0.000788491) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0996735,-0.00346182) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0440095,0.0891559) , 
17, 6.13592, 1, 0, 0.0750928,0.00115108) , 
13, 0.285709, 1, 0, 0.5,1.44664e-05)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.726738,-0.0161412) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.270078,0.0784014) , 
11, 16.3333, 1, 0, 0.620313,0.000502314) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0668481,-0.0464264) , 
17, 6.13592, 1, 0, 0.5,-1.05591e-05)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.839229,0.0316914) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0832514,-0.0401691) , 
15, 4.38202, 1, 0, 0.658904,0.000951155) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.376854,-0.0554127) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00587778,0.0413898) , 
12, 0.809224, 1, 0, 0.139931,-0.002162) , 
11, 18, 1, 0, 0.5,-2.06087e-06)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976809,0.0111617) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.459149,-0.0270308) , 
12, 0.190395, 1, 0, 0.800175,-0.000819332) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0299019,-0.00111271) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.119978,0.0349329) , 
8, 0.52381, 1, 0, 0.0750928,0.00116538) , 
13, 0.285709, 1, 0, 0.5,2.31584e-06)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.939201,-0.000401711) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.706415,-0.0265987) , 
12, 0.158666, 1, 0, 0.871023,-0.000920123) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0518443,-0.0237775) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.133342,0.0728925) , 
1, 1.25709, 1, 0, 0.0795519,0.0010437) , 
12, 0.476014, 1, 0, 0.5,4.71092e-07)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.906255,0.10318) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.488028,-0.0586369) , 
15, 0.669078, 1, 0, 0.693498,-0.000441036) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0280607,0.0410676) , 
15, 7.02562, 1, 0, 0.5,-5.31032e-06)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.714204,-0.074809) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.983049,-0.0180028) , 
5, 0.730547, 1, 0, 0.913953,-0.00210605) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0504703,-0.0182488) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.435766,0.051939) , 
5, 0.538947, 1, 0, 0.197898,0.0016492) , 
13, 0.0952364, 1, 0, 0.5,6.48685e-05)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0483753,-0.0538486) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.139584,0.0571194) , 
10, 0.289148, 1, 0, 0.102201,0.00144639) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.358687,-0.0617058) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.918526,0.021466) , 
8, 0.698242, 1, 0, 0.764447,-0.000921563) , 
19, 0.571429, 1, 0, 0.5,2.40062e-05)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428181,-0.0141398) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.600136,0.113725) , 
6, 3.37006, 1, 0, 0.457669,0.000341282) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.85225,-0.0845371) , 
6, 5.11852, 1, 0, 0.5,-2.17027e-06)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.109964,0.0493715) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.217684,-0.0343721) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.897038,0.00790607) , 
8, 0.667585, 1, 0, 0.647216,-0.000776914) , 
10, 0.333333, 1, 0, 0.5,2.32585e-05)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.618928,0.0199973) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0360184,0.00713497) , 
12, 0.380811, 1, 0, 0.166916,0.000952944) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.771164,-0.0435999) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.986036,0.0497648) , 
8, 0.831395, 1, 0, 0.885683,-0.00111369) , 
19, 0.666667, 1, 0, 0.5,-4.75533e-06)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.887412,0.162141) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.284866,-0.023268) , 
9, 0.238095, 1, 0, 0.384028,0.00048647) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.984176,-0.137424) , 
10, 0.714286, 1, 0, 0.5,1.63259e-05)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.954461,-0.150707) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.932166,0.0142505) , 
12, 0.0748022, 1, 0, 0.94006,-0.00126178) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.342788,0.0246039) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166168,-0.0825948) , 
0, 34.7332, 1, 0, 0.302042,0.000734273) , 
12, 0.142804, 1, 0, 0.5,0.000114956)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.487915,-0.0221011) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.427359,0.0348382) , 
0, 22.3668, 1, 0, 0.457669,-0.000290262) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.85225,0.0761816) , 
6, 5.11852, 1, 0, 0.5,3.51371e-05)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.739265,0.0755756) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.375147,-0.0115602) , 
7, 0.0864584, 1, 0, 0.499924,0.000908436) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.958437,0.116942) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.38056,-0.05787) , 
12, 0.095195, 1, 0, 0.50008,-0.000934604) , 
0, 24.2616, 1, 0, 0.5,7.79953e-06)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.951311,0.0376113) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.478456,-0.0552841) , 
11, 7.28571, 1, 0, 0.620171,-0.0011445) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0957492,-0.0222786) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.666621,0.0490538) , 
8, 0.569992, 1, 0, 0.352105,0.00146839) , 
7, 0.0864584, 1, 0, 0.5,2.68238e-05)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.070828,0.0418668) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.107329,-0.0552419) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.756564,0.00302722) , 
8, 0.58346, 1, 0, 0.624623,-0.000490716) , 
19, 0.476191, 1, 0, 0.5,1.64377e-05)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430588,0.0192976) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0147186,0.004834) , 
12, 0.618818, 1, 0, 0.117176,0.000916839) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.972006,-0.107101) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.724681,0.013732) , 
13, 0.0473137, 1, 0, 0.872104,-0.000905426) , 
5, 0.615177, 1, 0, 0.5,-7.231e-06)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.990135,0.0264928) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.72681,-0.0330096) , 
13, 0.0952216, 1, 0, 0.917362,-0.0011308) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515166,0.0358448) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0485097,0.0028886) , 
12, 0.636954, 1, 0, 0.143532,0.00104627) , 
12, 0.238007, 1, 0, 0.5,4.33959e-05)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493265,-0.0416032) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.503295,0.0144318) , 
0, 14.0749, 1, 0, 0.499924,-0.000749875) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.087877,-0.0490684) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.783767,0.0609829) , 
10, 0.427145, 1, 0, 0.50008,0.000801139) , 
0, 24.2616, 1, 0, 0.5,8.05754e-06)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.226,0.0319926) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.031771,-0.00755031) , 
13, 0.476182, 1, 0, 0.105178,0.000919709) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.686688,-0.0239708) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.987256,0.0630761) , 
8, 0.836736, 1, 0, 0.815599,-0.000717415) , 
8, 0.619048, 1, 0, 0.5,9.86494e-06)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.727349,0.0240817) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0571399,-0.0147731) , 
12, 0.33321, 1, 0, 0.240341,0.000538005) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.945393,-0.0684583) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.995435,0.157646) , 
8, 0.884228, 1, 0, 0.966603,-0.000931359) , 
5, 0.730547, 1, 0, 0.5,1.26656e-05)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.831879,-0.0278489) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.310601,0.0263943) , 
11, 16.8571, 1, 0, 0.70176,-0.000611728) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.151829,0.0487369) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00134333,-0.143148) , 
12, 0.951977, 1, 0, 0.0743182,0.00142313) , 
2, 0.00476112, 1, 0, 0.5,4.26009e-05)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.572965,-0.00344658) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.474362,0.0551268) , 
16, 1.71199, 1, 0, 0.554633,0.000430945) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.281905,-0.0330807) , 
16, 3.26841, 1, 0, 0.5,-5.68399e-06)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418773,-0.0236252) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0127124,0.0304617) , 
12, 0.714021, 1, 0, 0.130486,-0.000798395) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.913254,-0.154655) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.777147,0.0435392) , 
7, 0.0480519, 1, 0, 0.829651,0.000717574) , 
19, 0.619048, 1, 0, 0.5,2.80608e-06)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.797959,0.0125435) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0169095,-0.0634522) , 
12, 0.809157, 1, 0, 0.569053,0.000332879) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.094552,-0.0386565) , 
3, 0.0285701, 1, 0, 0.5,4.82236e-05)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.966184,0.062833) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.661539,-0.0254965) , 
12, 0.0951871, 1, 0, 0.735461,-0.000794257) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.376699,0.0400141) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0403785,-0.0512288) , 
2, 0.00714169, 1, 0, 0.216646,0.000941028) , 
3, 0.00476169, 1, 0, 0.5,-6.70906e-06)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.94915,-0.056648) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.171944,-0.0121436) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.895447,0.0485778) , 
8, 0.705406, 1, 0, 0.418499,0.000359621) , 
12, 0.0952028, 1, 0, 0.5,6.72631e-06)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228592,0.0459415) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0722277,-0.00687909) , 
11, 15, 1, 0, 0.117176,0.000988186) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.683094,0.0209197) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.930836,-0.0481546) , 
10, 0.523, 1, 0, 0.872104,-0.000923462) , 
5, 0.615177, 1, 0, 0.5,1.87891e-05)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614721,-0.00454394) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0325317,0.104564) , 
2, 0.00952224, 1, 0, 0.488594,0.000278593) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.599046,-0.0304836) , 
1, 1.94278, 1, 0, 0.5,1.49712e-05)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.950384,0.0088885) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.240372,-0.0266435) , 
12, 0.333192, 1, 0, 0.717202,-0.000519798) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0595737,0.00515118) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0365225,0.0719605) , 
17, 6.13592, 1, 0, 0.0485243,0.0010505) , 
13, 0.428564, 1, 0, 0.5,-9.72925e-06)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.967891,-0.0525563) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.432046,0.0140864) , 
13, 0.190454, 1, 0, 0.854618,-0.000923351) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0400038,-0.0175145) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0942349,0.0970341) , 
6, 2.53378, 1, 0, 0.058959,0.00113406) , 
12, 0.571217, 1, 0, 0.5,-6.37993e-06)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.930609,-0.0101318) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.67369,0.0387839) , 
11, 11.6667, 1, 0, 0.830734,0.000959582) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.156981,-0.0342073) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00645305,0.176857) , 
4, 8.01874, 1, 0, 0.090684,-0.00114707) , 
13, 0.238091, 1, 0, 0.5,1.81044e-05)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.42059,0.0068272) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0721059,-0.0531891) , 
3, 0.00952338, 1, 0, 0.264769,-0.000697282) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.949297,0.0777497) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.965398,-0.0297903) , 
6, 3.01164, 1, 0, 0.956569,0.00126797) , 
19, 0.761905, 1, 0, 0.5,-2.90421e-05)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588708,-0.00296052) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.666223,0.0419876) , 
1, 1.8285, 1, 0, 0.60004,0.000332263) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0273308,-0.0665818) , 
2, 0.0119028, 1, 0, 0.5,1.56668e-05)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0562872,0.040126) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.678848,-0.00439012) , 
5, 0.499807, 1, 0, 0.484444,0.00028219) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.573085,-0.0189471) , 
1, 1.71422, 1, 0, 0.5,-1.8183e-06)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.070828,-0.03129) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.60993,-0.00248191) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.674661,0.0298351) , 
1, 1.59993, 1, 0, 0.624623,0.000392434) , 
19, 0.476191, 1, 0, 0.5,-3.14106e-06)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.798713,0.0239894) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0168936,-0.0416333) , 
12, 0.761479, 1, 0, 0.476231,0.000724846) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72352,-0.0274821) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.20714,0.0128019) , 
3, 0.00952339, 1, 0, 0.522923,-0.000698822) , 
1, 0.914251, 1, 0, 0.5,1.11331e-07)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.814857,0.0170818) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.610374,-0.0190233) , 
7, 0.0864584, 1, 0, 0.737564,-0.000410675) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0174794,0.120701) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00157428,-0.116926) , 
12, 0.97243, 1, 0, 0.00960304,0.000856046) , 
12, 0.856825, 1, 0, 0.5,2.70811e-06)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.85579,-0.0742328) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.955102,0.0509585) , 
0, 20.4947, 1, 0, 0.911586,-0.00149826) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601751,0.0371436) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.170074,-0.0272272) , 
9, 0.619048, 1, 0, 0.373917,0.000428127) , 
11, 9, 1, 0, 0.5,-2.361e-05)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.874864,0.00840871) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0305336,-0.166166) , 
12, 0.713962, 1, 0, 0.620171,-0.000741758) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.669873,-0.0927008) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.260826,0.0505602) , 
9, 0.428571, 1, 0, 0.352105,0.00095674) , 
7, 0.0864584, 1, 0, 0.5,1.96583e-05)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.445558,0.0680794) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.410619,-0.00723178) , 
6, 0.893813, 1, 0, 0.42036,0.000864753) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.923679,0.12793) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326449,-0.0657328) , 
9, 0.428571, 1, 0, 0.566377,-0.000730142) , 
6, 2.05926, 1, 0, 0.5,-5.13004e-06)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.859724,0.00945713) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.241337,-0.0952069) , 
11, 12.1429, 1, 0, 0.620171,-0.000879741) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.669873,-0.0537262) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.260826,0.040669) , 
9, 0.428571, 1, 0, 0.352105,0.00119961) , 
7, 0.0864584, 1, 0, 0.5,5.24066e-05)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.967891,-0.0445886) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.432046,0.0167856) , 
13, 0.190454, 1, 0, 0.854618,-0.000579821) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.00675064,-0.0720739) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.107422,0.0367042) , 
5, 0.471108, 1, 0, 0.058959,0.000728192) , 
12, 0.571217, 1, 0, 0.5,3.14885e-06)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.822417,0.0428419) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.882405,-0.0127551) , 
6, 2.05926, 1, 0, 0.858845,0.000773717) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.173875,-0.0207452) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00660553,0.113884) , 
2, 0.00952224, 1, 0, 0.113819,-0.000815247) , 
13, 0.190473, 1, 0, 0.5,8.38617e-06)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.817735,-0.00446606) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.275113,0.0220104) , 
11, 15, 1, 0, 0.604007,0.000423428) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.11343,-0.0352136) , 
3, 0.0190467, 1, 0, 0.5,-4.2039e-06)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.109964,-0.0233688) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679722,-0.00831305) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.481129,0.0393187) , 
7, 0.127172, 1, 0, 0.647216,0.000380749) , 
10, 0.333333, 1, 0, 0.5,-1.23364e-06)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.160025,-0.03806) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.05059,0.034506) , 
9, 0.714286, 1, 0, 0.105178,-0.000795903) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.783238,0.0250817) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.861258,-0.020418) , 
6, 3.01164, 1, 0, 0.815599,0.000639295) , 
8, 0.619048, 1, 0, 0.5,1.71949e-06)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499185,0.00497869) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.495145,-0.11394) , 
0, 30.373, 1, 0, 0.498516,-0.000269833) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505116,0.0361944) , 
0, 38.5228, 1, 0, 0.5,8.32972e-07)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.862325,0.0312752) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.220658,-0.0332389) , 
15, 1.11875, 1, 0, 0.499924,-0.000659799) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.75858,0.0586766) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.103329,-0.0806568) , 
2, 0.00238057, 1, 0, 0.50008,0.00069773) , 
0, 24.2616, 1, 0, 0.5,3.58312e-06)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.269519,0.0515174) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0687852,-0.0417556) , 
11, 18, 1, 0, 0.154875,0.000661967) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.310176,-0.0390133) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.910578,0.0118266) , 
8, 0.667585, 1, 0, 0.77067,-0.000504312) , 
10, 0.428571, 1, 0, 0.5,8.32025e-06)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.413142,-0.0315863) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.904746,0.00180764) , 
10, 0.52381, 1, 0, 0.739152,-0.000830296) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.168895,-0.0323927) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.25902,0.0571577) , 
7, 0.117987, 1, 0, 0.201129,0.0010326) , 
11, 15, 1, 0, 0.5,-2.23448e-06)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.924544,0.0307582) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.890518,-0.0793314) , 
1, 1.48512, 1, 0, 0.913953,-0.000619359) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.195367,-0.0111372) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.204968,0.0457576) , 
1, 1.37137, 1, 0, 0.197898,0.000450123) , 
13, 0.0952364, 1, 0, 0.5,-1.08902e-06)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.054777,-0.0219378) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.24135,0.0352506) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.750492,-0.00442894) , 
10, 0.383079, 1, 0, 0.640889,0.000290581) , 
8, 0.52381, 1, 0, 0.5,1.93656e-05)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421579,0.0197788) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0560327,-0.0425439) , 
9, 0.52381, 1, 0, 0.154875,-0.000613705) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.841576,-0.0154932) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.622789,0.0273659) , 
7, 0.0894592, 1, 0, 0.77067,0.00047931) , 
10, 0.428571, 1, 0, 0.5,-1.11959e-06)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.762079,-0.00577152) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.218619,0.0536264) , 
3, 0.00952209, 1, 0, 0.620171,0.000472922) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.193361,-0.0237879) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.879958,0.0450999) , 
8, 0.663619, 1, 0, 0.352105,-0.000584935) , 
7, 0.0864584, 1, 0, 0.5,-1.30248e-06)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461462,0.0260225) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0165454,-0.00185434) , 
12, 0.618818, 1, 0, 0.130486,0.00110481) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485568,-0.036388) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.95516,0.00129459) , 
5, 0.705459, 1, 0, 0.829651,-0.000971801) , 
19, 0.619048, 1, 0, 0.5,7.30654e-06)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.607497,-0.00749839) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.647462,0.0173503) , 
1, 1.14281, 1, 0, 0.623981,0.000263437) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0338582,-0.0390581) , 
2, 0.00952224, 1, 0, 0.5,3.23952e-06)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.741554,0.018025) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0692022,-0.0227011) , 
4, 4.01045, 1, 0, 0.479519,0.000361649) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.262291,-0.0284693) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.891348,0.0122415) , 
10, 0.52381, 1, 0, 0.547042,-0.000832694) , 
1, 1.37137, 1, 0, 0.5,-6.20454e-07)    );
  // itree = 125
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.921276,0.0135743) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.954575,-0.061571) , 
6, 2.05926, 1, 0, 0.94006,-0.000822636) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564876,-0.0202861) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.126013,0.04006) , 
2, 0.00238057, 1, 0, 0.302042,0.000371457) , 
12, 0.142804, 1, 0, 0.5,9.65735e-07)    );
  // itree = 126
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.807059,0.0369867) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.663448,-0.0315898) , 
2, 0.00102023, 1, 0, 0.763158,0.000741935) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581099,-0.0370232) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0318308,0.00427438) , 
12, 0.666384, 1, 0, 0.158334,-0.000946398) , 
2, 0.00238056, 1, 0, 0.5,7.34411e-06)    );
  // itree = 127
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.893426,-0.034595) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.387555,0.0337036) , 
15, 1.88412, 1, 0, 0.771239,-0.00039689) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.024636,0.070626) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.105789,-0.00746806) , 
10, 0.333333, 1, 0, 0.0634012,0.000664924) , 
13, 0.333327, 1, 0, 0.5,9.99047e-06)    );
  // itree = 128
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.966993,-0.0266378) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.832552,0.0550494) , 
11, 10.9524, 1, 0, 0.913953,0.000841261) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.411268,-0.0121998) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00354762,0.0526398) , 
12, 0.856825, 1, 0, 0.197898,-0.000612733) , 
13, 0.0952364, 1, 0, 0.5,7.03508e-07)    );
  // itree = 129
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.109964,-0.0270194) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.632228,-0.00184593) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.687393,0.0261248) , 
1, 1.48565, 1, 0, 0.647216,0.000443883) , 
10, 0.333333, 1, 0, 0.5,9.06185e-06)    );
  // itree = 130
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.769856,0.0122653) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0136883,-0.0599907) , 
12, 0.809224, 1, 0, 0.484444,0.000237006) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.573085,-0.0157168) , 
1, 1.71422, 1, 0, 0.5,6.43216e-07)    );
  // itree = 131
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.902129,0.00538876) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.16733,-0.0319941) , 
12, 0.428413, 1, 0, 0.70176,-0.000338571) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0708741,-0.00211259) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0779702,0.0440936) , 
6, 2.0286, 1, 0, 0.0743182,0.000698442) , 
2, 0.00476112, 1, 0, 0.5,-5.10966e-06)    );
  // itree = 132
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.757428,-0.0227558) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.981661,0.0139193) , 
10, 0.52381, 1, 0, 0.917362,-0.000612375) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.283571,-0.0262597) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0866567,0.0427031) , 
4, 3.81669, 1, 0, 0.143532,0.000519073) , 
12, 0.238007, 1, 0, 0.5,-2.13312e-06)    );
  // itree = 133
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.827628,0.030243) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.449775,-0.0473148) , 
4, 1.91246, 1, 0, 0.756181,0.000650041) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.270194,-0.0362401) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00857286,0.0339132) , 
13, 0.333327, 1, 0, 0.101438,-0.0010142) , 
4, 4.01045, 1, 0, 0.5,-1.12522e-06)    );
  // itree = 134
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.972437,0.00383269) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.817594,-0.0282793) , 
11, 11.9048, 1, 0, 0.917362,-0.000906483) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.148741,0.0476272) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.133545,-0.02213) , 
7, 0.112164, 1, 0, 0.143532,0.000784725) , 
12, 0.238007, 1, 0, 0.5,5.66309e-06)    );
  // itree = 135
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564388,0.016294) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0268211,0.0104426) , 
12, 0.523615, 1, 0, 0.166916,0.000892104) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.722152,-0.0321598) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.981122,-0.00199589) , 
5, 0.770668, 1, 0, 0.885683,-0.00103137) , 
19, 0.666667, 1, 0, 0.5,7.46895e-07)    );
  // itree = 136
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626681,0.0237963) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.10041,-0.00472421) , 
13, 0.190473, 1, 0, 0.240341,0.000464697) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.945393,-0.0502895) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.995435,0.0871885) , 
8, 0.884228, 1, 0, 0.966603,-0.000822951) , 
5, 0.730547, 1, 0, 0.5,4.32622e-06)    );
  // itree = 137
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.775653,0.00332371) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.613775,-0.0325034) , 
3, 0.0024942, 1, 0, 0.735461,-0.000349299) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.672393,0.0403149) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.050446,-0.0323276) , 
12, 0.618818, 1, 0, 0.216646,0.000462043) , 
3, 0.00476169, 1, 0, 0.5,1.89231e-05)    );
  // itree = 138
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.923146,0.00299523) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.563284,-0.0315648) , 
12, 0.217591, 1, 0, 0.854618,-0.000655342) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.104638,0.0296205) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00703057,-0.0166159) , 
17, 4.92323, 1, 0, 0.058959,0.000820097) , 
12, 0.571217, 1, 0, 0.5,2.24794e-06)    );
  // itree = 139
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.91735,0.0179702) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.201135,-0.023909) , 
12, 0.333143, 1, 0, 0.756181,0.000396459) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.178625,-0.0302714) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0208039,0.053017) , 
11, 18, 1, 0, 0.101438,-0.000619934) , 
4, 4.01045, 1, 0, 0.5,-1.22507e-06)    );
  // itree = 140
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.739001,-0.0272132) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.985986,-0.000719288) , 
19, 0.714286, 1, 0, 0.917362,-0.0011255) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.562628,-0.0195999) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0363486,0.0560907) , 
13, 0.142855, 1, 0, 0.143532,0.000958316) , 
12, 0.238007, 1, 0, 0.5,-1.60091e-06)    );
  // itree = 141
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.928897,0.04932) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.796286,-0.0152007) , 
7, 0.0819107, 1, 0, 0.888627,0.000667631) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0634431,0.00320808) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.405755,-0.0275133) , 
8, 0.619048, 1, 0, 0.14631,-0.000631218) , 
13, 0.142855, 1, 0, 0.5,-1.23583e-05)    );
  // itree = 142
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.070258,-0.0155676) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.588593,0.0164424) , 
5, 0.53475, 1, 0, 0.32261,0.00035505) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.949663,-0.0743476) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.994174,0.0308411) , 
5, 0.835878, 1, 0, 0.975605,-0.00090607) , 
19, 0.809524, 1, 0, 0.5,1.24599e-05)    );
  // itree = 143
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0986307,0.0280253) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0253109,0.00102561) , 
13, 0.666655, 1, 0, 0.0618775,0.000781335) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.305716,-0.0248273) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.934191,0.0231793) , 
5, 0.67561, 1, 0, 0.699124,-0.000337315) , 
5, 0.499807, 1, 0, 0.5,1.22359e-05)    );
  // itree = 144
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649036,0.0129683) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0321634,-0.0147153) , 
12, 0.571217, 1, 0, 0.240341,0.000366839) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.98038,-0.199214) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.955893,0.0174801) , 
7, 0.0428006, 1, 0, 0.966603,-0.000649568) , 
5, 0.730547, 1, 0, 0.5,3.44473e-06)    );
  // itree = 145
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.874864,0.0117155) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.713548,-0.0162193) , 
7, 0.0864584, 1, 0, 0.81845,-0.000404146) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0222423,-0.0239602) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0619438,0.080356) , 
6, 2.45435, 1, 0, 0.037008,0.000691298) , 
12, 0.714021, 1, 0, 0.5,4.22652e-05)    );
  // itree = 146
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.656069,0.0111406) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0377008,-0.0303306) , 
13, 0.476182, 1, 0, 0.457669,0.000185783) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.85225,-0.0481066) , 
6, 5.11852, 1, 0, 0.5,-5.62983e-06)    );
  // itree = 147
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543479,-0.016241) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.976778,0.0256622) , 
19, 0.809524, 1, 0, 0.717202,-0.000654452) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.105969,0.0342672) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.000655262,0.217097) , 
12, 0.904427, 1, 0, 0.0485243,0.00135971) , 
13, 0.428564, 1, 0, 0.5,-2.05791e-07)    );
  // itree = 148
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.974826,-0.0262205) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.430075,0.0152143) , 
13, 0.0952269, 1, 0, 0.756181,0.000368864) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.177919,0.00395087) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00847568,-0.134974) , 
17, 4.92323, 1, 0, 0.101438,-0.000596396) , 
4, 4.01045, 1, 0, 0.5,-8.81313e-06)    );
  // itree = 149
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.99114,-0.0224102) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.681126,0.0245318) , 
12, 0.19039, 1, 0, 0.913953,0.000443767) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.182361,-0.0316772) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208503,0.00507741) , 
7, 0.0864584, 1, 0, 0.197898,-0.000352556) , 
13, 0.0952364, 1, 0, 0.5,-1.65891e-05)    );
   return;
};
 
// Clean up
inline void ReadMinNodeSize 10::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadMinNodeSize 10::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
