// Class: ReadNCuts 5
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::NCuts 5
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.14/07       [396807]
Creator        : mchristos
Date           : Tue Nov 20 23:02:07 2018
Host           : Linux cmsbuild02.cern.ch 2.6.32-754.3.5.el6.x86_64 #1 SMP Wed Aug 15 08:57:36 CEST 2018 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /cms/mchristos/ANN/FireMVA/2016
Training events: 74267
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "150" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "1.0%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "5" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "5" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 29
MuonPt                        MuonPt                        MuonPt                        MuonPt                                                          'F'    [10.0002336502,273.373016357]
abs(MuonEta)                  abs_MuonEta_                  abs(MuonEta)                  abs(MuonEta)                                                    'F'    [1.46795650835e-06,2.4928457737]
MuonDXY                       MuonDXY                       MuonDXY                       MuonDXY                                                         'F'    [1.25834446862e-07,0.0499910190701]
MuonDZ                        MuonDZ                        MuonDZ                        MuonDZ                                                          'F'    [7.31526483833e-08,0.0999844223261]
MuonSIP3D                     MuonSIP3D                     MuonSIP3D                     MuonSIP3D                                                       'F'    [0.00253649544902,54.8985595703]
MuonPtRatio                   MuonPtRatio                   MuonPtRatio                   MuonPtRatio                                                     'F'    [-1,2.23558855057]
MuonPtRel                     MuonPtRel                     MuonPtRel                     MuonPtRel                                                       'F'    [-1,52.0110664368]
MuonJetLRM                    MuonJetLRM                    MuonJetLRM                    MuonJetLRM                                                      'F'    [-1,0.300980508327]
MuonJetFD                     MuonJetFD                     MuonJetFD                     MuonJetFD                                                       'F'    [-1,1]
MuonJetInOutRatio             MuonJetInOutRatio             MuonJetInOutRatio             MuonJetInOutRatio                                               'F'    [-9999,1]
MuonJetZest                   MuonJetZest                   MuonJetZest                   MuonJetZest                                                     'F'    [-1,1]
MuonJetNoOfConst              MuonJetNoOfConst              MuonJetNoOfConst              MuonJetNoOfConst                                                'F'    [0,56]
MuonJetCSV                    MuonJetCSV                    MuonJetCSV                    MuonJetCSV                                                      'F'    [0,0.999598562717]
MuonRelPFIsoPUCorr            MuonRelPFIsoPUCorr            MuonRelPFIsoPUCorr            MuonRelPFIsoPUCorr                                              'F'    [0,0.999988734722]
MuonRelTrkIso                 MuonRelTrkIso                 MuonRelTrkIso                 MuonRelTrkIso                                                   'F'    [0,148.893722534]
MuonPFChargedHadronIso        MuonPFChargedHadronIso        MuonPFChargedHadronIso        MuonPFChargedHadronIso                                          'F'    [0,137.792205811]
MuonPFNeutralHadronIso        MuonPFNeutralHadronIso        MuonPFNeutralHadronIso        MuonPFNeutralHadronIso                                          'F'    [0,59.2765274048]
MuonPFPhotonIso               MuonPFPhotonIso               MuonPFPhotonIso               MuonPFPhotonIso                                                 'F'    [0,136.399520874]
MuonJetMuonEnergyFraction     MuonJetMuonEnergyFraction     MuonJetMuonEnergyFraction     MuonJetMuonEnergyFraction                                       'F'    [0,1.00000023842]
MuonJetMuonEnergyFraction     MuonJetMuonEnergyFraction     MuonJetMuonEnergyFraction     MuonJetMuonEnergyFraction                                       'F'    [0,1.00000023842]
MuonIsPF                      MuonIsPF                      MuonIsPF                      MuonIsPF                                                        'F'    [1,1]
MuonIsTracker                 MuonIsTracker                 MuonIsTracker                 MuonIsTracker                                                   'F'    [0,1]
MuonTrkValidFractionOfHits    MuonTrkValidFractionOfHits    MuonTrkValidFractionOfHits    MuonTrkValidFractionOfHits                                      'F'    [0,1]
MuonIsGlobal                  MuonIsGlobal                  MuonIsGlobal                  MuonIsGlobal                                                    'F'    [0,1]
MuonGlobalChi2                MuonGlobalChi2                MuonGlobalChi2                MuonGlobalChi2                                                  'F'    [-9999,5167.52246094]
MuonChi2LocalPosition         MuonChi2LocalPosition         MuonChi2LocalPosition         MuonChi2LocalPosition                                           'F'    [-1,37339.6367188]
MuonTrkKink                   MuonTrkKink                   MuonTrkKink                   MuonTrkKink                                                     'F'    [0,3863.02807617]
MuonSegmentCompatibility      MuonSegmentCompatibility      MuonSegmentCompatibility      MuonSegmentCompatibility                                        'F'    [0,1]
MuonPt                        MuonPt                        MuonPt                        MuonPt                                                          'F'    [10.0002336502,273.373016357]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new NCuts 5Node
   
#ifndef NCuts 5Node__def
#define NCuts 5Node__def
   
class NCuts 5Node {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   NCuts 5Node ( NCuts 5Node* left,NCuts 5Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~NCuts 5Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   NCuts 5Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   NCuts 5Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   NCuts 5Node*   fLeft;     // pointer to the left daughter node
   NCuts 5Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   NCuts 5Node::~NCuts 5Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool NCuts 5Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool NCuts 5Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadNCuts 5 : public IClassifierReader {

 public:

   // constructor
   ReadNCuts 5( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadNCuts 5" ),
        fNvars( 29 ),
        fIsNormalised( false )
   {
      // the training input variables
      const char* inputVars[] = { "MuonPt", "abs(MuonEta)", "MuonDXY", "MuonDZ", "MuonSIP3D", "MuonPtRatio", "MuonPtRel", "MuonJetLRM", "MuonJetFD", "MuonJetInOutRatio", "MuonJetZest", "MuonJetNoOfConst", "MuonJetCSV", "MuonRelPFIsoPUCorr", "MuonRelTrkIso", "MuonPFChargedHadronIso", "MuonPFNeutralHadronIso", "MuonPFPhotonIso", "MuonJetMuonEnergyFraction", "MuonJetMuonEnergyFraction", "MuonIsPF", "MuonIsTracker", "MuonTrkValidFractionOfHits", "MuonIsGlobal", "MuonGlobalChi2", "MuonChi2LocalPosition", "MuonTrkKink", "MuonSegmentCompatibility", "MuonPt" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;
      fVmin[16] = 0;
      fVmax[16] = 0;
      fVmin[17] = 0;
      fVmax[17] = 0;
      fVmin[18] = 0;
      fVmax[18] = 0;
      fVmin[19] = 0;
      fVmax[19] = 0;
      fVmin[20] = 0;
      fVmax[20] = 0;
      fVmin[21] = 0;
      fVmax[21] = 0;
      fVmin[22] = 0;
      fVmax[22] = 0;
      fVmin[23] = 0;
      fVmax[23] = 0;
      fVmin[24] = 0;
      fVmax[24] = 0;
      fVmin[25] = 0;
      fVmax[25] = 0;
      fVmin[26] = 0;
      fVmax[26] = 0;
      fVmin[27] = 0;
      fVmax[27] = 0;
      fVmin[28] = 0;
      fVmax[28] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';
      fType[19] = 'F';
      fType[20] = 'F';
      fType[21] = 'F';
      fType[22] = 'F';
      fType[23] = 'F';
      fType[24] = 'F';
      fType[25] = 'F';
      fType[26] = 'F';
      fType[27] = 'F';
      fType[28] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadNCuts 5() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[29];
   double fVmax[29];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[29];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<NCuts 5Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadNCuts 5::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      NCuts 5Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(NCuts 5Node*)current->GetRight();
         else current=(NCuts 5Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadNCuts 5::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.967957,0.935914) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.239815,-0.520369) , 
12, 0.666314, 1, 0, 0.918168,0.418168) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.414529,-0.170942) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0159889,-0.968022) , 
12, 0.3332, 1, 0, 0.106706,-0.393294) , 
13, 0.166665, 1, 0, 0.5,6.35443e-16)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0456436,-0.548355) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.235594,-0.124401) , 
10, 0.506257, 1, 0, 0.0668059,-0.13321) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9195,0.507204) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0463592,-0.439813) , 
12, 0.832892, 1, 0, 0.864571,0.114162) , 
5, 0.617794, 1, 0, 0.5,0.00111531)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.945887,0.396734) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.466261,-0.12409) , 
11, 15, 1, 0, 0.90839,0.0485848) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.106279,-0.370654) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.881891,0.403045) , 
10, 0.690542, 1, 0, 0.176916,-0.0423192) , 
12, 0.1666, 1, 0, 0.5,-0.00216789)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.888765,0.274573) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0790935,-0.164403) , 
13, 0.333324, 1, 0, 0.631895,0.0122789) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.319593,-1.05011) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0291777,-0.432434) , 
12, 0.3332, 1, 0, 0.0459882,-0.0411418) , 
2, 0.00833194, 1, 0, 0.5,0.000253209)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.927212,0.156524) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298858,-0.483869) , 
11, 8.16667, 1, 0, 0.642656,-0.0118732) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.264671,-0.0565922) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.275274,0.4967) , 
7, 0.120289, 1, 0, 0.268783,0.0176678) , 
7, 0.0841504, 1, 0, 0.5,-0.000601456)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.838125,0.100505) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.219568,-0.643674) , 
4, 7.3196, 1, 0, 0.820828,0.00665) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0274885,-0.289002) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.757391,0.232634) , 
5, 0.785857, 1, 0, 0.0519404,-0.0130667) , 
12, 0.499799, 1, 0, 0.5,-0.00157705)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.305154,-0.252249) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00980222,-0.299035) , 
12, 0.3332, 1, 0, 0.0670403,-0.0152814) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.639244,0.0133448) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.371252,0.275775) , 
7, 0.148696, 1, 0, 0.62402,0.00315036) , 
10, 0.333333, 1, 0, 0.5,-0.000953758)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.304927,0.397832) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0654738,-0.17759) , 
9, 0.333333, 1, 0, 0.0781508,-0.00763014) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.887403,0.000484678) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.806154,0.255918) , 
7, 0.0804202, 1, 0, 0.872154,0.00582685) , 
8, 0.666667, 1, 0, 0.5,-0.000480517)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.278667,-0.150684) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.984839,0.225633) , 
18, 0.833333, 1, 0, 0.477314,-0.00567134) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601648,0.0915185) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.040314,-0.189098) , 
11, 18.6667, 1, 0, 0.518538,0.00425936) , 
1, 0.83095, 1, 0, 0.5,-0.000206431)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.256778,0.167727) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00757648,-0.13703) , 
12, 0.499799, 1, 0, 0.0668059,0.00542705) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.580038,-0.22618) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.969475,0.110271) , 
8, 0.783693, 1, 0, 0.864571,-0.00440715) , 
5, 0.617794, 1, 0, 0.5,8.69827e-05)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.427434,-0.0599886) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.654977,0.123342) , 
6, 3.41643, 1, 0, 0.482071,-0.000726105) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.872757,0.484458) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.992325,0.167149) , 
10, 0.878556, 1, 0, 0.938521,0.0191678) , 
6, 7.83518, 1, 0, 0.5,5.53107e-05)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.675827,0.0740265) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0170628,-0.311678) , 
15, 8.63303, 1, 0, 0.500401,0.00101478) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.102478,-0.705325) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.986868,0.00848517) , 
18, 0.873266, 1, 0, 0.492575,-0.0161894) , 
0, 53.8957, 1, 0, 0.5,0.000133874)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.954719,0.124818) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.739053,-0.70972) , 
13, 0.0833293, 1, 0, 0.918168,-0.00541386) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0913827,0.0301529) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34312,0.310157) , 
6, 4.7386, 1, 0, 0.106706,0.00433763) , 
13, 0.166665, 1, 0, 0.5,-0.000388654)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.913568,-0.0152595) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.246014,0.103276) , 
12, 0.166573, 1, 0, 0.599351,0.00289991) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.212571,-0.28443) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00378003,-0.270057) , 
13, 0.16666, 1, 0, 0.0254129,-0.00606997) , 
4, 9.15187, 1, 0, 0.5,0.00134718)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.925829,-0.0849229) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475358,0.0742527) , 
11, 8.5, 1, 0, 0.717906,0.00153392) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0216744,-0.156189) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.191344,0.190025) , 
8, 0.626236, 1, 0, 0.032472,-0.00372215) , 
13, 0.499994, 1, 0, 0.5,-0.000137036)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.729302,0.0368906) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.292148,-0.233292) , 
2, 0.00277736, 1, 0, 0.631895,-0.00140002) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.18548,0.306849) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00340105,-0.1702) , 
12, 0.832999, 1, 0, 0.0459882,0.00453461) , 
2, 0.00833194, 1, 0, 0.5,-6.40609e-05)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.870974,-0.0141374) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.39421,-0.337698) , 
12, 0.277636, 1, 0, 0.855984,-0.00258027) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0474864,0.186134) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.769231,-0.421138) , 
10, 0.690542, 1, 0, 0.0829789,0.0027999) , 
12, 0.3332, 1, 0, 0.5,-0.0001026)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.962499,0.0172566) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379356,0.113763) , 
13, 0.166636, 1, 0, 0.866474,0.00347382) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.563862,0.132314) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0937223,-0.165836) , 
9, 0.5, 1, 0, 0.21272,-0.00293987) , 
11, 9.33333, 1, 0, 0.5,-0.000121495)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471693,0.293016) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.782098,-0.0254982) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.026801,0.0875777) , 
12, 0.666399, 1, 0, 0.500329,-0.000309327) , 
24, -7471.25, 1, 0, 0.5,-9.11704e-05)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.15406,0.097233) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0016811,-0.385558) , 
12, 0.832999, 1, 0, 0.0668059,0.00204601) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.95208,0.0315336) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.40761,-0.104256) , 
13, 0.166566, 1, 0, 0.864571,-0.00177439) , 
5, 0.617794, 1, 0, 0.5,-2.85079e-05)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.85782,0.0633183) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0546183,-0.0757422) , 
12, 0.333146, 1, 0, 0.480542,0.00140007) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.776323,-0.124525) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0410655,0.272018) , 
12, 0.666399, 1, 0, 0.534787,-0.00337576) , 
1, 1.24642, 1, 0, 0.5,-0.000313035)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491187,-0.165236) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501035,0.0413077) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.49957,-0.023545) , 
27, 0.916667, 1, 0, 0.500187,0.000182967) , 
27, 0.5, 1, 0, 0.5,-5.65112e-05)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.623207,-0.00827943) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0508444,-0.272459) , 
11, 15.3333, 1, 0, 0.47377,-0.0030166) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.130625,-0.0288586) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.945834,0.0902155) , 
5, 0.693791, 1, 0, 0.507727,0.000899243) , 
1, 0.415476, 1, 0, 0.5,8.18825e-06)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0760026,0.216897) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.756436,-0.0739008) , 
10, 0.333333, 1, 0, 0.642656,-0.00167761) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266045,0.0184315) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.355109,0.328408) , 
7, 0.192566, 1, 0, 0.268783,0.0027617) , 
7, 0.0841504, 1, 0, 0.5,1.62634e-05)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519224,-0.00231856) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00609521,-0.514853) , 
4, 18.3012, 1, 0, 0.490049,-0.000460925) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.906044,-0.0421817) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.165278,0.204533) , 
13, 0.166636, 1, 0, 0.634044,0.00632786) , 
1, 2.07737, 1, 0, 0.5,8.20641e-06)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.487161,-0.00967409) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.93974,0.19548) , 
6, 7.83518, 1, 0, 0.505149,-0.000272298) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.108459,0.288906) , 
3, 0.0833204, 1, 0, 0.5,-8.57735e-05)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546653,-0.0131272) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0492999,0.220219) , 
17, 11.3633, 1, 0, 0.506718,-0.000131028) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0480532,0.349365) , 
17, 22.7333, 1, 0, 0.5,1.08317e-05)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.304927,-0.205304) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0654738,0.00265345) , 
9, 0.333333, 1, 0, 0.0781508,-0.00143239) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.443325,-0.0780127) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.944986,0.0752858) , 
5, 0.698131, 1, 0, 0.872154,0.00116436) , 
8, 0.666667, 1, 0, 0.5,-5.27486e-05)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.915015,-0.00375587) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.726687,-0.392233) , 
3, 0.0165035, 1, 0, 0.90839,-0.00170217) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.444277,-0.242551) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.140985,0.0637941) , 
7, 0.0501752, 1, 0, 0.176916,0.00145347) , 
12, 0.1666, 1, 0, 0.5,5.96577e-05)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.962499,0.0223181) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379356,0.0642304) , 
13, 0.166636, 1, 0, 0.866474,0.00235789) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.847027,0.211421) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.169625,-0.0541747) , 
9, 0.166667, 1, 0, 0.21272,-0.0016773) , 
11, 9.33333, 1, 0, 0.5,9.58846e-05)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.838125,0.00872915) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.219568,0.185642) , 
4, 7.3196, 1, 0, 0.820828,0.0011876) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0274885,-0.0328448) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.757391,-0.146518) , 
5, 0.785857, 1, 0, 0.0519404,-0.00156631) , 
12, 0.499799, 1, 0, 0.5,3.84946e-05)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976975,0.128222) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436894,-0.00581041) , 
11, 4.5, 1, 0, 0.508771,0.000164709) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0132549,-0.348758) , 
11, 28, 1, 0, 0.5,7.71886e-06)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0801094,0.0030932) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.587344,0.182211) , 
10, 0.604155, 1, 0, 0.0967083,0.00100294) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.308899,-0.175584) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.918385,0.00935188) , 
8, 0.705926, 1, 0, 0.877814,-0.000921973) , 
18, 0.666667, 1, 0, 0.5,9.08807e-06)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.125848,0.126628) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00914793,-0.205934) , 
9, 0.666667, 1, 0, 0.0670403,0.00207443) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.706722,-0.0500407) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358754,0.0497697) , 
7, 0.0991312, 1, 0, 0.62402,-0.00057639) , 
10, 0.333333, 1, 0, 0.5,1.3856e-05)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.927212,-0.0380154) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298858,0.101046) , 
11, 8.16667, 1, 0, 0.642656,0.00132774) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.264671,0.0211386) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.275274,-0.0806619) , 
7, 0.120289, 1, 0, 0.268783,-0.00225845) , 
7, 0.0841504, 1, 0, 0.5,-4.06159e-05)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.767127,-0.0504197) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.993287,0.119232) , 
18, 0.833334, 1, 0, 0.90839,-0.00122472) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.106279,0.038212) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.881891,-0.121366) , 
10, 0.690542, 1, 0, 0.176916,0.000985792) , 
12, 0.1666, 1, 0, 0.5,9.43098e-06)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.857551,0.0200055) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.072679,-0.0165954) , 
13, 0.277768, 1, 0, 0.554804,0.00035259) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.125926,-0.104128) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0033068,-0.0870566) , 
12, 0.333146, 1, 0, 0.019756,-0.00235904) , 
13, 0.833324, 1, 0, 0.5,7.48414e-05)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.857551,0.000141794) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.222954,-0.162886) , 
13, 0.277774, 1, 0, 0.823318,-0.00114352) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.158854,0.0705809) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00307232,-0.190474) , 
12, 0.666399, 1, 0, 0.0483622,0.00157784) , 
13, 0.33333, 1, 0, 0.5,-8.14544e-06)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.967957,-0.110239) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302319,0.0369465) , 
13, 0.16666, 1, 0, 0.781884,-0.00122617) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.239815,0.254414) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00594941,-0.135802) , 
13, 0.166665, 1, 0, 0.0267131,0.00179671) , 
12, 0.666399, 1, 0, 0.5,-9.78094e-05)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.907303,0.0128606) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.161916,-0.0205015) , 
12, 0.1666, 1, 0, 0.490049,-0.000263385) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.922351,-0.0685551) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.38696,0.102646) , 
12, 0.166585, 1, 0, 0.634044,0.00423402) , 
1, 2.07737, 1, 0, 0.5,4.74038e-05)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.840573,0.0210698) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0818689,-0.281274) , 
15, 7.95095, 1, 0, 0.823318,0.000900078) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.237549,-0.0731379) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00768666,0.164343) , 
12, 0.3332, 1, 0, 0.0483622,-0.0012442) , 
13, 0.33333, 1, 0, 0.5,5.4669e-06)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.865642,0.0127999) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379975,0.158004) , 
16, 6.71034, 1, 0, 0.855984,0.0013934) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509646,-0.151444) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0159889,0.0653246) , 
13, 0.166665, 1, 0, 0.0829789,-0.00185857) , 
12, 0.3332, 1, 0, 0.5,-0.000104197)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.923624,0.0094051) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.820961,0.293438) , 
16, 3.06616, 1, 0, 0.918168,0.00173028) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.414529,-0.032766) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0159889,-0.00243197) , 
12, 0.3332, 1, 0, 0.106706,-0.00161249) , 
13, 0.166665, 1, 0, 0.5,7.66068e-06)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478686,0.0370145) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0448321,-0.0545952) , 
12, 0.1666, 1, 0, 0.0967083,-0.000917436) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.913192,-0.0071804) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.559224,0.0968453) , 
3, 0.0166611, 1, 0, 0.877814,0.000987153) , 
18, 0.666667, 1, 0, 0.5,6.59204e-05)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.704342,0.0401546) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.295925,-0.0510589) , 
3, 0.00555447, 1, 0, 0.551622,0.000416132) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499552,-0.205618) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0648564,-0.0298648) , 
12, 0.3332, 1, 0, 0.105037,-0.00323804) , 
3, 0.0333282, 1, 0, 0.5,-6.26172e-06)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.945887,-0.0518721) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.466261,0.0639959) , 
11, 15, 1, 0, 0.90839,-0.00144085) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498249,0.0580005) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0649523,-0.0208301) , 
11, 10.1667, 1, 0, 0.176916,0.00117195) , 
12, 0.1666, 1, 0, 0.5,1.79035e-05)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.91665,0.0280437) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.357346,-0.048613) , 
11, 15, 1, 0, 0.855984,0.000757886) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509646,-0.0611687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0159889,0.0217982) , 
13, 0.166665, 1, 0, 0.0829789,-0.000833514) , 
12, 0.3332, 1, 0, 0.5,2.50153e-05)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.7404,0.0312694) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.482038,-0.0463248) , 
3, 0.00277738, 1, 0, 0.608217,-0.000550828) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.59722,0.0678428) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0203323,-0.000410259) , 
13, 0.166665, 1, 0, 0.139675,0.00187088) , 
3, 0.0166641, 1, 0, 0.5,8.50141e-06)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0540845,0.103938) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.589979,-0.0511797) , 
10, 0.333333, 1, 0, 0.47377,-0.00155528) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501913,0.208505) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507812,0.00392144) , 
27, 0.5, 1, 0, 0.507727,0.000476884) , 
1, 0.415476, 1, 0, 0.5,1.44623e-05)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626101,-0.116484) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0506983,0.265278) , 
13, 0.666628, 1, 0, 0.494838,-0.00359965) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.718223,0.0169153) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0308799,-0.0483575) , 
13, 0.499994, 1, 0, 0.500395,0.000277362) , 
27, 0.666667, 1, 0, 0.5,2.09027e-06)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.645958,-0.00462923) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.206942,0.0460263) , 
3, 0.0111089, 1, 0, 0.551622,0.000289377) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476723,-0.0957311) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0163414,0.0174109) , 
13, 0.166657, 1, 0, 0.105037,-0.00232797) , 
3, 0.0333282, 1, 0, 0.5,-1.31676e-05)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0701332,0.0142376) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.867568,-0.0137191) , 
5, 0.617794, 1, 0, 0.512871,-0.00012425) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.297642,0.141352) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00565744,-0.229317) , 
13, 0.333204, 1, 0, 0.106485,0.00392653) , 
3, 0.0666563, 1, 0, 0.5,4.04757e-06)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.259098,-0.0175606) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.359826,0.0842731) , 
6, 4.50355, 1, 0, 0.265243,-0.000552609) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.983319,0.0114207) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.451522,0.114137) , 
12, 0.666293, 1, 0, 0.966602,0.00108581) , 
10, 0.666667, 1, 0, 0.5,-4.20353e-06)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.869978,0.0195546) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.595672,-0.0810926) , 
3, 0.0166504, 1, 0, 0.855984,0.00078086) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.174146,0.0207714) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0023994,-0.354964) , 
12, 0.888535, 1, 0, 0.0829789,-0.000909086) , 
12, 0.3332, 1, 0, 0.5,2.60686e-06)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.837886,0.00581117) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.191519,-0.057197) , 
12, 0.416499, 1, 0, 0.707168,-0.000646042) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0384598,0.611182) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00409452,-0.0470481) , 
12, 0.860769, 1, 0, 0.00684067,0.00100125) , 
12, 0.832999, 1, 0, 0.5,-0.000158745)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.98463,0.00728212) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.508843,-0.0351741) , 
13, 0.16663, 1, 0, 0.90839,-0.00108596) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.193336,-0.0295456) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.14895,0.0614229) , 
7, 0.100336, 1, 0, 0.176916,0.000605494) , 
12, 0.1666, 1, 0, 0.5,-0.000141603)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.736712,0.0406842) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0212817,-0.281978) , 
11, 16.3333, 1, 0, 0.642656,0.00107039) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.111205,0.00986553) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.663456,-0.0694613) , 
10, 0.515479, 1, 0, 0.268783,-0.00175419) , 
7, 0.0841504, 1, 0, 0.5,-7.36366e-06)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.566833,0.000655554) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0555528,0.186211) , 
17, 17.3461, 1, 0, 0.554804,0.000183842) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0969042,-0.0974038) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00211083,0.0879346) , 
12, 0.499719, 1, 0, 0.019756,-0.00169166) , 
13, 0.833324, 1, 0, 0.5,-8.2627e-06)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.651145,0.00517166) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.149815,-0.333299) , 
2, 0.00694322, 1, 0, 0.631895,-0.000310089) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0384591,0.116775) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0855424,-0.137002) , 
1, 1.66193, 1, 0, 0.0459882,0.00099104) , 
2, 0.00833194, 1, 0, 0.5,-1.71889e-05)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.597567,-0.0133446) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.778038,0.0589013) , 
1, 2.06344, 1, 0, 0.608217,-0.000442422) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0189665,-0.0151669) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.559285,0.0561337) , 
18, 0.666667, 1, 0, 0.139675,0.00140174) , 
3, 0.0166641, 1, 0, 0.5,-1.64846e-05)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.466479,-0.265403) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.477648,0.0231255) , 
27, 0.5, 1, 0, 0.477314,0.000567298) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.530115,-0.00352661) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.02333,-0.385582) , 
16, 9.87942, 1, 0, 0.518538,-0.000450974) , 
1, 0.83095, 1, 0, 0.5,6.93837e-06)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491187,0.117509) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511019,-0.00660847) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0450878,0.247727) , 
16, 9.87942, 1, 0, 0.500187,-0.000203871) , 
27, 0.5, 1, 0, 0.5,-9.68737e-06)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.53396,-0.000266515) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.199027,0.0949864) , 
3, 0.0666563, 1, 0, 0.528118,0.000102626) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.027178,-0.282425) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.000681044,-0.0106794) , 
13, 0.333319, 1, 0, 0.00599038,-0.00197555) , 
4, 18.3012, 1, 0, 0.5,-9.29013e-06)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.537115,-0.00124479) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.115922,0.17742) , 
3, 0.0416602, 1, 0, 0.526667,0.000124047) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.140402,-0.161927) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0394654,0.150702) , 
7, 0.0916859, 1, 0, 0.0941758,-0.00201967) , 
3, 0.0499922, 1, 0, 0.5,-8.13256e-06)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.74328,0.00853857) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.14044,-0.0598156) , 
4, 7.85648, 1, 0, 0.707168,0.000306259) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.023822,-0.17775) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00394546,0.0481367) , 
11, 10.1667, 1, 0, 0.00684067,-0.000746479) , 
12, 0.832999, 1, 0, 0.5,-5.15789e-06)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.542386,-0.00577525) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.140921,0.091302) , 
3, 0.0666487, 1, 0, 0.532484,-0.000206398) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.00170309,-0.115282) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.102176,0.245987) , 
8, 0.624928, 1, 0, 0.0203442,0.00260659) , 
2, 0.0249956, 1, 0, 0.5,-2.79758e-05)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.494915,0.00431394) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0516604,-0.266309) , 
3, 0.0833109, 1, 0, 0.490049,0.000129618) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.196664,-0.0970021) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.954637,0.103364) , 
8, 0.772042, 1, 0, 0.634044,-0.00188278) , 
1, 2.07737, 1, 0, 0.5,-9.44602e-06)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.945887,-0.033187) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.466261,0.0770747) , 
11, 15, 1, 0, 0.90839,-0.000490773) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0272017,-0.0529909) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475742,0.0367911) , 
8, 0.626236, 1, 0, 0.176916,0.00040256) , 
12, 0.1666, 1, 0, 0.5,7.98448e-06)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0456436,0.0633016) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.235594,-0.0962255) , 
10, 0.506257, 1, 0, 0.0668059,0.000877551) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528286,-0.116956) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.886859,0.00257334) , 
10, 0.393077, 1, 0, 0.864571,-0.000740892) , 
5, 0.617794, 1, 0, 0.5,-1.27925e-06)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596062,-0.00108527) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.103692,0.237217) , 
17, 14.9611, 1, 0, 0.583059,0.000275416) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.020471,-0.169981) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.218849,0.180578) , 
10, 0.428979, 1, 0, 0.0434415,-0.00160952) , 
11, 18.6667, 1, 0, 0.5,-1.47177e-05)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498981,0.0299917) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.501648,-0.0490099) , 
0, 24.6315, 1, 0, 0.500401,9.64462e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.953055,0.10788) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.144773,-0.24061) , 
11, 10.1667, 1, 0, 0.492575,-0.00285743) , 
0, 53.8957, 1, 0, 0.5,-5.48021e-05)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0292451,-0.127566) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.154719,0.0282476) , 
8, 0.539573, 1, 0, 0.0967083,-0.000658101) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.907223,-0.0245365) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.785871,0.0559421) , 
7, 0.0711622, 1, 0, 0.877814,0.000639434) , 
18, 0.666667, 1, 0, 0.5,1.18284e-05)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0854794,0.167963) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0223645,-0.060165) , 
9, 0.666667, 1, 0, 0.0429263,0.00191743) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62935,-0.0188785) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.540145,0.0893472) , 
7, 0.142166, 1, 0, 0.625847,-0.000566059) , 
18, 0.5, 1, 0, 0.5,-2.9897e-05)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0826217,-0.0355075) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.949726,0.0644937) , 
5, 0.693791, 1, 0, 0.642656,0.00106902) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.312297,-0.0395132) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0271938,0.338907) , 
15, 14.3903, 1, 0, 0.268783,-0.00180525) , 
7, 0.0841504, 1, 0, 0.5,-2.76917e-05)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0723286,-0.0166628) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.695706,0.0300506) , 
8, 0.660665, 1, 0, 0.265243,0.000462334) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.990184,0.0276037) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.857072,-0.0910379) , 
12, 0.166573, 1, 0, 0.966602,-0.00100367) , 
10, 0.666667, 1, 0, 0.5,-2.83639e-05)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.337709,0.101774) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0132618,-0.03434) , 
13, 0.33333, 1, 0, 0.0670403,0.00117222) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.346131,-0.0244801) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.981212,0.0807756) , 
5, 0.787962, 1, 0, 0.62402,-0.000305877) , 
10, 0.333333, 1, 0, 0.5,2.32456e-05)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.970826,0.104666) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.847908,-0.104533) , 
13, 0.0277764, 1, 0, 0.918168,-0.00152564) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.302319,0.040604) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00594941,-0.102065) , 
12, 0.666399, 1, 0, 0.106706,0.00150774) , 
13, 0.166665, 1, 0, 0.5,3.75411e-05)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.294787,-0.0473552) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.95493,-0.0128023) , 
5, 0.554742, 1, 0, 0.90839,-0.00115492) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.106279,0.0352958) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.881891,-0.0769423) , 
10, 0.690542, 1, 0, 0.176916,0.00105799) , 
12, 0.1666, 1, 0, 0.5,8.05722e-05)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.837899,-0.00144581) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.363574,-0.14039) , 
12, 0.41646, 1, 0, 0.820828,-0.000759159) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.216771,0.103633) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0175036,-0.0299519) , 
12, 0.749706, 1, 0, 0.0519404,0.00107182) , 
12, 0.499799, 1, 0, 0.5,4.84242e-06)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.809235,0.00123953) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.210883,-0.17999) , 
12, 0.555317, 1, 0, 0.781884,-0.000589867) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.239815,0.112612) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00594941,-0.0382495) , 
13, 0.166665, 1, 0, 0.0267131,0.000967887) , 
12, 0.666399, 1, 0, 0.5,-8.40115e-06)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0288115,-0.0661104) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.104304,0.0445624) , 
8, 0.54042, 1, 0, 0.0668059,0.000590262) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.780219,-0.0232257) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.99321,0.133718) , 
8, 0.891847, 1, 0, 0.864571,-0.000523712) , 
5, 0.617794, 1, 0, 0.5,-1.4637e-05)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.114846,-0.00912462) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.766306,0.0419501) , 
18, 0.69439, 1, 0, 0.276222,0.000707659) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.991775,-0.0596089) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.807091,-0.0966749) , 
12, 0.333137, 1, 0, 0.979812,-0.0014352) , 
18, 0.833334, 1, 0, 0.5,2.61168e-05)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.324935,0.105796) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.019702,0.0225245) , 
12, 0.1666, 1, 0, 0.0429263,0.00176861) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.680861,-0.0404716) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.426482,0.0427415) , 
7, 0.0947777, 1, 0, 0.625847,-0.000446922) , 
18, 0.5, 1, 0, 0.5,3.13909e-05)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.927212,-0.0193281) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298858,0.0660954) , 
11, 8.16667, 1, 0, 0.642656,0.00092461) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626074,-0.0399206) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0362865,0.0521023) , 
12, 0.499799, 1, 0, 0.268783,-0.0014775) , 
7, 0.0841504, 1, 0, 0.5,8.05743e-06)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.246468,-0.0119615) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.697416,0.0646643) , 
6, 5.31729, 1, 0, 0.276222,-0.000428259) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.983915,-0.0317186) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.974412,0.0853859) , 
1, 1.23808, 1, 0, 0.979812,0.000930737) , 
18, 0.833334, 1, 0, 0.5,3.97279e-06)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.191322,-0.0421812) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.920136,0.0271936) , 
5, 0.554742, 1, 0, 0.820828,0.000592733) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.392821,-0.0681401) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0092531,0.0262571) , 
13, 0.166665, 1, 0, 0.0519404,-0.000766255) , 
12, 0.499799, 1, 0, 0.5,2.56775e-05)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.24074,0.0755274) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00721645,-0.013552) , 
12, 0.3332, 1, 0, 0.0429263,0.00159388) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.61753,-0.137644) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.626018,-0.00371245) , 
27, 0.5, 1, 0, 0.625847,-0.00043432) , 
18, 0.5, 1, 0, 0.5,3.55047e-06)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491187,0.090719) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499045,-0.0837717) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500209,-0.000990344) , 
27, 0.583333, 1, 0, 0.500187,-0.000150551) , 
27, 0.5, 1, 0, 0.5,-1.62561e-06)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.887557,0.0012934) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47967,-0.0739327) , 
12, 0.222109, 1, 0, 0.855984,-0.000686087) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0282915,-0.00252093) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.663356,0.0620707) , 
8, 0.750824, 1, 0, 0.0829789,0.000809325) , 
12, 0.3332, 1, 0, 0.5,2.57928e-06)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.749509,-0.000546434) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0718754,-0.10614) , 
2, 0.00832994, 1, 0, 0.642656,-0.000520975) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228238,0.0233844) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.942799,-0.345219) , 
5, 0.80102, 1, 0, 0.268783,0.000858607) , 
7, 0.0841504, 1, 0, 0.5,5.42104e-06)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471693,0.101932) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.26526,-0.0082305) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.966812,0.0365786) , 
10, 0.666667, 1, 0, 0.500329,3.49891e-06) , 
24, -7471.25, 1, 0, 0.5,7.53765e-05)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485045,0.0828579) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.537488,-0.138044) , 
1, 1.23854, 1, 0, 0.494838,0.00186089) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505626,-0.00425064) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.107979,0.144807) , 
3, 0.0833204, 1, 0, 0.500395,-0.000133998) , 
27, 0.666667, 1, 0, 0.5,7.64101e-06)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47803,-0.020824) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507157,0.0186814) , 
1, 1.03865, 1, 0, 0.490049,-0.000148874) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.805124,0.0541632) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0540331,-0.142838) , 
12, 0.666339, 1, 0, 0.634044,0.0020644) , 
1, 2.07737, 1, 0, 0.5,4.07182e-06)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.93278,0.0457399) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.109038,-0.0111816) , 
13, 0.166665, 1, 0, 0.480542,0.000421929) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492866,0.0515188) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.548403,-0.030142) , 
1, 1.45418, 1, 0, 0.534787,-0.000755168) , 
1, 1.24642, 1, 0, 0.5,-2.98852e-07)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.066023,0.0388793) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.609109,-0.0154854) , 
10, 0.333333, 1, 0, 0.482854,-0.000374082) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558537,0.122855) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.575788,-0.000488342) , 
22, 0.166667, 1, 0, 0.572265,0.00164986) , 
1, 1.6619, 1, 0, 0.5,1.40476e-05)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.954719,-0.135223) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.739053,0.11096) , 
13, 0.0833293, 1, 0, 0.918168,-0.00070677) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0913827,0.0226703) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34312,-0.0819146) , 
6, 4.7386, 1, 0, 0.106706,0.00066994) , 
13, 0.166665, 1, 0, 0.5,2.68617e-06)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.412003,-0.0944093) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0336581,-0.0226845) , 
9, 0.333333, 1, 0, 0.0670403,-0.00156208) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.706722,-0.00500009) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358754,0.0347048) , 
7, 0.0991312, 1, 0, 0.62402,0.000656399) , 
10, 0.333333, 1, 0, 0.5,0.00016242)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.765728,0.015454) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440363,-0.032204) , 
2, 0.00138875, 1, 0, 0.631895,-0.000397675) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.2752,0.0901929) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0111077,-0.00949834) , 
12, 0.666399, 1, 0, 0.0459882,0.00137319) , 
2, 0.00833194, 1, 0, 0.5,9.69353e-07)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.900633,0.0412387) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.910754,-0.0432302) , 
1, 0.412717, 1, 0, 0.90839,-0.00113301) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.108195,5.10292e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.904537,0.108439) , 
5, 0.785857, 1, 0, 0.176916,0.000901513) , 
12, 0.1666, 1, 0, 0.5,2.88502e-06)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.939732,0.0141628) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.114573,-0.0576801) , 
13, 0.166665, 1, 0, 0.47377,-0.00174967) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.51883,0.0130029) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.033211,-0.252876) , 
16, 9.87942, 1, 0, 0.507727,0.000567338) , 
1, 0.415476, 1, 0, 0.5,4.01018e-05)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.572827,-0.0767059) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340088,0.165456) , 
16, 1.64561, 1, 0, 0.510854,-0.000125116) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0715075,0.353495) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0225531,-0.0617411) , 
1, 0.807556, 1, 0, 0.0441355,0.00488886) , 
16, 9.87942, 1, 0, 0.5,-8.50706e-06)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.906318,0.0338194) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.181019,-0.0796995) , 
13, 0.499907, 1, 0, 0.866474,0.00113575) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.134565,-0.0298044) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.96142,0.144414) , 
5, 0.785857, 1, 0, 0.21272,-0.000802629) , 
11, 9.33333, 1, 0, 0.5,4.91542e-05)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0568646,0.0185433) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.850533,-0.0233611) , 
5, 0.617794, 1, 0, 0.482854,-0.000355581) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.060388,-0.0496504) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.841181,0.051234) , 
8, 0.64494, 1, 0, 0.572265,0.00169829) , 
1, 1.6619, 1, 0, 0.5,3.82869e-05)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.500453,0.0147073) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500023,-0.182671) , 
0, 39.2627, 1, 0, 0.500401,0.000123056) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.829326,-0.346945) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.21518,0.0248619) , 
7, 0.0333413, 1, 0, 0.492575,-0.00211617) , 
0, 53.8957, 1, 0, 0.5,8.40049e-06)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.633878,-0.0282063) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.178423,0.00716305) , 
11, 9.33333, 1, 0, 0.276222,-0.000391722) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.958184,-0.079783) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.990279,0.172181) , 
18, 0.888898, 1, 0, 0.979812,0.000947596) , 
18, 0.833334, 1, 0, 0.5,3.42511e-05)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.579351,0.0059256) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0270029,-0.0643227) , 
2, 0.0138857, 1, 0, 0.50643,0.000145559) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00457809,-0.54723) , 
2, 0.0416592, 1, 0, 0.5,8.94507e-05)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626121,0.0149885) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.979785,-0.383579) , 
6, 7.83518, 1, 0, 0.642656,0.000400296) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.238336,-0.0182757) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.751818,0.125239) , 
6, 6.16389, 1, 0, 0.268783,-0.000678398) , 
7, 0.0841504, 1, 0, 0.5,-1.12928e-05)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.719805,0.0120387) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.101699,-0.026211) , 
11, 13.5, 1, 0, 0.508771,0.000102937) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0132549,-0.215412) , 
11, 28, 1, 0, 0.5,3.88388e-05)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0801094,0.00709172) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.587344,0.0722537) , 
10, 0.604155, 1, 0, 0.0967083,0.000649836) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62751,-0.0357049) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.976811,0.031815) , 
8, 0.803951, 1, 0, 0.877814,-0.000621473) , 
18, 0.666667, 1, 0, 0.5,-6.55243e-06)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0723286,-0.00427619) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.695706,0.0182575) , 
8, 0.660665, 1, 0, 0.265243,0.00046707) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.983319,-0.0653006) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.451522,0.082487) , 
12, 0.666293, 1, 0, 0.966602,-0.000886802) , 
10, 0.666667, 1, 0, 0.5,1.39063e-05)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488747,0.00685124) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0423034,0.592386) , 
3, 0.0666487, 1, 0, 0.480542,0.000476146) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.776323,0.00331202) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0410655,-0.091549) , 
12, 0.666399, 1, 0, 0.534787,-0.000781413) , 
1, 1.24642, 1, 0, 0.5,2.50563e-05)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596138,-0.00191894) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0449111,0.0405129) , 
11, 18.6667, 1, 0, 0.512871,7.42021e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.242311,0.0534502) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0303453,-0.332514) , 
2, 0.00833565, 1, 0, 0.106485,-0.00280924) , 
3, 0.0666563, 1, 0, 0.5,-1.71234e-05)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.796439,-0.00160806) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.411797,-0.0524652) , 
3, 0.0333138, 1, 0, 0.781884,-0.000331369) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.147353,0.275077) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0208446,-0.0259122) , 
12, 0.721944, 1, 0, 0.0267131,0.000535624) , 
12, 0.666399, 1, 0, 0.5,-7.74443e-06)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.643341,-0.00820399) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0280569,0.16401) , 
2, 0.0166596, 1, 0, 0.608217,-0.000288748) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0494391,-0.0880858) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.229284,0.0605951) , 
1, 1.24642, 1, 0, 0.139675,0.000878113) , 
3, 0.0166641, 1, 0, 0.5,-1.92443e-05)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.466479,-0.128369) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.477648,0.016985) , 
27, 0.5, 1, 0, 0.477314,0.000506272) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.050102,0.209067) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.53081,-0.010227) , 
18, 0.333333, 1, 0, 0.518538,-0.000424301) , 
1, 0.83095, 1, 0, 0.5,-5.8266e-06)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.882598,-0.0651715) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.270563,0.0844926) , 
11, 8.5, 1, 0, 0.494838,0.00205191) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509963,0.0555848) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499964,-0.00574439) , 
27, 0.722235, 1, 0, 0.500395,-0.000159915) , 
27, 0.666667, 1, 0, 0.5,-2.87281e-06)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0842616,-0.00118888) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.309732,-0.0791072) , 
6, 4.7386, 1, 0, 0.0967083,-0.000489333) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.907223,-0.0241448) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.785871,0.0470116) , 
7, 0.0711622, 1, 0, 0.877814,0.000465146) , 
18, 0.666667, 1, 0, 0.5,3.4728e-06)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0354488,-0.0575799) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.465691,0.00953465) , 
8, 0.570606, 1, 0, 0.276222,-0.000274013) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.985195,-0.0336717) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.973305,0.0766165) , 
11, 5.5, 1, 0, 0.979812,0.000629426) , 
18, 0.833334, 1, 0, 0.5,1.33279e-05)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.304927,-0.149735) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0654738,0.0520362) , 
9, 0.333333, 1, 0, 0.0781508,0.0010532) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.872669,-0.00146786) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.857841,-0.285701) , 
7, 0.120629, 1, 0, 0.872154,-0.000917223) , 
8, 0.666667, 1, 0, 0.5,6.32451e-06)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.412003,0.112418) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0336581,-0.00978704) , 
9, 0.333333, 1, 0, 0.0670403,0.00102772) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.244978,-0.0186536) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.964157,0.0294026) , 
8, 0.770088, 1, 0, 0.62402,-0.000240328) , 
10, 0.333333, 1, 0, 0.5,4.20226e-05)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.94437,0.014463) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.674457,-0.120632) , 
13, 0.111106, 1, 0, 0.918168,-0.000907089) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.147065,0.166162) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.105812,0.00944766) , 
27, 0.5, 1, 0, 0.106706,0.000869584) , 
13, 0.166665, 1, 0, 0.5,8.47869e-06)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491187,-0.067097) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.642368,-0.0147187) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.268848,0.0166785) , 
7, 0.0841504, 1, 0, 0.500187,0.000138668) , 
27, 0.5, 1, 0, 0.5,2.47003e-05)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0456436,0.0140316) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.235594,-0.0771598) , 
10, 0.506257, 1, 0, 0.0668059,-0.000549563) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9195,-0.001888) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0463592,0.211699) , 
12, 0.832892, 1, 0, 0.864571,0.000466474) , 
5, 0.617794, 1, 0, 0.5,2.15498e-06)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.785132,-0.00325982) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.77677,0.0189862) , 
1, 1.23808, 1, 0, 0.781884,0.000444522) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.00777882,0.0104612) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.163901,-0.0755518) , 
18, 0.666667, 1, 0, 0.0267131,-0.000830606) , 
12, 0.666399, 1, 0, 0.5,-3.14475e-05)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.304927,-0.0755099) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0654738,0.000737419) , 
9, 0.333333, 1, 0, 0.0781508,-0.000507416) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.905388,-0.00426895) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.266391,0.0852061) , 
13, 0.333131, 1, 0, 0.872154,0.000444029) , 
8, 0.666667, 1, 0, 0.5,-1.91841e-06)    );
  // itree = 125
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.954719,-0.0363358) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.739053,0.0651479) , 
13, 0.0833293, 1, 0, 0.918168,0.000412459) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.414529,-0.0187921) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0159889,0.0301575) , 
12, 0.3332, 1, 0, 0.106706,-0.000387531) , 
13, 0.166665, 1, 0, 0.5,2.02497e-07)    );
  // itree = 126
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.869307,0.00387257) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.320315,0.0773425) , 
2, 0.00830501, 1, 0, 0.855984,0.000510466) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0447319,-0.00316556) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.825342,-0.0687722) , 
5, 0.785857, 1, 0, 0.0829789,-0.000554033) , 
12, 0.3332, 1, 0, 0.5,2.02436e-05)    );
  // itree = 127
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47803,-0.00425987) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.495072,0.0699913) , 
1, 1.03866, 1, 0, 0.480542,0.000333759) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525841,-0.0143751) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.755428,0.0987094) , 
6, 5.05394, 1, 0, 0.534787,-0.000580309) , 
1, 1.24642, 1, 0, 0.5,5.88013e-06)    );
  // itree = 128
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.608017,0.0180097) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0594012,-0.0307353) , 
11, 16.3333, 1, 0, 0.477314,0.000490044) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.481906,-0.0484671) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.529695,0.00344169) , 
1, 1.10799, 1, 0, 0.518538,-0.000391686) , 
1, 0.83095, 1, 0, 0.5,4.82435e-06)    );
  // itree = 129
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.332395,-0.00745298) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0414463,0.0321811) , 
11, 18.6667, 1, 0, 0.265243,-0.000240483) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.987644,-0.0162232) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.727039,0.0610204) , 
12, 0.333146, 1, 0, 0.966602,0.000483968) , 
10, 0.666667, 1, 0, 0.5,2.00282e-06)    );
  // itree = 130
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.925434,-0.000653247) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.181177,0.0296536) , 
13, 0.49998, 1, 0, 0.855984,0.000385813) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0447319,-0.004251) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.825342,-0.0463069) , 
5, 0.785857, 1, 0, 0.0829789,-0.000442161) , 
12, 0.3332, 1, 0, 0.5,4.51512e-06)    );
  // itree = 131
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.964166,0.0786244) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.605111,-0.0210401) , 
13, 0.0555549, 1, 0, 0.823318,0.000445661) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.194255,-0.0205393) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00519236,0.023264) , 
12, 0.499799, 1, 0, 0.0483622,-0.000620995) , 
13, 0.33333, 1, 0, 0.5,6.42666e-07)    );
  // itree = 132
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.967957,-0.0308633) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.239815,0.0526669) , 
12, 0.666314, 1, 0, 0.918168,-0.00061849) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.302319,0.0236302) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00594941,-0.0961347) , 
12, 0.666399, 1, 0, 0.106706,0.000652515) , 
13, 0.166665, 1, 0, 0.5,3.64936e-05)    );
  // itree = 133
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.874019,-0.0022573) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.348142,0.0518016) , 
11, 14.3333, 1, 0, 0.823318,0.000391276) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.194255,-0.023597) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00519236,0.0513312) , 
12, 0.499799, 1, 0, 0.0483622,-0.000575778) , 
13, 0.33333, 1, 0, 0.5,-1.21876e-05)    );
  // itree = 134
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.191322,-0.022488) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.920136,0.0170099) , 
5, 0.554742, 1, 0, 0.820828,0.000441199) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0274885,-0.00391789) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.757391,-0.105515) , 
5, 0.785857, 1, 0, 0.0519404,-0.000629505) , 
12, 0.499799, 1, 0, 0.5,-5.56572e-06)    );
  // itree = 135
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.932181,-0.00504309) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.21771,0.0412389) , 
13, 0.333271, 1, 0, 0.866474,0.000310825) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0209696,-0.151746) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258316,0.0103361) , 
8, 0.489209, 1, 0, 0.21272,-0.000226649) , 
11, 9.33333, 1, 0, 0.5,9.53394e-06)    );
  // itree = 136
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.24074,0.0701352) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00721645,0.0172161) , 
12, 0.3332, 1, 0, 0.0429263,0.0017542) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.680861,-0.0230342) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.426482,0.0126213) , 
7, 0.0947777, 1, 0, 0.625847,-0.000518595) , 
18, 0.5, 1, 0, 0.5,-2.79183e-05)    );
  // itree = 137
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.943921,0.038374) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0845452,-0.014063) , 
13, 0.166665, 1, 0, 0.642656,0.000670319) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.30138,-0.0253348) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0625166,0.126161) , 
17, 9.93196, 1, 0, 0.268783,-0.00109149) , 
7, 0.0841504, 1, 0, 0.5,-1.92069e-06)    );
  // itree = 138
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.954719,-0.0418995) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.739053,0.0315588) , 
13, 0.0833293, 1, 0, 0.918168,-0.000417288) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.383714,0.0242587) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0540473,-0.00439377) , 
13, 0.305583, 1, 0, 0.106706,0.000392526) , 
13, 0.166665, 1, 0, 0.5,3.08412e-08)    );
  // itree = 139
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.893068,0.00360729) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.423262,0.0493479) , 
3, 0.0333228, 1, 0, 0.866474,0.000507203) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.320337,-0.110989) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.19209,0.0060409) , 
7, 0.0593413, 1, 0, 0.21272,-0.000368301) , 
11, 9.33333, 1, 0, 0.5,1.64221e-05)    );
  // itree = 140
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.927212,-0.0165255) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298858,0.0402983) , 
11, 8.16667, 1, 0, 0.642656,0.000435869) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266045,-0.0132201) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.355109,0.0677031) , 
7, 0.192566, 1, 0, 0.268783,-0.000693764) , 
7, 0.0841504, 1, 0, 0.5,4.84357e-06)    );
  // itree = 141
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.265582,0.043945) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.265236,-0.00589144) , 
27, 0.5, 1, 0, 0.265243,-0.000286294) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.987644,-0.00335728) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.727039,0.0508819) , 
12, 0.333146, 1, 0, 0.966602,0.000578679) , 
10, 0.666667, 1, 0, 0.5,3.2269e-06)    );
  // itree = 142
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491187,-0.0356765) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552083,0.00497379) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.104592,-0.0403767) , 
3, 0.0333282, 1, 0, 0.500187,6.53769e-05) , 
27, 0.5, 1, 0, 0.5,3.33842e-06)    );
  // itree = 143
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.893068,0.001542) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.423262,0.0421112) , 
3, 0.0333228, 1, 0, 0.866474,0.000360849) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.211841,-0.0322054) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.21454,0.0238167) , 
7, 0.107669, 1, 0, 0.21272,-0.000282389) , 
11, 9.33333, 1, 0, 0.5,2.69641e-07)    );
  // itree = 144
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.769911,0.00692726) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0453443,-0.0160052) , 
13, 0.416653, 1, 0, 0.554804,0.000108838) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.00431446,-0.268221) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0615032,0.137341) , 
10, 0.384375, 1, 0, 0.019756,-0.000956645) , 
13, 0.833324, 1, 0, 0.5,-2.97601e-07)    );
  // itree = 145
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0584433,-0.090197) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0699083,0.0593439) , 
22, 0.166667, 1, 0, 0.0670403,0.000780101) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.346131,-0.0163936) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.981212,0.048892) , 
5, 0.787962, 1, 0, 0.62402,-0.000286258) , 
10, 0.333333, 1, 0, 0.5,-4.88165e-05)    );
  // itree = 146
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.964166,0.028876) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.793327,-0.0477355) , 
13, 0.0555529, 1, 0, 0.918168,-0.000612323) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.104511,0.00124847) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.118686,0.0429313) , 
1, 1.6619, 1, 0, 0.106706,0.000588261) , 
13, 0.166665, 1, 0, 0.5,6.37036e-06)    );
  // itree = 147
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0723286,-0.00644009) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.695706,0.01791) , 
8, 0.660665, 1, 0, 0.265243,0.000385101) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.979198,-0.0146611) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.58461,-0.0671859) , 
2, 0.00811352, 1, 0, 0.966602,-0.000725582) , 
10, 0.666667, 1, 0, 0.5,1.33363e-05)    );
  // itree = 148
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.807302,0.0311246) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0501581,-0.0490727) , 
12, 0.499735, 1, 0, 0.478581,0.000706587) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558284,0.00125111) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.108589,-0.0618666) , 
3, 0.0333282, 1, 0, 0.506506,-0.000208515) , 
22, 0.166667, 1, 0, 0.5,4.68989e-06)    );
  // itree = 149
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.838125,-0.00842034) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.219568,0.0642547) , 
4, 7.3196, 1, 0, 0.820828,-0.000383057) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.329228,0.0915144) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.036571,0.00428927) , 
12, 0.583111, 1, 0, 0.0519404,0.00053565) , 
12, 0.499799, 1, 0, 0.5,2.85824e-07)    );
   return;
};
 
// Clean up
inline void ReadNCuts 5::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadNCuts 5::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
