// Class: ReadShrinkage .5
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::Shrinkage .5
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.14/07       [396807]
Creator        : mchristos
Date           : Tue Nov 20 22:53:05 2018
Host           : Linux cmsbuild02.cern.ch 2.6.32-754.3.5.el6.x86_64 #1 SMP Wed Aug 15 08:57:36 CEST 2018 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /cms/mchristos/ANN/FireMVA/2016
Training events: 74267
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "150" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "1.0%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
Shrinkage: "5.000000e-01" [Learning rate for GradBoost algorithm]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "5" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 29
MuonPt                        MuonPt                        MuonPt                        MuonPt                                                          'F'    [10.0002336502,273.373016357]
abs(MuonEta)                  abs_MuonEta_                  abs(MuonEta)                  abs(MuonEta)                                                    'F'    [1.46795650835e-06,2.4928457737]
MuonDXY                       MuonDXY                       MuonDXY                       MuonDXY                                                         'F'    [1.25834446862e-07,0.0499910190701]
MuonDZ                        MuonDZ                        MuonDZ                        MuonDZ                                                          'F'    [7.31526483833e-08,0.0999844223261]
MuonSIP3D                     MuonSIP3D                     MuonSIP3D                     MuonSIP3D                                                       'F'    [0.00253649544902,54.8985595703]
MuonPtRatio                   MuonPtRatio                   MuonPtRatio                   MuonPtRatio                                                     'F'    [-1,2.23558855057]
MuonPtRel                     MuonPtRel                     MuonPtRel                     MuonPtRel                                                       'F'    [-1,52.0110664368]
MuonJetLRM                    MuonJetLRM                    MuonJetLRM                    MuonJetLRM                                                      'F'    [-1,0.300980508327]
MuonJetFD                     MuonJetFD                     MuonJetFD                     MuonJetFD                                                       'F'    [-1,1]
MuonJetInOutRatio             MuonJetInOutRatio             MuonJetInOutRatio             MuonJetInOutRatio                                               'F'    [-9999,1]
MuonJetZest                   MuonJetZest                   MuonJetZest                   MuonJetZest                                                     'F'    [-1,1]
MuonJetNoOfConst              MuonJetNoOfConst              MuonJetNoOfConst              MuonJetNoOfConst                                                'F'    [0,56]
MuonJetCSV                    MuonJetCSV                    MuonJetCSV                    MuonJetCSV                                                      'F'    [0,0.999598562717]
MuonRelPFIsoPUCorr            MuonRelPFIsoPUCorr            MuonRelPFIsoPUCorr            MuonRelPFIsoPUCorr                                              'F'    [0,0.999988734722]
MuonRelTrkIso                 MuonRelTrkIso                 MuonRelTrkIso                 MuonRelTrkIso                                                   'F'    [0,148.893722534]
MuonPFChargedHadronIso        MuonPFChargedHadronIso        MuonPFChargedHadronIso        MuonPFChargedHadronIso                                          'F'    [0,137.792205811]
MuonPFNeutralHadronIso        MuonPFNeutralHadronIso        MuonPFNeutralHadronIso        MuonPFNeutralHadronIso                                          'F'    [0,59.2765274048]
MuonPFPhotonIso               MuonPFPhotonIso               MuonPFPhotonIso               MuonPFPhotonIso                                                 'F'    [0,136.399520874]
MuonJetMuonEnergyFraction     MuonJetMuonEnergyFraction     MuonJetMuonEnergyFraction     MuonJetMuonEnergyFraction                                       'F'    [0,1.00000023842]
MuonJetMuonEnergyFraction     MuonJetMuonEnergyFraction     MuonJetMuonEnergyFraction     MuonJetMuonEnergyFraction                                       'F'    [0,1.00000023842]
MuonIsPF                      MuonIsPF                      MuonIsPF                      MuonIsPF                                                        'F'    [1,1]
MuonIsTracker                 MuonIsTracker                 MuonIsTracker                 MuonIsTracker                                                   'F'    [0,1]
MuonTrkValidFractionOfHits    MuonTrkValidFractionOfHits    MuonTrkValidFractionOfHits    MuonTrkValidFractionOfHits                                      'F'    [0,1]
MuonIsGlobal                  MuonIsGlobal                  MuonIsGlobal                  MuonIsGlobal                                                    'F'    [0,1]
MuonGlobalChi2                MuonGlobalChi2                MuonGlobalChi2                MuonGlobalChi2                                                  'F'    [-9999,5167.52246094]
MuonChi2LocalPosition         MuonChi2LocalPosition         MuonChi2LocalPosition         MuonChi2LocalPosition                                           'F'    [-1,37339.6367188]
MuonTrkKink                   MuonTrkKink                   MuonTrkKink                   MuonTrkKink                                                     'F'    [0,3863.02807617]
MuonSegmentCompatibility      MuonSegmentCompatibility      MuonSegmentCompatibility      MuonSegmentCompatibility                                        'F'    [0,1]
MuonPt                        MuonPt                        MuonPt                        MuonPt                                                          'F'    [10.0002336502,273.373016357]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new Shrinkage .5Node
   
#ifndef Shrinkage .5Node__def
#define Shrinkage .5Node__def
   
class Shrinkage .5Node {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   Shrinkage .5Node ( Shrinkage .5Node* left,Shrinkage .5Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~Shrinkage .5Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   Shrinkage .5Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   Shrinkage .5Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   Shrinkage .5Node*   fLeft;     // pointer to the left daughter node
   Shrinkage .5Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   Shrinkage .5Node::~Shrinkage .5Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool Shrinkage .5Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool Shrinkage .5Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadShrinkage .5 : public IClassifierReader {

 public:

   // constructor
   ReadShrinkage .5( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadShrinkage .5" ),
        fNvars( 29 ),
        fIsNormalised( false )
   {
      // the training input variables
      const char* inputVars[] = { "MuonPt", "abs(MuonEta)", "MuonDXY", "MuonDZ", "MuonSIP3D", "MuonPtRatio", "MuonPtRel", "MuonJetLRM", "MuonJetFD", "MuonJetInOutRatio", "MuonJetZest", "MuonJetNoOfConst", "MuonJetCSV", "MuonRelPFIsoPUCorr", "MuonRelTrkIso", "MuonPFChargedHadronIso", "MuonPFNeutralHadronIso", "MuonPFPhotonIso", "MuonJetMuonEnergyFraction", "MuonJetMuonEnergyFraction", "MuonIsPF", "MuonIsTracker", "MuonTrkValidFractionOfHits", "MuonIsGlobal", "MuonGlobalChi2", "MuonChi2LocalPosition", "MuonTrkKink", "MuonSegmentCompatibility", "MuonPt" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;
      fVmin[16] = 0;
      fVmax[16] = 0;
      fVmin[17] = 0;
      fVmax[17] = 0;
      fVmin[18] = 0;
      fVmax[18] = 0;
      fVmin[19] = 0;
      fVmax[19] = 0;
      fVmin[20] = 0;
      fVmax[20] = 0;
      fVmin[21] = 0;
      fVmax[21] = 0;
      fVmin[22] = 0;
      fVmax[22] = 0;
      fVmin[23] = 0;
      fVmax[23] = 0;
      fVmin[24] = 0;
      fVmax[24] = 0;
      fVmin[25] = 0;
      fVmax[25] = 0;
      fVmin[26] = 0;
      fVmax[26] = 0;
      fVmin[27] = 0;
      fVmax[27] = 0;
      fVmin[28] = 0;
      fVmax[28] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';
      fType[19] = 'F';
      fType[20] = 'F';
      fType[21] = 'F';
      fType[22] = 'F';
      fType[23] = 'F';
      fType[24] = 'F';
      fType[25] = 'F';
      fType[26] = 'F';
      fType[27] = 'F';
      fType[28] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadShrinkage .5() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[29];
   double fVmax[29];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[29];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<Shrinkage .5Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadShrinkage .5::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      Shrinkage .5Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(Shrinkage .5Node*)current->GetRight();
         else current=(Shrinkage .5Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadShrinkage .5::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.46748,-0.0325204) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0265561,-0.473444) , 
12, 0.2856, 1, 0, 0.120402,-0.379598) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.966479,0.46648) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.211136,-0.288864) , 
12, 0.761477, 1, 0, 0.940855,0.440855) , 
5, 0.694832, 1, 0, 0.5,6.95826e-16)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.954377,0.322589) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0886011,-0.253518) , 
12, 0.809095, 1, 0, 0.906832,0.239465) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461676,-0.0730737) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0283946,-0.329148) , 
12, 0.1904, 1, 0, 0.0927246,-0.239668) , 
13, 0.190474, 1, 0, 0.5,2.92191e-05)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.958231,0.260851) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.232589,-0.152967) , 
12, 0.571126, 1, 0, 0.880691,0.130473) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0396025,-0.270523) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304004,-0.00623987) , 
10, 0.52381, 1, 0, 0.0730445,-0.146786) , 
13, 0.238093, 1, 0, 0.5,-0.00021575)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.937748,0.222545) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.185296,-0.19506) , 
15, 6.31618, 1, 0, 0.882275,0.0838519) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.768585,0.176905) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0505491,-0.236362) , 
13, 0.0476185, 1, 0, 0.107418,-0.0857011) , 
12, 0.238, 1, 0, 0.5,0.000203165)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.639921,0.123191) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0789372,-0.205151) , 
9, 0.333333, 1, 0, 0.146479,-0.0560005) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.920229,0.204511) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.274684,-0.188971) , 
2, 0.00713398, 1, 0, 0.865815,0.057184) , 
10, 0.52381, 1, 0, 0.5,-0.000375461)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.968277,0.208025) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.310624,-0.241386) , 
4, 8.94038, 1, 0, 0.950787,0.0460133) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.397487,0.00239637) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0329183,-0.227041) , 
4, 2.61663, 1, 0, 0.175027,-0.0336315) , 
13, 0.095237, 1, 0, 0.5,-0.000267583)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.884057,0.146039) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.242444,-0.100672) , 
15, 2.49955, 1, 0, 0.742398,0.0191275) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0138051,-0.22182) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.168135,0.0903679) , 
6, 4.57447, 1, 0, 0.0244099,-0.0379659) , 
15, 6.56153, 1, 0, 0.5,-0.000147633)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.853078,0.0975283) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.280467,-0.357604) , 
4, 5.99625, 1, 0, 0.834941,0.0172039) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0238833,-0.198004) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.509057,0.0487278) , 
10, 0.602126, 1, 0, 0.0657969,-0.0237332) , 
12, 0.428399, 1, 0, 0.5,-0.000623114)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.623654,0.0876281) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0614833,-0.160936) , 
9, 0.238095, 1, 0, 0.0955162,-0.0216562) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.760374,0.0350154) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.498388,0.264977) , 
7, 0.14026, 1, 0, 0.744494,0.0116707) , 
10, 0.428571, 1, 0, 0.5,-0.000884798)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.901225,0.0981149) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0157896,-0.2125) , 
12, 0.856662, 1, 0, 0.831217,0.0126821) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.168181,-0.134302) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.228137,0.0964788) , 
7, 0.135368, 1, 0, 0.177521,-0.0139067) , 
11, 10.6667, 1, 0, 0.5,-0.000789976)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.769715,0.0277987) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.520447,0.137366) , 
7, 0.115126, 1, 0, 0.73862,0.0096434) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.725547,-0.166885) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0807315,-0.0816432) , 
12, 0.238, 1, 0, 0.176512,-0.0143249) , 
2, 0.00238064, 1, 0, 0.5,-0.00053135)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.273622,-0.105091) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0163766,-0.134095) , 
12, 0.1904, 1, 0, 0.0409807,-0.0147808) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.779283,0.00308604) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.578998,0.13875) , 
7, 0.0981827, 1, 0, 0.745554,0.00749235) , 
5, 0.540756, 1, 0, 0.5,-0.000270158)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.209504,-0.0825143) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.275986,0.0464661) , 
7, 0.115126, 1, 0, 0.227385,-0.00710933) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.982928,0.146816) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.932879,-0.0652893) , 
17, 2.01647, 1, 0, 0.978149,0.0116864) , 
8, 0.809524, 1, 0, 0.5,-0.000284295)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.743729,0.00794761) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.538745,0.166023) , 
16, 2.64184, 1, 0, 0.719805,0.00542384) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0897861,-0.107207) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.254921,0.146503) , 
7, 0.177344, 1, 0, 0.0972652,-0.00973312) , 
11, 13.3333, 1, 0, 0.5,7.22562e-05)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.819975,0.0739703) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.430351,-0.0239741) , 
4, 1.12282, 1, 0, 0.619011,0.00348495) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.202084,-0.26394) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0224661,-0.152762) , 
12, 0.380799, 1, 0, 0.0321073,-0.01387) , 
4, 7.84483, 1, 0, 0.5,-3.42411e-05)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.703522,-0.0411492) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.984767,0.140062) , 
8, 0.714286, 1, 0, 0.966426,0.0090929) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.237802,-0.0443348) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.716528,0.128116) , 
6, 5.66235, 1, 0, 0.264403,-0.00467719) , 
13, 0.0476185, 1, 0, 0.5,-5.59844e-05)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.726031,0.00599495) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.459819,0.0659308) , 
7, 0.115126, 1, 0, 0.688594,0.00345341) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.00110619,-0.217833) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0268719,-0.149763) , 
10, 0.513709, 1, 0, 0.00457384,-0.00856721) , 
12, 0.856799, 1, 0, 0.5,0.000139159)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.322666,-0.0787448) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0198333,-0.0425042) , 
12, 0.1904, 1, 0, 0.0513774,-0.00584191) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.825991,-0.0146763) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.675806,0.0893232) , 
7, 0.0831968, 1, 0, 0.794314,0.0036526) , 
8, 0.619048, 1, 0, 0.5,-0.000108641)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.257651,-0.0774559) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.989052,0.128824) , 
5, 0.848908, 1, 0, 0.474513,-0.00555017) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47947,0.0111321) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.746476,0.114323) , 
6, 4.04867, 1, 0, 0.516092,0.00342165) , 
1, 0.712243, 1, 0, 0.5,-5.06478e-05)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.245895,0.0819365) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0288338,-0.100495) , 
9, 0.714286, 1, 0, 0.146479,0.00398418) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.934535,0.00278998) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.235519,-0.140119) , 
15, 4.11151, 1, 0, 0.865815,-0.00408032) , 
10, 0.52381, 1, 0, 0.5,2.08454e-05)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.688662,-0.00169202) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.446954,0.0987115) , 
16, 2.64184, 1, 0, 0.656286,0.00219873) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.329187,-0.07422) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0117025,-0.0769239) , 
12, 0.285571, 1, 0, 0.0637157,-0.0063623) , 
11, 16, 1, 0, 0.5,-5.91783e-05)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.300245,-0.0232691) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.986085,0.0984507) , 
5, 0.814776, 1, 0, 0.503735,-0.000622576) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.600462,0.11989) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.039313,-0.0100993) , 
12, 0.713854, 1, 0, 0.333713,0.0254117) , 
7, 0.177078, 1, 0, 0.5,-5.05917e-05)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.956572,0.0340726) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.736705,-0.136295) , 
15, 1.06981, 1, 0, 0.906832,-0.00356548) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.255585,0.0555188) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00407835,-0.130875) , 
12, 0.713999, 1, 0, 0.0927246,0.00363637) , 
13, 0.190474, 1, 0, 0.5,3.34787e-05)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.741705,0.0336454) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.14678,-0.0355822) , 
17, 2.69619, 1, 0, 0.500521,0.000585321) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.937801,-0.0485621) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.103481,-0.323563) , 
11, 11.4762, 1, 0, 0.485424,-0.0160137) , 
0, 60.1665, 1, 0, 0.5,1.26999e-05)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.14621,0.0251668) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.853675,-0.0437542) , 
10, 0.52381, 1, 0, 0.472766,-0.000833938) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57325,0.161329) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.984938,0.0934739) , 
10, 0.708853, 1, 0, 0.912501,0.0125075) , 
6, 6.57301, 1, 0, 0.5,-7.66841e-06)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0451804,-0.0709291) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.705194,0.0211593) , 
8, 0.52381, 1, 0, 0.618031,0.0015056) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.281667,-0.179328) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.024945,-0.0682933) , 
12, 0.3332, 1, 0, 0.0387204,-0.00578079) , 
2, 0.0095222, 1, 0, 0.5,2.10493e-05)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47269,-0.245599) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470847,-0.0299775) , 
27, 0.52381, 1, 0, 0.470927,-0.00420697) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553896,-0.000987675) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.281969,0.0527108) , 
7, 0.115126, 1, 0, 0.510159,0.00146059) , 
1, 0.474829, 1, 0, 0.5,-6.97314e-06)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.657866,-0.0880961) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.324153,0.00578908) , 
7, 0.0531747, 1, 0, 0.386433,-0.00116723) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.995686,0.169132) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.989203,0.0333691) , 
17, 0.618343, 1, 0, 0.9941,0.00506589) , 
8, 0.904762, 1, 0, 0.5,-2.31657e-06)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.930178,0.0679069) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437561,-0.027524) , 
12, 0.142777, 1, 0, 0.715024,0.00225534) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.798528,-0.106803) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.103804,0.0369909) , 
12, 0.238, 1, 0, 0.269837,-0.00225287) , 
3, 0.00476123, 1, 0, 0.5,7.78925e-05)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.641662,0.00483543) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00172276,-0.203689) , 
12, 0.904399, 1, 0, 0.491841,-0.000511449) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.917817,-0.025403) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.198948,0.147453) , 
13, 0.142662, 1, 0, 0.64092,0.0104144) , 
1, 2.13673, 1, 0, 0.5,8.64847e-05)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471613,-0.0876553) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502589,0.0147931) , 
0, 11.7918, 1, 0, 0.500971,0.00056581) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.223229,-0.167876) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.994662,0.144119) , 
5, 0.853827, 1, 0, 0.488975,-0.00690894) , 
0, 47.6249, 1, 0, 0.5,-3.94113e-05)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.95549,0.0596712) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0940342,-0.247204) , 
14, 0.24748, 1, 0, 0.926192,0.00276955) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.698226,0.0629263) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.13347,-0.0571575) , 
9, 0.47619, 1, 0, 0.298563,-0.00132788) , 
11, 8, 1, 0, 0.5,-1.28101e-05)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.925467,0.00214347) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.588717,-0.108166) , 
17, 2.71403, 1, 0, 0.880691,-0.00283094) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.251918,0.109373) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0460451,-0.00391273) , 
13, 0.346946, 1, 0, 0.0730445,0.00316313) , 
13, 0.238093, 1, 0, 0.5,-5.57989e-06)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0649679,-0.0104026) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.415327,0.0724679) , 
5, 0.614121, 1, 0, 0.120402,0.00243447) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.790365,-0.111261) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.9763,0.0310267) , 
5, 0.768222, 1, 0, 0.940855,-0.00279493) , 
5, 0.694832, 1, 0, 0.5,1.49896e-05)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.208081,0.052873) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.113545,-0.0119219) , 
0, 21.3719, 1, 0, 0.146479,0.00240547) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.398624,-0.0666578) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.947488,0.00280127) , 
8, 0.721448, 1, 0, 0.865815,-0.00236656) , 
10, 0.52381, 1, 0, 0.5,6.02363e-05)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.852124,-0.0258537) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0882619,0.0148016) , 
12, 0.238, 1, 0, 0.437227,-0.00121229) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.863847,-0.00841199) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.52529,0.0971341) , 
7, 0.099481, 1, 0, 0.765419,0.00526526) , 
6, 4.04867, 1, 0, 0.5,2.66734e-05)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535935,0.000701913) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.190442,0.127832) , 
3, 0.0618951, 1, 0, 0.528118,0.000457438) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.027178,-0.302847) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.000681044,-0.195467) , 
13, 0.333319, 1, 0, 0.00599038,-0.00765688) , 
4, 18.3012, 1, 0, 0.5,2.0458e-05)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.947829,-0.0848589) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.423223,0.0324272) , 
12, 0.0475938, 1, 0, 0.500585,0.00213964) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.89647,0.0281435) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.248478,-0.0334771) , 
11, 8.95238, 1, 0, 0.499611,-0.0014477) , 
27, 0.904762, 1, 0, 0.5,-1.45657e-05)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.922223,-0.00954837) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.383622,-0.145386) , 
17, 5.42805, 1, 0, 0.906832,-0.00179787) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.154797,0.0447333) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0593674,-0.0176081) , 
0, 21.3719, 1, 0, 0.0927246,0.00180893) , 
13, 0.190474, 1, 0, 0.5,4.54554e-06)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.823594,0.0365035) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.294062,-0.030582) , 
17, 1.23714, 1, 0, 0.534653,-0.000518412) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.195331,0.204944) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0133556,-0.0439119) , 
11, 14.8571, 1, 0, 0.0500365,0.00676442) , 
17, 12.9904, 1, 0, 0.5,2.3559e-06)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0357052,-0.0162806) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388976,0.0433964) , 
8, 0.601107, 1, 0, 0.146479,0.00198135) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527334,-0.0455966) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.970865,0.0148069) , 
8, 0.777159, 1, 0, 0.865815,-0.00204195) , 
10, 0.52381, 1, 0, 0.5,4.08401e-06)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423719,-0.0185537) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505009,0.0316002) , 
6, 3.08699, 1, 0, 0.437227,-0.00107648) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.773222,0.0264867) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.661714,0.177383) , 
1, 1.63759, 1, 0, 0.765419,0.00459345) , 
6, 4.04867, 1, 0, 0.5,8.00705e-06)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.844303,-0.029174) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.346201,0.126501) , 
17, 7.12297, 1, 0, 0.831217,-0.00185885) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540769,0.0452946) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0279463,-0.0203689) , 
13, 0.33333, 1, 0, 0.177521,0.00183194) , 
11, 10.6667, 1, 0, 0.5,1.12123e-05)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.924719,0.0145099) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.281546,-0.0246199) , 
12, 0.142782, 1, 0, 0.546192,-0.000800744) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.762076,-0.0295709) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.115137,0.0645297) , 
12, 0.1904, 1, 0, 0.276853,0.00397435) , 
7, 0.115126, 1, 0, 0.5,1.81955e-05)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502748,0.048996) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.469067,-0.0101008) , 
6, 0.803076, 1, 0, 0.472766,-0.00038004) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57325,0.104235) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.984938,0.01665) , 
10, 0.708853, 1, 0, 0.912501,0.00577253) , 
6, 6.57301, 1, 0, 0.5,1.00421e-06)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471693,0.103106) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.715749,0.0109283) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.268924,-0.0168591) , 
3, 0.00476123, 1, 0, 0.500329,-0.0001513) , 
23, 0.047619, 1, 0, 0.5,3.8745e-06)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.840553,0.0209124) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0544447,-0.0346647) , 
15, 3.6919, 1, 0, 0.500455,0.000149235) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.455679,-0.232204) , 
0, 85.2496, 1, 0, 0.5,3.16043e-06)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.956572,0.0128124) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.736705,-0.0612292) , 
15, 1.06981, 1, 0, 0.906832,-0.0018932) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.255585,0.0263246) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00407835,-0.0667639) , 
12, 0.713999, 1, 0, 0.0927246,0.00189314) , 
13, 0.190474, 1, 0, 0.5,-1.06011e-06)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.98421,0.0378486) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.796569,-0.153216) , 
4, 1.97631, 1, 0, 0.952266,-0.00410976) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626026,-0.0424028) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258729,0.0298711) , 
7, 0.0716728, 1, 0, 0.422292,0.000706708) , 
12, 0.0475999, 1, 0, 0.5,4.88709e-07)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.464756,-0.031766) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0236471,0.00929397) , 
12, 0.2856, 1, 0, 0.115854,-0.00214832) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.957842,0.00780883) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.18486,0.172744) , 
12, 0.761501, 1, 0, 0.925036,0.00243676) , 
8, 0.714286, 1, 0, 0.5,2.83743e-05)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.241737,0.0175924) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.914483,-0.00752248) , 
10, 0.52381, 1, 0, 0.646575,0.000716278) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0267679,-0.137335) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.000680861,-0.183173) , 
13, 0.142856, 1, 0, 0.0020633,-0.00245279) , 
12, 0.904399, 1, 0, 0.5,-4.43251e-06)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.530758,-0.0556264) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0632847,0.00244129) , 
13, 0.190474, 1, 0, 0.115854,-0.00134937) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.957842,0.00453284) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.18486,0.0952647) , 
12, 0.761501, 1, 0, 0.925036,0.00141314) , 
8, 0.714286, 1, 0, 0.5,-3.79108e-05)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.904212,0.044537) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.232769,-0.109541) , 
12, 0.142777, 1, 0, 0.477905,-0.00459) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.516287,0.00495257) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.059581,-0.0957905) , 
16, 8.46808, 1, 0, 0.501589,0.000309233) , 
1, 0.118708, 1, 0, 0.5,-1.93752e-05)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594626,-0.0304573) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.481074,0.0355853) , 
16, 0.672047, 1, 0, 0.554927,-0.00058744) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0402994,-0.0411931) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.676741,0.077138) , 
5, 0.572806, 1, 0, 0.243651,0.00267559) , 
16, 2.82269, 1, 0, 0.5,-1.1657e-05)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.464227,-0.124877) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.477766,-0.00471625) , 
27, 0.52381, 1, 0, 0.477323,-0.00093917) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.629577,-0.00921934) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.257202,0.0407659) , 
7, 0.0912428, 1, 0, 0.528852,0.0012053) , 
1, 1.06836, 1, 0, 0.5,4.58308e-06)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.764538,-0.0528681) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.276442,0.00263268) , 
12, 0.0951999, 1, 0, 0.315275,-0.000680412) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.993534,0.0917369) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.851632,-0.0995026) , 
12, 0.332934, 1, 0, 0.984978,0.00179907) , 
18, 0.857143, 1, 0, 0.5,3.50647e-06)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.578367,0.0724971) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.483554,-0.00422019) , 
6, 0.441131, 1, 0, 0.48734,-0.000134965) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.950385,0.101615) , 
6, 9.09735, 1, 0, 0.5,4.17839e-05)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.812592,0.0131085) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.621682,-0.0457935) , 
4, 1.24705, 1, 0, 0.759081,-0.000836252) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0277758,0.0715284) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.714807,-0.0444783) , 
5, 0.694832, 1, 0, 0.130438,0.00125461) , 
4, 2.61663, 1, 0, 0.5,2.5448e-05)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534405,-0.0476538) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.162014,-0.00233757) , 
12, 0.0951999, 1, 0, 0.178624,-0.00106011) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.551692,-0.070128) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.967074,0.0313481) , 
8, 0.775944, 1, 0, 0.954231,0.00150489) , 
18, 0.761905, 1, 0, 0.5,2.71049e-06)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.955972,-0.00835407) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.237763,0.0229781) , 
13, 0.238086, 1, 0, 0.794255,0.000969437) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462779,-0.0751099) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0158393,-0.016064) , 
13, 0.0476185, 1, 0, 0.0317656,-0.0015122) , 
12, 0.618799, 1, 0, 0.5,1.174e-05)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.177225,0.120335) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.114651,-0.0129002) , 
27, 0.47619, 1, 0, 0.115854,-0.00107849) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.938747,-0.0144041) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.880155,0.0491793) , 
7, 0.067435, 1, 0, 0.925036,0.0012037) , 
8, 0.714286, 1, 0, 0.5,4.94606e-06)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532609,-0.00101972) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0591396,0.0880674) , 
17, 14.868, 1, 0, 0.511457,0.000165514) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0264438,-0.180094) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00535793,0.232401) , 
4, 6.90356, 1, 0, 0.0164712,-0.00653674) , 
11, 26.6667, 1, 0, 0.5,1.03788e-05)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.107868,0.00274974) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.77329,-0.0480827) , 
5, 0.694832, 1, 0, 0.178624,-0.00084185) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976536,0.0379197) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.671882,-0.0433991) , 
2, 0.00472209, 1, 0, 0.954231,0.00117197) , 
18, 0.761905, 1, 0, 0.5,-7.41685e-06)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.24258,-0.0227744) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.966242,0.0153247) , 
5, 0.665795, 1, 0, 0.759081,-0.000911415) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.65191,-0.0567187) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0935643,0.0361539) , 
12, 0.1904, 1, 0, 0.130438,0.0013344) , 
4, 2.61663, 1, 0, 0.5,1.41445e-05)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.36829,0.0212071) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00472616,-0.0714528) , 
12, 0.713999, 1, 0, 0.146479,0.00127333) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527334,-0.0298577) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.970865,0.0106888) , 
8, 0.777159, 1, 0, 0.865815,-0.00130422) , 
10, 0.52381, 1, 0, 0.5,6.58196e-06)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.817188,0.0139573) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0343231,-0.0281124) , 
12, 0.523599, 1, 0, 0.482534,0.00052667) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.852814,-0.039067) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.161645,0.0321756) , 
12, 0.333169, 1, 0, 0.557031,-0.00174188) , 
1, 1.54319, 1, 0, 0.5,-5.18292e-06)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.898807,0.0454241) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.142469,-0.0280847) , 
15, 1.64255, 1, 0, 0.499894,0.000555943) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.513739,-0.0578551) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277688,0.141276) , 
7, 0.100839, 1, 0, 0.500322,-0.00169615) , 
0, 35.0834, 1, 0, 0.5,-6.13342e-07)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.981766,0.021308) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.607741,-0.0481757) , 
12, 0.190375, 1, 0, 0.906832,-0.00129659) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461676,-0.0143175) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0283946,0.0448402) , 
12, 0.1904, 1, 0, 0.0927246,0.00132798) , 
13, 0.190474, 1, 0, 0.5,1.49806e-05)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0151229,-0.0945477) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0611906,0.0285134) , 
10, 0.364573, 1, 0, 0.027018,-0.00224247) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.668665,-0.0161093) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.412759,0.0329723) , 
7, 0.0922435, 1, 0, 0.607803,0.000516239) , 
8, 0.52381, 1, 0, 0.5,4.18056e-06)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.759134,-0.00603651) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.136629,0.0169724) , 
4, 2.61663, 1, 0, 0.509783,0.000119975) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0045439,-0.248834) , 
2, 0.0380884, 1, 0, 0.5,-1.0047e-05)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.938641,0.0254562) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0610917,-0.149282) , 
14, 0.384434, 1, 0, 0.913929,0.0012643) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.388462,-0.046736) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.20802,0.0090202) , 
7, 0.0716728, 1, 0, 0.269193,-0.000724493) , 
12, 0.1428, 1, 0, 0.5,-1.25312e-05)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462544,-0.0482929) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.49256,-0.000865088) , 
27, 0.52381, 1, 0, 0.491841,-0.00024018) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.907463,-0.0484887) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.361939,0.0716143) , 
12, 0.190382, 1, 0, 0.64092,0.00387954) , 
1, 2.13673, 1, 0, 0.5,-1.47222e-05)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.214618,-0.0831536) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.044451,-0.00489362) , 
9, 0.333333, 1, 0, 0.0513774,-0.00116633) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.807768,0.00182024) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.218933,0.112095) , 
13, 0.571303, 1, 0, 0.794314,0.000755382) , 
8, 0.619048, 1, 0, 0.5,-5.90448e-06)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.219969,0.018968) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0043982,-0.137775) , 
4, 7.84773, 1, 0, 0.146479,0.00103456) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.346846,-0.0534438) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.933091,0.00531547) , 
8, 0.693593, 1, 0, 0.865815,-0.00108263) , 
10, 0.52381, 1, 0, 0.5,-5.94285e-06)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.866474,0.00393395) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.543699,-0.0710858) , 
11, 9.04762, 1, 0, 0.831217,-0.000943744) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.118137,-0.000447901) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.959624,0.117268) , 
5, 0.785857, 1, 0, 0.177521,0.000877085) , 
11, 10.6667, 1, 0, 0.5,-2.11611e-05)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.848036,0.0313404) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.716408,-0.0198661) , 
4, 0.624793, 1, 0, 0.759081,-0.000695585) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.65191,-0.0477747) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0935643,0.0285627) , 
12, 0.1904, 1, 0, 0.130438,0.00100953) , 
4, 2.61663, 1, 0, 0.5,7.13703e-06)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499732,0.0482632) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0975152,-0.000812813) , 
11, 8, 1, 0, 0.120402,0.000783555) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.932145,-0.0700358) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.945135,0.0303325) , 
0, 22.5467, 1, 0, 0.940855,-0.000894875) , 
5, 0.694832, 1, 0, 0.5,6.99758e-06)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504493,0.009304) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.504156,-0.0072505) , 
27, 0.904762, 1, 0, 0.504291,-5.77622e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.108274,0.078345) , 
3, 0.0857009, 1, 0, 0.5,3.02037e-05)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480461,-0.0522413) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.50194,0.00989322) , 
0, 12.3888, 1, 0, 0.500521,0.000172469) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.708052,-0.128287) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0106524,0.150138) , 
13, 0.476133, 1, 0, 0.485424,-0.00438295) , 
0, 60.1665, 1, 0, 0.5,1.53191e-05)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.896295,0.0507531) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.198686,-0.0167202) , 
15, 1.05233, 1, 0, 0.500878,0.0013181) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536342,-0.0274978) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.231922,0.0533409) , 
7, 0.103798, 1, 0, 0.499479,-0.000764174) , 
0, 22.5418, 1, 0, 0.5,1.124e-05)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.92558,-0.0108229) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.156149,0.019922) , 
13, 0.190474, 1, 0, 0.656286,0.000556285) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.288056,-0.0349824) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00965932,0.01444) , 
12, 0.380762, 1, 0, 0.0637157,-0.00148745) , 
11, 16, 1, 0, 0.5,1.72666e-05)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.235479,0.0402391) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.323345,-0.00905703) , 
6, 0.804939, 1, 0, 0.315275,-0.000528409) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.987932,0.0575651) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.948368,-0.0762445) , 
17, 1.82053, 1, 0, 0.984978,0.00141356) , 
18, 0.857143, 1, 0, 0.5,7.24553e-06)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532329,0.0017876) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.109167,-0.0523759) , 
16, 5.64538, 1, 0, 0.503735,-0.000112239) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.116282,-0.0546322) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.527039,0.0707658) , 
18, 0.431489, 1, 0, 0.333713,0.00576027) , 
7, 0.177078, 1, 0, 0.5,1.67828e-05)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.988428,0.0278562) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.656414,-0.0716945) , 
12, 0.285563, 1, 0, 0.950787,-0.00102287) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.111422,-0.000281134) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.784213,0.0353744) , 
18, 0.761905, 1, 0, 0.175027,0.000749592) , 
13, 0.095237, 1, 0, 0.5,7.09366e-06)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.718262,-0.0150894) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.182583,0.0637178) , 
2, 0.00238007, 1, 0, 0.478581,0.0016203) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488534,0.0055193) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.552127,-0.0240634) , 
1, 1.42448, 1, 0, 0.506506,-0.000468488) , 
22, 0.047619, 1, 0, 0.5,1.8169e-05)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0826686,0.0219461) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.723297,-0.0233605) , 
10, 0.428571, 1, 0, 0.477323,-0.000903457) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.500289,0.0910066) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.53107,0.00465889) , 
1, 1.13621, 1, 0, 0.528852,0.00117046) , 
1, 1.06836, 1, 0, 0.5,9.24838e-06)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.70742,-0.00228334) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28021,0.0162641) , 
3, 0.00952239, 1, 0, 0.59794,0.000368792) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.000382896,-0.187792) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00542827,-0.223417) , 
10, 0.564287, 1, 0, 0.000715334,-0.00183805) , 
12, 0.951999, 1, 0, 0.5,6.88872e-06)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.981194,0.0380477) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.837214,-0.0841484) , 
7, 0.061167, 1, 0, 0.952266,-0.00199566) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435107,-0.00291086) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.280125,0.0342054) , 
7, 0.143331, 1, 0, 0.422292,0.00031979) , 
12, 0.0475999, 1, 0, 0.5,-1.97158e-05)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0555071,0.0069656) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0380904,-0.0689401) , 
1, 1.4245, 1, 0, 0.0513774,-0.000953972) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.242551,0.0554664) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.813521,0.00148938) , 
5, 0.556328, 1, 0, 0.794314,0.000624097) , 
8, 0.619048, 1, 0, 0.5,-1.05367e-06)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519596,3.40588e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0373563,0.123229) , 
11, 24.7619, 1, 0, 0.511457,0.000103694) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0242306,-0.148075) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00796699,0.0750051) , 
2, 0.00712972, 1, 0, 0.0164712,-0.00474839) , 
11, 26.6667, 1, 0, 0.5,-8.61508e-06)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661171,-0.0750793) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.133813,0.143086) , 
2, 0.0047519, 1, 0, 0.491903,-0.00359857) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498166,0.0803914) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500334,-1.00076e-05) , 
27, 0.612292, 1, 0, 0.500304,0.000123163) , 
27, 0.571429, 1, 0, 0.5,-1.15237e-05)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897754,0.00615269) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0901494,-0.0228165) , 
12, 0.190369, 1, 0, 0.477323,-0.000572499) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.88963,-0.00875362) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0848771,0.0231586) , 
13, 0.190468, 1, 0, 0.528852,0.000716648) , 
1, 1.06836, 1, 0, 0.5,-5.16152e-06)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.199242,-0.0541589) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00777779,0.0273636) , 
12, 0.380749, 1, 0, 0.0480962,-0.00209856) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.677606,-0.0107787) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.297425,0.0134051) , 
7, 0.0859957, 1, 0, 0.542508,0.000192049) , 
10, 0.238095, 1, 0, 0.5,-4.88908e-06)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.111953,-0.00367162) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.267991,-0.0840196) , 
18, 0.70101, 1, 0, 0.115854,-0.00083782) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.957842,0.000200564) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.18486,0.0857833) , 
12, 0.761501, 1, 0, 0.925036,0.000919587) , 
8, 0.714286, 1, 0, 0.5,-3.51894e-06)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471693,0.0511922) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483231,0.00331425) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.553669,-0.0103482) , 
1, 1.51968, 1, 0, 0.500329,-7.92478e-05) , 
23, 0.047619, 1, 0, 0.5,-5.92109e-06)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0912406,0.0113125) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.736465,-0.00931004) , 
10, 0.428571, 1, 0, 0.485598,-0.000296538) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.109692,-0.0292817) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.909188,0.0462678) , 
8, 0.701742, 1, 0, 0.609483,0.00223222) , 
1, 1.89931, 1, 0, 0.5,-2.56047e-06)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561526,0.000405217) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305601,0.0696395) , 
3, 0.061844, 1, 0, 0.558116,0.000222608) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0891684,-0.0794699) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00222327,-0.0369369) , 
13, 0.238085, 1, 0, 0.0140035,-0.001838) , 
4, 13.073, 1, 0, 0.5,2.51726e-06)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0603705,0.0333153) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.700711,-0.00246043) , 
18, 0.52381, 1, 0, 0.583059,0.000266914) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0222227,-0.0556626) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.254939,0.0441833) , 
10, 0.445996, 1, 0, 0.0434415,-0.00146985) , 
11, 18.6667, 1, 0, 0.5,-4.13653e-07)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.845655,-0.00525512) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.222388,0.0102262) , 
11, 10.6667, 1, 0, 0.56403,0.000245557) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.00790619,-0.0959623) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.150084,0.0724013) , 
10, 0.472322, 1, 0, 0.0201769,-0.00189781) , 
13, 0.809515, 1, 0, 0.5,-6.78978e-06)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.214618,-0.0470782) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.044451,-0.00501425) , 
9, 0.333333, 1, 0, 0.0513774,-0.000786295) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.205079,-0.0405797) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.855631,0.0116727) , 
8, 0.655347, 1, 0, 0.794314,0.000492526) , 
8, 0.619048, 1, 0, 0.5,-1.40782e-05)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.786191,-0.0355879) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0726832,0.0161488) , 
13, 0.095237, 1, 0, 0.146479,0.000728035) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.890708,-0.0136409) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.146325,0.104979) , 
2, 0.0166457, 1, 0, 0.865815,-0.000767642) , 
10, 0.52381, 1, 0, 0.5,-7.02202e-06)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.538381,-6.41431e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.130836,0.0903476) , 
3, 0.0408029, 1, 0, 0.529563,0.000170892) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.31963,-0.0733906) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0194622,0.0643085) , 
12, 0.76153, 1, 0, 0.0920191,-0.00240027) , 
3, 0.0476117, 1, 0, 0.5,-2.83156e-06)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.856754,-0.000487119) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.101564,0.0440728) , 
13, 0.66664, 1, 0, 0.794255,0.000568543) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0476726,-0.0564801) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.023053,0.0236616) , 
4, 5.23713, 1, 0, 0.0317656,-0.00091266) , 
12, 0.618799, 1, 0, 0.5,-3.07384e-06)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.274851,-0.0189762) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0119324,0.000532995) , 
12, 0.2856, 1, 0, 0.0513774,-0.000964782) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477046,0.0191592) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.916994,-0.00747397) , 
10, 0.566484, 1, 0, 0.794314,0.000613971) , 
8, 0.619048, 1, 0, 0.5,-1.1451e-05)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.538903,0.000279898) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0440867,0.0847473) , 
2, 0.0261047, 1, 0, 0.528118,0.000141536) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0237753,-0.134796) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.253474) , 
12, 0.904283, 1, 0, 0.00599038,-0.00258363) , 
4, 18.3012, 1, 0, 0.5,-5.2223e-06)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.653145,-0.0123251) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0460905,0.0129758) , 
12, 0.2856, 1, 0, 0.227385,-0.000461631) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.98849,0.0355355) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.720921,-0.0522972) , 
12, 0.522976, 1, 0, 0.978149,0.000783801) , 
8, 0.809524, 1, 0, 0.5,-9.39376e-06)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0812606,0.150505) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.923014,-0.038406) , 
5, 0.572806, 1, 0, 0.842864,-0.000865331) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.17606,-0.00660924) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.944774,0.0513527) , 
8, 0.766642, 1, 0, 0.325462,0.000445826) , 
7, 0.0531747, 1, 0, 0.5,3.527e-06)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.733049,-0.0111238) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.175104,0.00597654) , 
11, 10.6667, 1, 0, 0.386433,-0.000283486) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.992037,-0.0232415) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.996756,0.172936) , 
0, 33.6154, 1, 0, 0.9941,0.00131781) , 
8, 0.904762, 1, 0, 0.5,1.57811e-05)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.884604,-0.0044914) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.09388,0.0103212) , 
13, 0.23128, 1, 0, 0.56403,0.000250093) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0170591,-0.0166188) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.049992,-0.16842) , 
18, 0.524053, 1, 0, 0.0201769,-0.00162997) , 
13, 0.809515, 1, 0, 0.5,2.87457e-05)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.711007,0.00500224) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.29565,-0.0248043) , 
3, 0.0333138, 1, 0, 0.688594,0.000372023) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0277685,0.117137) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0034563,-0.0886633) , 
12, 0.870415, 1, 0, 0.00457384,-0.000936755) , 
12, 0.856799, 1, 0, 0.5,1.11747e-05)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499281,0.000554496) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.671438,-0.0252829) , 
1, 2.25543, 1, 0, 0.504291,-6.4951e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.108274,0.0527471) , 
3, 0.0857009, 1, 0, 0.5,-6.59703e-06)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647294,-0.00713063) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.134749,0.0132417) , 
3, 0.00952131, 1, 0, 0.485598,-0.000212193) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.683021,0.0257929) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.075079,-0.155503) , 
2, 0.0118881, 1, 0, 0.609483,0.00158645) , 
1, 1.89931, 1, 0, 0.5,-3.09424e-06)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.710739,-0.000267993) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.832909,0.124384) , 
1, 2.1224, 1, 0, 0.715024,0.0005143) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.822285,-0.0304177) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.127458,0.00504921) , 
11, 8, 1, 0, 0.269837,-0.00055628) , 
3, 0.00476123, 1, 0, 0.5,-2.78638e-06)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.272327,0.00483912) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0987223,-0.0540606) , 
0, 32.7436, 1, 0, 0.227385,-0.000471388) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.910729,-0.0806499) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.983491,0.039027) , 
8, 0.827671, 1, 0, 0.978149,0.000836919) , 
8, 0.809524, 1, 0, 0.5,3.68037e-06)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459536,-0.000528609) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.882653,0.061535) , 
6, 7.19799, 1, 0, 0.472769,0.00014336) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.98423,-0.302409) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.999732,0.229558) , 
0, 27.8236, 1, 0, 0.992581,-0.00235605) , 
10, 0.904762, 1, 0, 0.5,1.24266e-05)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0273751,-0.0337429) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.14289,0.0482477) , 
8, 0.584432, 1, 0, 0.0409807,-0.000753397) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.779283,-0.00956605) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.578998,0.0299331) , 
7, 0.0981827, 1, 0, 0.745554,0.000456243) , 
5, 0.540756, 1, 0, 0.5,3.46656e-05)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.750632,-0.0316163) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208012,-0.000966899) , 
12, 0.0475999, 1, 0, 0.227385,-0.000470551) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.985364,0.047353) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.956944,-0.0286488) , 
17, 1.00824, 1, 0, 0.978149,0.00086517) , 
8, 0.809524, 1, 0, 0.5,1.44712e-05)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.955118,-0.00952912) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.232753,0.0877121) , 
15, 6.31618, 1, 0, 0.913929,0.000783543) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0631559,-0.023862) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.746981,0.0163863) , 
8, 0.679631, 1, 0, 0.269193,-0.000408598) , 
12, 0.1428, 1, 0, 0.5,1.8173e-05)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.265085,0.0425132) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00849609,-0.0301859) , 
12, 0.2856, 1, 0, 0.0444897,0.00124937) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.650013,-0.0739043) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.664564,-0.00153361) , 
27, 0.52381, 1, 0, 0.664227,-0.00044772) , 
18, 0.52381, 1, 0, 0.5,1.99947e-06)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485814,0.0407332) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.566966,-0.0894286) , 
1, 1.53285, 1, 0, 0.499171,0.00171756) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.852981,0.00711166) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0565347,-0.0159205) , 
13, 0.285711, 1, 0, 0.500097,-0.000201201) , 
27, 0.714286, 1, 0, 0.5,-9.90051e-07)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.823594,0.0194185) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.3802,-0.0202524) , 
17, 1.23708, 1, 0, 0.617055,-0.000312766) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.288676,0.0636572) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0331017,-0.0106216) , 
11, 11.4762, 1, 0, 0.0603899,0.0011787) , 
17, 6.49522, 1, 0, 0.5,8.5781e-07)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.84005,-0.0143843) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.594615,0.0559695) , 
7, 0.131331, 1, 0, 0.831217,-0.000830337) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.187176,-0.036418) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.171824,0.0232176) , 
7, 0.0801645, 1, 0, 0.177521,0.000815203) , 
11, 10.6667, 1, 0, 0.5,3.42971e-06)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0827404,-0.00613392) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.905831,0.0142832) , 
5, 0.665795, 1, 0, 0.437227,0.000304697) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.970667,0.0706553) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.5306,-0.0475748) , 
9, 0.380952, 1, 0, 0.765419,-0.00127321) , 
6, 4.04867, 1, 0, 0.5,2.89159e-06)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0649679,-0.00520851) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.415327,0.0264994) , 
5, 0.614121, 1, 0, 0.120402,0.000739665) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.948296,-0.0223882) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.798944,0.0679478) , 
11, 13.8571, 1, 0, 0.940855,-0.000835736) , 
5, 0.694832, 1, 0, 0.5,1.0776e-05)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0371465,-0.00917952) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.180072,0.0710027) , 
8, 0.58356, 1, 0, 0.0543099,0.000912379) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.746296,-0.000977791) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.669045,-0.0339107) , 
7, 0.128204, 1, 0, 0.74276,-0.000475259) , 
18, 0.571429, 1, 0, 0.5,1.40479e-05)    );
  // itree = 125
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.284583,0.0444527) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00989187,-0.00858545) , 
12, 0.238, 1, 0, 0.0407433,0.00143761) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0933704,-0.0195241) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.862729,0.00642279) , 
8, 0.659395, 1, 0, 0.592068,-0.000280674) , 
18, 0.476191, 1, 0, 0.5,6.27098e-06)    );
  // itree = 126
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.958231,-0.0167841) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.232589,0.0295519) , 
12, 0.571126, 1, 0, 0.880691,-0.000613118) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.211276,0.0161053) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00299987,-0.0814573) , 
12, 0.713999, 1, 0, 0.0730445,0.000690307) , 
13, 0.238093, 1, 0, 0.5,1.26313e-06)    );
  // itree = 127
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.623654,-0.0516992) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0614833,0.0228247) , 
9, 0.238095, 1, 0, 0.0955162,0.000729086) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.11251,-0.0399636) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.845327,0.00367476) , 
5, 0.561477, 1, 0, 0.744494,-0.000454985) , 
10, 0.428571, 1, 0, 0.5,-8.90146e-06)    );
  // itree = 128
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0696642,-0.00187436) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.458247,0.0429978) , 
10, 0.558322, 1, 0, 0.0967083,0.000616358) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0931087,-0.160683) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.893936,-0.00164794) , 
8, 0.663916, 1, 0, 0.877814,-0.000589813) , 
18, 0.666667, 1, 0, 0.5,-6.39871e-06)    );
  // itree = 129
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.186731,0.0153823) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0163546,-0.0759899) , 
9, 0.809524, 1, 0, 0.146479,0.000720903) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.464536,-0.0214179) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.960331,0.00475252) , 
8, 0.749304, 1, 0, 0.865815,-0.000755569) , 
10, 0.52381, 1, 0, 0.5,-4.71591e-06)    );
  // itree = 130
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471693,0.0553443) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0670502,-0.0830223) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.50498,-0.000164308) , 
18, 0.285714, 1, 0, 0.500329,-8.35704e-05) , 
24, -9276.78, 1, 0, 0.5,-8.12336e-06)    );
  // itree = 131
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.212007,0.0221098) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0663775,-0.0211949) , 
0, 21.3719, 1, 0, 0.120402,0.000520023) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.98011,0.00976852) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.627482,-0.0362892) , 
12, 0.285554, 1, 0, 0.940855,-0.000613311) , 
5, 0.694832, 1, 0, 0.5,-4.3355e-06)    );
  // itree = 132
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.40147,-0.0229064) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.974486,0.0136056) , 
5, 0.665795, 1, 0, 0.868551,-0.000864772) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.656414,-0.037082) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0289853,0.0399317) , 
13, 0.095237, 1, 0, 0.0917884,0.000954758) , 
12, 0.2856, 1, 0, 0.5,-1.45787e-06)    );
  // itree = 133
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.112311,0.00121522) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390908,0.0550574) , 
6, 5.5584, 1, 0, 0.120402,0.000551494) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.966479,-0.0186788) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.211136,0.078346) , 
12, 0.761477, 1, 0, 0.940855,-0.000650718) , 
5, 0.694832, 1, 0, 0.5,-4.73239e-06)    );
  // itree = 134
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5825,0.00130125) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0518004,-0.0608248) , 
3, 0.0142819, 1, 0, 0.477323,-0.000457918) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.753538,-0.00763242) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.239092,0.0222735) , 
2, 0.00238005, 1, 0, 0.528852,0.000580542) , 
1, 1.06836, 1, 0, 0.5,-9.04734e-07)    );
  // itree = 135
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.990456,0.0753019) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558835,-0.00767241) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.269932,0.00922722) , 
7, 0.100959, 1, 0, 0.482851,-9.39158e-05) , 
11, 2.66667, 1, 0, 0.5,-2.26265e-06)    );
  // itree = 136
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54105,0.00591204) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.685346,-0.0355836) , 
1, 2.24031, 1, 0, 0.546192,0.000301162) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587134,-0.0740503) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.248443,0.000426436) , 
9, 0.285714, 1, 0, 0.276853,-0.00144688) , 
7, 0.115126, 1, 0, 0.5,1.36865e-06)    );
  // itree = 137
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.677771,-0.00929737) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0554216,0.00711927) , 
12, 0.238, 1, 0, 0.227385,-0.000361774) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.991106,0.0492826) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.904802,-0.0288716) , 
2, 0.00233147, 1, 0, 0.978149,0.000641091) , 
8, 0.809524, 1, 0, 0.5,2.38333e-06)    );
  // itree = 138
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0223566,-0.0518339) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.19565,0.0141457) , 
8, 0.506924, 1, 0, 0.146479,0.000544254) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.910509,-0.0128938) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.205272,0.0487889) , 
2, 0.00951192, 1, 0, 0.865815,-0.000539058) , 
10, 0.52381, 1, 0, 0.5,1.18555e-05)    );
  // itree = 139
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.133392,0.0888406) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0131345,-0.0563942) , 
3, 0.00476115, 1, 0, 0.042124,0.00180375) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588565,-0.00740595) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.341164,0.0109174) , 
7, 0.109517, 1, 0, 0.545951,-0.000178179) , 
18, 0.428572, 1, 0, 0.5,2.58079e-06)    );
  // itree = 140
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.635987,0.00645907) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0310037,-0.0463689) , 
2, 0.0119027, 1, 0, 0.546192,0.000260784) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0400919,-0.0924574) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344331,0.00319244) , 
5, 0.411226, 1, 0, 0.276853,-0.00127665) , 
7, 0.115126, 1, 0, 0.5,-2.88853e-06)    );
  // itree = 141
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.225427,0.0519171) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00426763,-0.0338805) , 
12, 0.428399, 1, 0, 0.042124,0.00205688) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.216287,-0.00787219) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.969019,0.0156351) , 
8, 0.783001, 1, 0, 0.545951,-0.000215199) , 
18, 0.428572, 1, 0, 0.5,-7.97724e-06)    );
  // itree = 142
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555478,-0.0150817) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.651543,0.0116283) , 
0, 20.9578, 1, 0, 0.617055,-0.000305368) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0489023,-0.0105941) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.13717,0.0835113) , 
7, 0.129024, 1, 0, 0.0603899,0.00112759) , 
17, 6.49522, 1, 0, 0.5,-4.04822e-06)    );
  // itree = 143
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.61451,-0.00614942) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.789136,0.0482953) , 
1, 2.1224, 1, 0, 0.622443,-0.000333786) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0121322,-0.0441645) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45643,0.0289271) , 
5, 0.572806, 1, 0, 0.149349,0.000940506) , 
3, 0.0142836, 1, 0, 0.5,-3.98354e-06)    );
  // itree = 144
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.212007,0.0177928) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0663775,-0.0141357) , 
0, 21.3719, 1, 0, 0.120402,0.000569954) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.983049,0.0105468) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.714162,-0.0289829) , 
12, 0.190369, 1, 0, 0.940855,-0.000667258) , 
5, 0.694832, 1, 0, 0.5,-2.46545e-06)    );
  // itree = 145
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.855848,-0.0142769) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.378804,0.0528331) , 
17, 4.74865, 1, 0, 0.831217,-0.000538563) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.83547,0.0411478) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0810961,-0.00315027) , 
13, 0.095237, 1, 0, 0.177521,0.000525255) , 
11, 10.6667, 1, 0, 0.5,4.5547e-07)    );
  // itree = 146
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511124,9.86187e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.689221,-0.0231209) , 
1, 2.25543, 1, 0, 0.516077,-9.73041e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.317387,0.0604766) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00223138,-0.191032) , 
15, 3.58798, 1, 0, 0.106175,0.00253452) , 
3, 0.0618951, 1, 0, 0.5,5.92268e-06)    );
  // itree = 147
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952183,0.0112532) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.346391,-0.0878179) , 
11, 9.14286, 1, 0, 0.842864,-0.000703114) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498128,0.0143971) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.151301,-0.0149555) , 
9, 0.666667, 1, 0, 0.325462,0.000357096) , 
7, 0.0531747, 1, 0, 0.5,-5.50051e-07)    );
  // itree = 148
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.30455,0.0601229) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.89955,-0.00918648) , 
18, 0.52381, 1, 0, 0.880691,-0.000500033) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.327645,0.0420864) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0610991,0.000781316) , 
13, 0.274386, 1, 0, 0.0730445,0.000563891) , 
13, 0.238093, 1, 0, 0.5,1.45686e-06)    );
  // itree = 149
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.797218,0.00418878) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0310768,-0.0147621) , 
12, 0.618799, 1, 0, 0.503735,9.55452e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62731,-0.0467109) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0546738,0.0978794) , 
12, 0.618673, 1, 0, 0.333713,-0.00413835) , 
7, 0.177078, 1, 0, 0.5,2.52487e-06)    );
   return;
};
 
// Clean up
inline void ReadShrinkage .5::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadShrinkage .5::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
