// Class: ReadNCuts 100
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::NCuts 100
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.14/07       [396807]
Creator        : mchristos
Date           : Wed Nov 21 11:39:11 2018
Host           : Linux cmsbuild02.cern.ch 2.6.32-754.3.5.el6.x86_64 #1 SMP Wed Aug 15 08:57:36 CEST 2018 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /cms/mchristos/ANN/FireMVA/2016
Training events: 106990
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "150" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "2.5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "100" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "5" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 27
ElectronPt                    ElectronPt                    ElectronPt                    ElectronPt                                                      'F'    [10.000002861,712.53137207]
abs(ElectronEta)              abs_ElectronEta_              abs(ElectronEta)              abs(ElectronEta)                                                'F'    [2.89801610052e-05,2.49977111816]
ElectronDXY                   ElectronDXY                   ElectronDXY                   ElectronDXY                                                     'F'    [2.20267484252e-08,0.0999909341335]
ElectronDZ                    ElectronDZ                    ElectronDZ                    ElectronDZ                                                      'F'    [4.56618387545e-08,0.199988603592]
ElectronSIP3D                 ElectronSIP3D                 ElectronSIP3D                 ElectronSIP3D                                                   'F'    [0.000830443459563,54.7749519348]
ElectronPtRatio               ElectronPtRatio               ElectronPtRatio               ElectronPtRatio                                                 'F'    [-1,5.81726551056]
ElectronPtRel                 ElectronPtRel                 ElectronPtRel                 ElectronPtRel                                                   'F'    [-1,426.082794189]
ElectronJetLRM                ElectronJetLRM                ElectronJetLRM                ElectronJetLRM                                                  'F'    [-1,0.314764946699]
ElectronJetFD                 ElectronJetFD                 ElectronJetFD                 ElectronJetFD                                                   'F'    [-1,1]
ElectronJetInOutRatio         ElectronJetInOutRatio         ElectronJetInOutRatio         ElectronJetInOutRatio                                           'F'    [-9999,1]
ElectronJetZest               ElectronJetZest               ElectronJetZest               ElectronJetZest                                                 'F'    [-1,1]
ElectronJetNoOfConst          ElectronJetNoOfConst          ElectronJetNoOfConst          ElectronJetNoOfConst                                            'F'    [0,57]
ElectronJetCSV                ElectronJetCSV                ElectronJetCSV                ElectronJetCSV                                                  'F'    [0,0.999967813492]
ElectronRelPFIsoPUCorr        ElectronRelPFIsoPUCorr        ElectronRelPFIsoPUCorr        ElectronRelPFIsoPUCorr                                          'F'    [0,0.99998831749]
ElectronRelTrkIso             ElectronRelTrkIso             ElectronRelTrkIso             ElectronRelTrkIso                                               'F'    [0,543.433166504]
ElectronPFChargedHadronIso    ElectronPFChargedHadronIso    ElectronPFChargedHadronIso    ElectronPFChargedHadronIso                                      'F'    [0,195.12449646]
ElectronPFNeutralHadronIso    ElectronPFNeutralHadronIso    ElectronPFNeutralHadronIso    ElectronPFNeutralHadronIso                                      'F'    [0,84.9326248169]
ElectronPFPhotonIso           ElectronPFPhotonIso           ElectronPFPhotonIso           ElectronPFPhotonIso                                             'F'    [0,509.028747559]
ElectronJetMuonEnergyFraction ElectronJetMuonEnergyFraction ElectronJetMuonEnergyFraction ElectronJetMuonEnergyFraction                                   'F'    [0,0.90521723032]
ElectronJetElectronEnergyFraction ElectronJetElectronEnergyFraction ElectronJetElectronEnergyFraction ElectronJetElectronEnergyFraction                                       'F'    [0,1.00000011921]
ElectronMissingHits           ElectronMissingHits           ElectronMissingHits           ElectronMissingHits                                             'F'    [0,3]
ElectronPassConversionVeto    ElectronPassConversionVeto    ElectronPassConversionVeto    ElectronPassConversionVeto                                      'F'    [1,1]
ElectronEInverseMinusPInverse ElectronEInverseMinusPInverse ElectronEInverseMinusPInverse ElectronEInverseMinusPInverse                                   'F'    [6.3770655423e-09,0.297991424799]
ElectronHoE                   ElectronHoE                   ElectronHoE                   ElectronHoE                                                     'F'    [0,0.355959296227]
ElectronDeltaPhiTrkSC         ElectronDeltaPhiTrkSC         ElectronDeltaPhiTrkSC         ElectronDeltaPhiTrkSC                                           'F'    [-0.227979421616,0.227120369673]
ElectronDeltaEtaTrkSeedSC     ElectronDeltaEtaTrkSeedSC     ElectronDeltaEtaTrkSeedSC     ElectronDeltaEtaTrkSeedSC                                       'F'    [-0.00894999504089,0.00894991494715]
ElectronFull5x5SigmaIEtaIEta  ElectronFull5x5SigmaIEtaIEta  ElectronFull5x5SigmaIEtaIEta  ElectronFull5x5SigmaIEtaIEta                                    'F'    [0,0.0369998216629]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new NCuts 100Node
   
#ifndef NCuts 100Node__def
#define NCuts 100Node__def
   
class NCuts 100Node {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   NCuts 100Node ( NCuts 100Node* left,NCuts 100Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~NCuts 100Node();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   NCuts 100Node* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   NCuts 100Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   NCuts 100Node*   fLeft;     // pointer to the left daughter node
   NCuts 100Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   NCuts 100Node::~NCuts 100Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool NCuts 100Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool NCuts 100Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadNCuts 100 : public IClassifierReader {

 public:

   // constructor
   ReadNCuts 100( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadNCuts 100" ),
        fNvars( 27 ),
        fIsNormalised( false )
   {
      // the training input variables
      const char* inputVars[] = { "ElectronPt", "abs(ElectronEta)", "ElectronDXY", "ElectronDZ", "ElectronSIP3D", "ElectronPtRatio", "ElectronPtRel", "ElectronJetLRM", "ElectronJetFD", "ElectronJetInOutRatio", "ElectronJetZest", "ElectronJetNoOfConst", "ElectronJetCSV", "ElectronRelPFIsoPUCorr", "ElectronRelTrkIso", "ElectronPFChargedHadronIso", "ElectronPFNeutralHadronIso", "ElectronPFPhotonIso", "ElectronJetMuonEnergyFraction", "ElectronJetElectronEnergyFraction", "ElectronMissingHits", "ElectronPassConversionVeto", "ElectronEInverseMinusPInverse", "ElectronHoE", "ElectronDeltaPhiTrkSC", "ElectronDeltaEtaTrkSeedSC", "ElectronFull5x5SigmaIEtaIEta" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;
      fVmin[16] = 0;
      fVmax[16] = 0;
      fVmin[17] = 0;
      fVmax[17] = 0;
      fVmin[18] = 0;
      fVmax[18] = 0;
      fVmin[19] = 0;
      fVmax[19] = 0;
      fVmin[20] = 0;
      fVmax[20] = 0;
      fVmin[21] = 0;
      fVmax[21] = 0;
      fVmin[22] = 0;
      fVmax[22] = 0;
      fVmin[23] = 0;
      fVmax[23] = 0;
      fVmin[24] = 0;
      fVmax[24] = 0;
      fVmin[25] = 0;
      fVmax[25] = 0;
      fVmin[26] = 0;
      fVmax[26] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';
      fType[19] = 'F';
      fType[20] = 'F';
      fType[21] = 'F';
      fType[22] = 'F';
      fType[23] = 'F';
      fType[24] = 'F';
      fType[25] = 'F';
      fType[26] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadNCuts 100() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[27];
   double fVmax[27];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[27];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<NCuts 100Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadNCuts 100::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      NCuts 100Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(NCuts 100Node*)current->GetRight();
         else current=(NCuts 100Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadNCuts 100::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469519,-0.0609625) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.276549,-0.446902) , 
26, 0.00952471, 1, 0, 0.323861,-0.176139) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.633108,0.266216) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.808135,0.616269) , 
12, 0.839212, 1, 0, 0.749326,0.249326) , 
12, 0.603941, 1, 0, 0.5,-1.1375e-16)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490503,-0.0684819) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.68273,0.298901) , 
0, 16.9559, 1, 0, 0.618404,0.0716493) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.304752,-0.277013) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.476637,-0.00524627) , 
11, 13.5446, 1, 0, 0.39297,-0.0578418) , 
22, 0.00590083, 1, 0, 0.5,0.00363729)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.299186,-0.34594) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.261763,-0.153348) , 
22, 0.005701, 1, 0, 0.273497,-0.0856901) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.297039,-0.114198) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.660671,0.132614) , 
12, 0.188047, 1, 0, 0.563992,0.0240723) , 
19, 0.00990099, 1, 0, 0.5,-0.000107014)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.443457,-0.0736068) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.725783,0.262276) , 
18, 0.0717004, 1, 0, 0.455167,-0.021753) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.401901,0.0270102) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.712163,0.191709) , 
4, 1.62778, 1, 0, 0.599313,0.0457394) , 
17, 5.03989, 1, 0, 0.5,-0.000761169)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.301298,0.0196741) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.504723,0.318761) , 
4, 4.33937, 1, 0, 0.323861,0.0209342) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.689609,-0.185072) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.836713,0.0833789) , 
0, 26.1643, 1, 0, 0.749326,-0.0281752) , 
12, 0.603941, 1, 0, 0.5,0.000603321)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477257,0.108106) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.686075,0.317503) , 
6, 2.0504, 1, 0, 0.576291,0.0796038) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523483,0.0102503) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.325663,-0.147774) , 
22, 0.0295041, 1, 0, 0.493948,-0.00526388) , 
5, 0.349954, 1, 0, 0.5,0.000973899)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.415093,-0.309884) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.329122,-0.069467) , 
26, 0.00952429, 1, 0, 0.341763,-0.0395331) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589982,0.0601082) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.351524,-0.0928395) , 
25, 0.00269609, 1, 0, 0.53555,0.0087779) , 
25, -0.00274706, 1, 0, 0.5,-8.47414e-05)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469121,-0.00779574) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.389106,-0.0913313) , 
5, 0.560411, 1, 0, 0.429444,-0.017669) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.261828,-0.0862011) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.62248,0.0746323) , 
12, 0.13856, 1, 0, 0.56454,0.0158618) , 
15, 5.79578, 1, 0, 0.5,-0.000157046)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.359568,-0.111798) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505558,0.00539599) , 
6, 0.925869, 1, 0, 0.47537,-0.00664716) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.395914,0.114727) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.797613,-0.0189578) , 
12, 0.60373, 1, 0, 0.579884,0.0211797) , 
6, 3.22854, 1, 0, 0.5,-8.94258e-05)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.425229,-0.022911) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.613249,0.0452541) , 
2, 0.00594008, 1, 0, 0.513659,0.00284277) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.46191,-0.117763) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.300449,-0.0334877) , 
1, 1.68269, 1, 0, 0.381904,-0.0271184) , 
20, 0.029703, 1, 0, 0.5,-0.000263263)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.267385,0.122797) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543186,0.0209416) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.488736,-0.0276406) , 
5, 0.49446, 1, 0, 0.512865,-0.00207427) , 
12, 0.00990067, 1, 0, 0.5,9.72085e-06)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.400152,-0.0251429) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500723,0.0512505) , 
17, 1.54686, 1, 0, 0.455167,0.00596931) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.696833,0.00794536) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.517048,-0.0761899) , 
1, 0.940526, 1, 0, 0.599313,-0.0135803) , 
17, 5.03989, 1, 0, 0.5,-0.000111098)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.298061,-0.00521349) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444026,0.120844) , 
12, 0.400623, 1, 0, 0.323861,0.00675259) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.612598,-0.0942907) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.795171,-0.00013191) , 
0, 15.3882, 1, 0, 0.749326,-0.00961765) , 
12, 0.603941, 1, 0, 0.5,-2.45561e-05)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.408017,0.0370193) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.796755,-0.0367529) , 
12, 0.841222, 1, 0, 0.521975,0.00672186) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.367139,-0.0520636) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.842919,0.081211) , 
12, 0.88116, 1, 0, 0.464993,-0.0106967) , 
23, 0.0634383, 1, 0, 0.5,4.43359e-06)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.446739,-0.0110299) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.613767,0.0374441) , 
6, 2.2264, 1, 0, 0.517,0.00305228) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.21847,-0.153633) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.443398,-0.0275333) , 
4, 0.995617, 1, 0, 0.38171,-0.021138) , 
5, 0.687442, 1, 0, 0.5,1.26107e-05)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.392427,0.0159891) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.576687,-0.0238943) , 
11, 13.5446, 1, 0, 0.488915,-0.0017554) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55847,0.152386) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.851155,-0.00013583) , 
12, 0.841128, 1, 0, 0.698246,0.0296911) , 
18, 0.0448127, 1, 0, 0.5,-9.0131e-05)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.296954,-0.108287) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.513783,0.00760393) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.316814,-0.0992398) , 
22, 0.0796611, 1, 0, 0.507685,0.00141452) , 
13, 0.00990087, 1, 0, 0.5,4.26474e-06)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.518829,-0.0771152) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.704063,0.0332022) , 
11, 13.5446, 1, 0, 0.618404,-0.00726519) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.283431,-0.0121916) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.747066,0.112098) , 
12, 0.772252, 1, 0, 0.39297,0.00644547) , 
22, 0.00590083, 1, 0, 0.5,-6.40033e-05)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.374108,0.00341317) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444529,0.0664405) , 
19, 0.594059, 1, 0, 0.403658,0.010328) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.665851,0.0055862) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439115,-0.0785904) , 
22, 0.0118017, 1, 0, 0.587242,-0.00892535) , 
11, 13.5446, 1, 0, 0.5,0.000224134)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503281,0.0720965) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.356455,-0.000488946) , 
1, 0.569277, 1, 0, 0.384474,0.00503659) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.767589,-0.127176) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.829811,-0.00762177) , 
14, 0.278123, 1, 0, 0.808324,-0.0137173) , 
12, 0.841557, 1, 0, 0.5,-7.50148e-05)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.437578,-0.194365) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.603285,-0.00876687) , 
19, 0.316832, 1, 0, 0.594495,-0.00609039) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.267793,0.0634072) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.634933,-0.0616133) , 
12, 0.603941, 1, 0, 0.365971,0.00913687) , 
1, 1.53452, 1, 0, 0.5,0.00020613)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.322979,-0.0320853) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.498964,0.064129) , 
11, 20.3168, 1, 0, 0.345939,-0.00680055) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.785479,0.0223178) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.694678,0.144637) , 
22, 0.0274713, 1, 0, 0.776499,0.0117849) , 
12, 0.722749, 1, 0, 0.5,-0.000150408)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.401129,0.0312292) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.704729,-0.0210744) , 
4, 4.3511, 1, 0, 0.48685,0.0058328) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475995,-0.0312981) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.805255,0.0614702) , 
4, 9.55788, 1, 0, 0.516728,-0.00734973) , 
16, 0.840917, 1, 0, 0.5,3.09292e-05)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.686178,0.0969927) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482388,-0.0109012) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.551577,0.036251) , 
0, 44.7788, 1, 0, 0.492962,-0.00129125) , 
26, 0.00769303, 1, 0, 0.5,-8.38273e-07)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.402263,-0.0342411) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.892687,0.124743) , 
12, 0.950123, 1, 0, 0.452946,-0.00770346) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.290162,0.0658587) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.600542,-0.00286859) , 
12, 0.188113, 1, 0, 0.527411,0.00452574) , 
7, 0.0804504, 1, 0, 0.5,2.41358e-05)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54753,0.0180865) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.320144,-0.0440133) , 
1, 1.08901, 1, 0, 0.432961,-0.00455526) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.711245,-0.0125595) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438708,0.04061) , 
26, 0.0195162, 1, 0, 0.577931,0.00523493) , 
3, 0.00990047, 1, 0, 0.5,-2.79316e-05)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.340596,-0.133421) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.291542,0.00883987) , 
22, 0.00583702, 1, 0, 0.306152,-0.0123274) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.407767,0.0704155) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.535587,-0.000711379) , 
25, -0.00273629, 1, 0, 0.526089,0.00158778) , 
25, -0.00416487, 1, 0, 0.5,-6.28468e-05)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.441089,0.0425215) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.626951,-0.010678) , 
0, 16.9558, 1, 0, 0.561154,0.00352539) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.438463,-0.116305) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.325039,0.0116752) , 
26, 0.00952471, 1, 0, 0.354268,-0.00863379) , 
22, 0.0147521, 1, 0, 0.5,-6.87929e-05)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.349099,-0.0620081) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.496351,-0.000364388) , 
0, 12.2727, 1, 0, 0.466029,-0.00477656) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.46276,0.0614878) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.78223,-0.0266912) , 
4, 3.71746, 1, 0, 0.579053,0.010986) , 
0, 30.8673, 1, 0, 0.5,-3.89096e-05)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.710431,0.0604343) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.569528,-0.053597) , 
25, 0.00149816, 1, 0, 0.686239,0.0130747) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.419442,-0.0151435) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.759056,0.049072) , 
4, 8.1356, 1, 0, 0.464306,-0.00258136) , 
26, 0.00879204, 1, 0, 0.5,-6.33879e-05)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525212,0.01376) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.630744,0.11497) , 
19, 0.433068, 1, 0, 0.545228,0.0114633) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.616676,-0.0336306) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.371916,0.0141402) , 
22, 0.00590083, 1, 0, 0.488778,-0.00276127) , 
5, 0.417451, 1, 0, 0.5,6.64856e-05)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.542324,0.0658212) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.82655,-0.0703598) , 
12, 0.841222, 1, 0, 0.654715,0.00851221) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.339593,-0.0212321) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.804742,0.0400419) , 
12, 0.871259, 1, 0, 0.428574,-0.00388187) , 
22, 0.00295042, 1, 0, 0.5,3.27711e-05)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.354046,-0.0392198) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457337,0.035896) , 
15, 0.803355, 1, 0, 0.429444,0.0056834) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553879,-0.00671165) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.648639,-0.0885502) , 
2, 0.0267226, 1, 0, 0.56454,-0.00500668) , 
15, 5.79578, 1, 0, 0.5,0.000100357)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.373516,-0.0463642) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502297,0.0184843) , 
14, 0.334624, 1, 0, 0.425784,-0.00695144) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.563112,0.00434263) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354594,0.0466661) , 
22, 0.0295041, 1, 0, 0.5355,0.00333085) , 
25, -0.00115201, 1, 0, 0.5,3.87688e-06)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.25204,-0.0148598) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.537183,0.0354538) , 
4, 1.64015, 1, 0, 0.403658,0.0047614) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.572817,-0.0205605) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.697042,0.0537337) , 
9, 0.836922, 1, 0, 0.587242,-0.00439348) , 
11, 13.5446, 1, 0, 0.5,-4.29435e-05)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492122,0.0597124) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379595,-0.0218395) , 
24, 0.0151332, 1, 0, 0.459998,0.012752) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.433266,-0.0186384) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.589354,0.0124875) , 
0, 22.0459, 1, 0, 0.505522,-0.00174522) , 
10, 0.207921, 1, 0, 0.5,1.31746e-05)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.604235,-0.0328418) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.370514,0.00974683) , 
22, 0.00583193, 1, 0, 0.479448,-0.00317523) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477322,0.038546) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.765919,-0.0341107) , 
12, 0.910543, 1, 0, 0.552264,0.00802848) , 
7, 0.119503, 1, 0, 0.5,-1.29937e-05)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.617891,0.0217673) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.338563,-0.0372954) , 
26, 0.0289695, 1, 0, 0.561154,0.00316113) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.403107,-0.0735481) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.332915,0.00139251) , 
1, 0.841567, 1, 0, 0.354268,-0.00747764) , 
22, 0.0147521, 1, 0, 0.5,1.63742e-05)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.341119,0.028217) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.532252,-0.00329518) , 
25, -0.00274706, 1, 0, 0.496765,0.000821758) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.575505,-0.0633116) , 
23, 0.204412, 1, 0, 0.5,-2.60634e-05)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.319397,0.0522366) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.500256,-0.00431917) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.818512,0.0789146) , 
4, 17.8973, 1, 0, 0.50892,-0.000846482) , 
13, 0.0297026, 1, 0, 0.5,-8.24374e-06)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493573,0.00628364) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.560196,-0.0502701) , 
2, 0.0366304, 1, 0, 0.497076,0.00108772) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.555695,-0.0566289) , 
3, 0.0792034, 1, 0, 0.5,8.17326e-06)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475084,-0.0133886) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.323876,0.0200622) , 
1, 1.85627, 1, 0, 0.437721,-0.0017465) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533782,-0.0351014) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.810526,0.0434843) , 
12, 0.574038, 1, 0, 0.760092,0.00733218) , 
4, 6.50865, 1, 0, 0.5,7.41789e-06)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456999,0.0040247) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499472,0.0517782) , 
0, 58.6903, 1, 0, 0.460837,0.00285773) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.619894,-0.0313137) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.426456,0.0543487) , 
22, 0.0349887, 1, 0, 0.597376,-0.00700137) , 
3, 0.0198009, 1, 0, 0.5,2.98821e-05)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.466888,0.00350575) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.680713,0.107762) , 
17, 12.6737, 1, 0, 0.47537,0.00239755) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673899,0.00225294) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.472103,-0.050596) , 
5, 0.588115, 1, 0, 0.579884,-0.00777079) , 
6, 3.22854, 1, 0, 0.5,1.2568e-06)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.294952,-0.0171912) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.578728,0.026206) , 
4, 1.59788, 1, 0, 0.455167,0.00285296) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.401901,0.0292151) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.712163,-0.0544724) , 
4, 1.62778, 1, 0, 0.599313,-0.0062843) , 
17, 5.03989, 1, 0, 0.5,1.10485e-05)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.267385,0.0474764) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.232142,-0.0739653) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.522483,8.08118e-05) , 
12, 0.0895321, 1, 0, 0.512865,-0.000794294) , 
12, 0.00990067, 1, 0, 0.5,4.16941e-05)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456945,-0.00291491) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.572743,-0.0564448) , 
18, 0.00896255, 1, 0, 0.466029,-0.00240537) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567578,0.00852392) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.699241,0.117281) , 
18, 0.00681596, 1, 0, 0.579053,0.00546865) , 
0, 30.8673, 1, 0, 0.5,-3.8723e-05)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.346126,-0.0225869) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.808944,0.0628102) , 
12, 0.930663, 1, 0, 0.402832,-0.00459156) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.351975,-0.0398132) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.551707,0.00891453) , 
24, -0.047461, 1, 0, 0.538373,0.0018439) , 
25, -0.00150647, 1, 0, 0.5,2.19713e-05)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469519,-0.0490294) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.276549,0.0306361) , 
26, 0.00952471, 1, 0, 0.323861,0.00314095) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.803035,0.0173335) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.683493,-0.0459693) , 
26, 0.00983047, 1, 0, 0.749326,-0.0044377) , 
12, 0.603941, 1, 0, 0.5,3.45054e-06)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.707244,0.0503752) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.485315,-0.00763935) , 
22, 0.000671708, 1, 0, 0.507581,-0.000773211) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.325079,0.0541532) , 
22, 0.0678594, 1, 0, 0.5,-9.39345e-06)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490503,0.0534757) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.68273,-0.0512353) , 
0, 16.9559, 1, 0, 0.618404,-0.00333996) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.318442,-0.036535) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.431463,0.0319759) , 
0, 15.9094, 1, 0, 0.39297,0.00303259) , 
22, 0.00590083, 1, 0, 0.5,7.06458e-06)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533502,0.00700926) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.310312,-0.033639) , 
25, 0.0048737, 1, 0, 0.513885,0.00116326) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.323825,-0.0717706) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.363504,0.00953707) , 
23, 0.0561599, 1, 0, 0.340988,-0.0130663) , 
24, 0.0468828, 1, 0, 0.5,2.05474e-05)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.516046,-0.0206348) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.355626,0.0291196) , 
25, 0.00239242, 1, 0, 0.478345,-0.00296656) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.513766,0.000516115) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.707048,0.160957) , 
14, 0.58219, 1, 0, 0.527437,0.00369083) , 
19, 0.524753, 1, 0, 0.5,-2.98749e-05)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45547,-0.00762795) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.612619,0.0273413) , 
0, 22.0459, 1, 0, 0.531872,0.00274237) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.382679,-0.0230769) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.820456,0.0569409) , 
12, 0.940173, 1, 0, 0.438878,-0.00513216) , 
25, 0.000974708, 1, 0, 0.5,4.34861e-05)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.424308,0.00796281) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.554281,-0.0163231) , 
15, 5.27311, 1, 0, 0.491037,-0.00136648) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.472481,-0.0230742) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59999,0.0522436) , 
14, 0.410668, 1, 0, 0.561294,0.00947332) , 
13, 0.821773, 1, 0, 0.5,1.63492e-05)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496763,0.00624718) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.556685,0.0727062) , 
2, 0.0415804, 1, 0, 0.499522,0.00320974) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.393329,0.00482767) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.790076,-0.0704299) , 
12, 0.860994, 1, 0, 0.500597,-0.00400123) , 
10, 0.386139, 1, 0, 0.5,6.13109e-06)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.637818,0.0408305) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.739042,-0.0208796) , 
2, 0.00841661, 1, 0, 0.680857,0.00544485) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.351261,-0.0123264) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.80385,0.0327226) , 
12, 0.88116, 1, 0, 0.435081,-0.00184038) , 
26, 0.00915837, 1, 0, 0.5,8.39384e-05)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519174,-0.0180946) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305907,0.0367576) , 
22, 0.00582149, 1, 0, 0.403658,0.00333027) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456728,-0.042294) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.61289,-0.00135893) , 
24, -0.0224878, 1, 0, 0.587242,-0.00295306) , 
11, 13.5446, 1, 0, 0.5,3.28724e-05)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514989,-0.0537294) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.296057,-0.000517484) , 
26, 0.00952429, 1, 0, 0.353676,-0.00543516) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543782,0.00241229) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.690542,0.0737202) , 
9, 0.891089, 1, 0, 0.550948,0.00183967) , 
11, 10.1584, 1, 0, 0.5,-3.91424e-05)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.590588,0.00907129) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.373688,-0.00846403) , 
22, 0.00885124, 1, 0, 0.498993,0.000527036) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.534612,-0.0516517) , 
16, 10.9319, 1, 0, 0.5,1.51595e-05)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.437777,-0.00043702) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.539509,0.0540741) , 
7, 0.13252, 1, 0, 0.457103,0.00378256) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.672478,0.0103609) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.428186,-0.0134256) , 
22, 0.00291572, 1, 0, 0.518438,-0.00162652) , 
24, -0.00718843, 1, 0, 0.5,-5.09688e-07)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506872,-0.00631477) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.471392,0.0468683) , 
0, 72.6018, 1, 0, 0.50563,-0.00139446) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.623964,0.0813012) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.443416,8.87854e-05) , 
8, 0.67881, 1, 0, 0.478499,0.00532621) , 
19, 0.643564, 1, 0, 0.5,1.89212e-07)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.251448,-0.0123357) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278009,0.0492552) , 
2, 0.00395893, 1, 0, 0.262112,0.00416651) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.319828,-0.0499741) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.642944,0.00355987) , 
12, 0.268496, 1, 0, 0.596093,-0.00167376) , 
12, 0.188113, 1, 0, 0.5,6.59469e-06)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.180899,-0.0909819) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380763,0.0361545) , 
4, 1.72629, 1, 0, 0.25521,-0.0118256) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.437694,0.0163382) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.583102,-0.00887422) , 
2, 0.00495007, 1, 0, 0.518426,0.000820363) , 
12, 0.0792054, 1, 0, 0.5,-6.4896e-05)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541448,-0.00723366) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.403886,0.0309162) , 
5, 0.708246, 1, 0, 0.528227,-0.00117219) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.240182,-0.0353095) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.39593,0.0461396) , 
2, 0.00494906, 1, 0, 0.338543,0.00629255) , 
22, 0.0295041, 1, 0, 0.5,-6.1345e-05)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.258621,0.00817633) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.538426,-0.0510693) , 
12, 0.385963, 1, 0, 0.381513,-0.00718219) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524962,0.00211346) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.532884,0.0583901) , 
19, 0.722772, 1, 0, 0.525291,0.0015018) , 
13, 0.168315, 1, 0, 0.5,-2.57196e-05)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.497842,0.000486521) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.285954,-0.0611003) , 
22, 0.0145538, 1, 0, 0.433899,-0.00578007) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.518493,0.00800455) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.592357,-0.0694067) , 
0, 52.6964, 1, 0, 0.520957,0.00183888) , 
7, 0.0674329, 1, 0, 0.5,4.77576e-06)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.639623,0.00332133) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.455182,-0.0448962) , 
26, 0.0101782, 1, 0, 0.597553,-0.00255021) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.474298,0.0756363) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.356488,0.00387867) , 
26, 0.0228887, 1, 0, 0.366101,0.0034413) , 
1, 1.50977, 1, 0, 0.5,-2.48914e-05)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.663441,-0.0128643) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.408338,0.00970823) , 
26, 0.00952471, 1, 0, 0.498333,0.000680678) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.531954,-0.0372964) , 
2, 0.0405904, 1, 0, 0.5,-1.34496e-05)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.648238,0.0213851) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.451698,-0.038691) , 
25, 0.00200674, 1, 0, 0.62237,0.00421259) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.427803,-0.0161379) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.325344,0.0268636) , 
22, 0.0256436, 1, 0, 0.409851,-0.00310088) , 
1, 1.06428, 1, 0, 0.5,1.43723e-06)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.565477,5.14191e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.318971,-0.0430629) , 
26, 0.0311385, 1, 0, 0.53439,-0.00186985) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.429629,-0.0459229) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.342789,0.0371581) , 
26, 0.00962411, 1, 0, 0.356934,0.00775422) , 
25, 0.00256975, 1, 0, 0.5,-4.74049e-06)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482627,-0.0109457) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.425322,0.0101246) , 
23, 0.0669626, 1, 0, 0.461321,-0.00115711) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.75857,0.058203) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.803073,-0.0131603) , 
16, 0.840917, 1, 0, 0.779547,0.00803023) , 
4, 9.22024, 1, 0, 0.5,-4.04296e-05)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.621739,0.0374008) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.548135,-0.0680451) , 
5, 0.296482, 1, 0, 0.576291,-0.00958253) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.374938,0.00793776) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.802229,-0.0165283) , 
12, 0.831656, 1, 0, 0.493948,0.000784747) , 
5, 0.349954, 1, 0, 0.5,2.27514e-05)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674657,0.0134306) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.426702,-0.0064095) , 
26, 0.00915837, 1, 0, 0.491693,-0.000482158) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.77343,0.0564244) , 
18, 0.098588, 1, 0, 0.5,1.15419e-05)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.369401,-0.0247229) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.3157,0.0591206) , 
26, 0.0260086, 1, 0, 0.341763,0.00600822) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490549,-0.0457628) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.539043,-0.00061501) , 
25, -0.00193636, 1, 0, 0.53555,-0.00133515) , 
25, -0.00274706, 1, 0, 0.5,1.199e-05)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.292319,-0.0238853) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.577175,0.00906425) , 
19, 0.277228, 1, 0, 0.519254,0.000870556) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.300339,0.0535559) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372642,-0.0898385) , 
19, 0.029703, 1, 0, 0.335443,-0.00781749) , 
1, 2.10377, 1, 0, 0.5,-3.95181e-05)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72981,-0.0245078) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438463,0.0232064) , 
22, 0.0147521, 1, 0, 0.665452,-0.00407941) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.409938,0.00325301) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.476453,0.0560323) , 
0, 86.5133, 1, 0, 0.412913,0.00205982) , 
26, 0.00952471, 1, 0, 0.5,-5.72556e-05)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515986,0.00526855) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.490622,-0.0420571) , 
0, 79.5576, 1, 0, 0.514872,0.000981834) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.17531,-0.0825988) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.48163,0.00553996) , 
12, 0.286998, 1, 0, 0.325261,-0.0113916) , 
22, 0.0472066, 1, 0, 0.5,1.13383e-05)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.434674,-0.0149074) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.541476,0.006979) , 
19, 0.475248, 1, 0, 0.492086,-0.00103103) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.606806,0.0893562) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.528158,-0.0047218) , 
23, 0.0528559, 1, 0, 0.546285,0.00573178) , 
16, 4.20459, 1, 0, 0.5,-4.3531e-05)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468254,0.0716854) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.535957,0.011263) , 
17, 1.73835, 1, 0, 0.522413,0.00819166) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476398,-0.00245262) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.666345,-0.0398624) , 
11, 20.4059, 1, 0, 0.494709,-0.0019277) , 
8, 0.465347, 1, 0, 0.5,4.93729e-06)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448439,-0.00887494) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.557526,0.0929442) , 
17, 12.3013, 1, 0, 0.452345,-0.00197827) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.420506,-0.0298038) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.658399,0.0237975) , 
25, -0.0038118, 1, 0, 0.629401,0.00537563) , 
11, 17.4951, 1, 0, 0.5,1.04796e-06)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.415725,-0.00428055) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.378258,0.0339887) , 
24, 0.00559348, 1, 0, 0.403658,0.00269942) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522042,-0.0269455) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.610741,0.000124892) , 
11, 15.2772, 1, 0, 0.587242,-0.00243521) , 
11, 13.5446, 1, 0, 0.5,4.83945e-06)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.270033,-0.0310487) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.512225,0.00309311) , 
11, 6.20792, 1, 0, 0.498716,0.000444797) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.536985,-0.0420872) , 
13, 0.950484, 1, 0, 0.5,-1.19646e-05)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.370892,0.0144364) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.545521,-0.0022957) , 
25, -0.00221538, 1, 0, 0.508089,0.000436418) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313758,-0.0301966) , 
24, 0.0739185, 1, 0, 0.5,-4.77247e-06)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.347729,-0.0164855) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.485813,0.0127904) , 
3, 0.00396022, 1, 0, 0.446021,0.00165632) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49553,0.0162186) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.635003,-0.0254273) , 
2, 0.00395892, 1, 0, 0.578941,-0.00243877) , 
15, 7.7277, 1, 0, 0.5,-6.70862e-06)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.438464,0.00279077) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.561582,-0.0221938) , 
3, 0.0198009, 1, 0, 0.474191,-0.00163177) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493574,-0.00327782) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.677367,0.0403714) , 
2, 0.00989727, 1, 0, 0.560039,0.00380209) , 
13, 0.623755, 1, 0, 0.5,1.84949e-06)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.414734,0.00503561) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390483,-0.044689) , 
16, 1.55884, 1, 0, 0.406165,-0.00422376) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.52083,-0.000177764) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.580818,0.0366112) , 
0, 51.7347, 1, 0, 0.52692,0.0012293) , 
2, 0.00198004, 1, 0, 0.5,1.36322e-05)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.21966,-0.0410017) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.349193,0.0633858) , 
14, 0.18356, 1, 0, 0.297519,0.00786041) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.694617,0.00940076) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.452806,-0.00618988) , 
26, 0.00915832, 1, 0, 0.518732,-0.000736565) , 
4, 0.543148, 1, 0, 0.5,-8.57512e-06)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.223667,-0.0237483) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.46379,0.0150074) , 
19, 0.306931, 1, 0, 0.410717,0.00284833) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507366,0.0303) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.551603,-0.00855204) , 
13, 0.247587, 1, 0, 0.547519,-0.00155342) , 
15, 3.86385, 1, 0, 0.5,-2.44454e-05)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535136,0.000331669) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305745,-0.0301005) , 
25, 0.0048737, 1, 0, 0.515756,-0.000746395) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.189052,-0.022285) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.398549,0.0465586) , 
12, 0.188009, 1, 0, 0.32186,0.00835277) , 
26, 0.0337028, 1, 0, 0.5,-6.98275e-06)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499652,-0.0117901) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.634457,0.0208856) , 
14, 0.488662, 1, 0, 0.53439,-0.00131073) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.289298,0.00237973) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.785043,0.103569) , 
12, 0.870897, 1, 0, 0.356934,0.00536669) , 
25, 0.00256975, 1, 0, 0.5,-1.66724e-05)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.281983,0.0153291) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47581,-0.0577537) , 
4, 4.33937, 1, 0, 0.298968,0.00259641) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.690655,-0.00356064) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.663645,-0.0774434) , 
0, 70.2297, 1, 0, 0.689312,-0.00236299) , 
12, 0.405928, 1, 0, 0.5,4.22593e-05)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.437615,-0.00558494) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440571,0.0351265) , 
0, 86.5133, 1, 0, 0.437721,-0.00135232) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.80049,-0.0420471) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.749109,0.033211) , 
1, 0.395975, 1, 0, 0.760092,0.0056325) , 
4, 6.50865, 1, 0, 0.5,-2.91308e-06)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477257,0.0235663) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.686075,-0.080697) , 
6, 2.0504, 1, 0, 0.576291,-0.00792983) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.438242,0.00510562) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.82689,-0.0242612) , 
12, 0.950464, 1, 0, 0.493948,0.000654593) , 
5, 0.349954, 1, 0, 0.5,2.36371e-05)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418802,-0.0350825) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.494619,0.000198275) , 
10, 0.168317, 1, 0, 0.491233,-0.000500954) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.682631,0.0342604) , 
11, 25.396, 1, 0, 0.5,2.85938e-05)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.288686,0.00240638) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.667087,-0.0340084) , 
12, 0.603633, 1, 0, 0.364476,-0.00170781) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.705485,0.0127457) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.503102,-0.0388049) , 
22, 0.0320729, 1, 0, 0.686394,0.00234971) , 
4, 2.71242, 1, 0, 0.5,3.6235e-07)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.317943,-0.00854661) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.72167,0.00669453) , 
12, 0.504934, 1, 0, 0.508266,-0.000616354) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.324986,0.0418914) , 
22, 0.064909, 1, 0, 0.5,1.67104e-05)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.591548,-0.00106003) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.314274,-0.0658402) , 
25, 0.00449633, 1, 0, 0.575575,-0.00153415) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.340097,0.019966) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.441791,-0.0314977) , 
6, 3.22854, 1, 0, 0.361697,0.00278227) , 
1, 1.63352, 1, 0, 0.5,-8.91679e-06)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564069,0.00402275) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.330812,-0.0225303) , 
26, 0.0282078, 1, 0, 0.512375,-0.000695565) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.289984,0.0858663) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.334864,-0.033469) , 
19, 0.356436, 1, 0, 0.309266,0.0102805) , 
25, 0.00593706, 1, 0, 0.5,-2.68085e-05)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.628922,-0.0242339) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413653,0.00593688) , 
22, 0.00295042, 1, 0, 0.481211,-0.00120522) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511427,-0.0175435) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.613475,0.0388045) , 
9, 0.663366, 1, 0, 0.569824,0.00427996) , 
0, 37.823, 1, 0, 0.5,-4.21797e-05)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.386535,0.012862) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.435558,-0.0688725) , 
13, 0.296889, 1, 0, 0.405235,-0.00543576) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.380795,0.0553309) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.521093,-1.28026e-05) , 
9, 0.227723, 1, 0, 0.514782,0.000860551) , 
7, 0.0544155, 1, 0, 0.5,1.09199e-05)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.341671,-0.000250495) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.62461,-0.0430049) , 
4, 5.1702, 1, 0, 0.403581,-0.00359641) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532285,0.0013808) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.506817,0.0620798) , 
10, 0.584158, 1, 0, 0.531401,0.00114545) , 
13, 0.22772, 1, 0, 0.5,-1.94674e-05)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461905,0.00914737) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.550207,-0.0046484) , 
13, 0.435638, 1, 0, 0.509568,0.000656404) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.424162,-0.0476783) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344169,0.00846796) , 
10, 0.674554, 1, 0, 0.387168,-0.00764853) , 
10, 0.60396, 1, 0, 0.5,7.18313e-06)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488988,-0.000255456) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.539167,-0.0328744) , 
7, 0.147084, 1, 0, 0.491305,-0.000640405) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.645543,0.0458072) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499055,-0.0235584) , 
1, 1.01389, 1, 0, 0.586694,0.00634003) , 
7, 0.158555, 1, 0, 0.5,-4.11087e-06)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.452871,0.0288581) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.655548,0.00778315) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.428977,-0.00484328) , 
22, 0.00295042, 1, 0, 0.501401,-0.000302292) , 
10, 0.148515, 1, 0, 0.5,9.39159e-06)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.454932,-0.0264877) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.797032,0.00789054) , 
12, 0.524552, 1, 0, 0.665452,-0.00261365) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.584709,0.047207) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.399191,0.00077304) , 
26, 0.00979685, 1, 0, 0.412913,0.00137475) , 
26, 0.00952471, 1, 0, 0.5,-6.24703e-07)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54348,0.0349865) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404527,0.000259495) , 
1, 0.198028, 1, 0, 0.414125,0.000939285) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.658991,-0.092218) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.84284,0.00478892) , 
0, 12.914, 1, 0, 0.819677,-0.00348609) , 
12, 0.900961, 1, 0, 0.5,2.21395e-06)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.563241,-0.0388922) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.725289,0.0148068) , 
11, 15.2475, 1, 0, 0.625313,-0.00661627) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.46273,-0.00283869) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.537966,0.0145693) , 
7, 0.117389, 1, 0, 0.484346,0.000859503) , 
1, 0.272278, 1, 0, 0.5,2.93325e-05)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.639515,0.0320673) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.490908,-0.0002263) , 
1, 0.0990287, 1, 0, 0.496708,0.000328259) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.593907,-0.0248008) , 
7, 0.18459, 1, 0, 0.5,4.94063e-06)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475536,0.000336115) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.579524,-0.0427417) , 
3, 0.0592825, 1, 0, 0.481319,-0.000726381) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.608644,-0.00649887) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.601536,0.0528406) , 
3, 0.0475222, 1, 0, 0.606451,0.00416009) , 
2, 0.0227702, 1, 0, 0.5,3.13632e-06)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531159,-0.00187462) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344433,0.0145339) , 
1, 1.95527, 1, 0, 0.500657,0.000345543) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.478588,-0.0301756) , 
2, 0.0475205, 1, 0, 0.5,6.94872e-06)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520749,0.00352934) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.467993,-0.042879) , 
0, 93.4691, 1, 0, 0.519254,0.000657879) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.298864,0.0405649) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.347678,-0.0321823) , 
13, 0.148441, 1, 0, 0.335443,-0.0056581) , 
1, 2.10377, 1, 0, 0.5,-3.72062e-06)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.494816,-0.003879) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.569909,0.0333687) , 
16, 6.94078, 1, 0, 0.499236,-0.000601393) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.548327,-0.0376632) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.459761,0.0887698) , 
26, 0.0251412, 1, 0, 0.510717,0.00822681) , 
0, 65.646, 1, 0, 0.5,-1.42281e-05)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.358389,0.0225082) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.524484,-0.00234838) , 
6, 0.842103, 1, 0, 0.501465,0.000323027) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457235,-0.0275261) , 
6, 7.45709, 1, 0, 0.5,-1.12922e-05)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.380949,-0.0282403) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487228,0.000148405) , 
7, 0.0524248, 1, 0, 0.47537,-0.000944316) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.654326,0.0498643) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.549746,-0.00687685) , 
23, 0.00704631, 1, 0, 0.579884,0.00303809) , 
6, 3.22854, 1, 0, 0.5,-5.81409e-06)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.304107,-0.000551401) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.835309,0.112476) , 
12, 0.761937, 1, 0, 0.405235,0.0054351) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.279936,0.0309674) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.531112,-0.00475784) , 
12, 0.089106, 1, 0, 0.514782,-0.000840449) , 
7, 0.0544155, 1, 0, 0.5,6.3806e-06)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.326235,0.00398453) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.206737,-0.0558817) , 
26, 0.0245399, 1, 0, 0.265646,-0.00819001) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.516724,3.88259e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436976,0.0320893) , 
19, 0.782178, 1, 0, 0.513265,0.000499186) , 
12, 0.059404, 1, 0, 0.5,3.37082e-05)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48718,-0.0224512) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.549908,0.00576877) , 
19, 0.485149, 1, 0, 0.525589,-0.00173153) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507991,-0.00533025) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.353978,0.0361276) , 
1, 1.88104, 1, 0, 0.466868,0.00220927) , 
23, 0.0528652, 1, 0, 0.5,-1.42376e-05)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.314726,0.0161146) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.474238,-0.0190826) , 
19, 0.465347, 1, 0, 0.431194,-0.00361356) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507146,-0.0115) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.56639,0.0179641) , 
7, 0.0912086, 1, 0, 0.542027,0.00218295) , 
13, 0.33663, 1, 0, 0.5,-1.50384e-05)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.381165,-0.0142948) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.820327,0.0398703) , 
12, 0.940564, 1, 0, 0.446705,-0.00253983) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435493,-0.0325568) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.55621,0.0107078) , 
7, 0.0477819, 1, 0, 0.542642,0.00202791) , 
19, 0.475248, 1, 0, 0.5,-2.35999e-06)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.44175,0.0098988) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.280895,-0.00546471) , 
26, 0.0263761, 1, 0, 0.384474,0.00165062) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.758892,0.0575921) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.814316,-0.0276879) , 
25, -0.00257466, 1, 0, 0.808324,-0.00437681) , 
12, 0.841557, 1, 0, 0.5,7.76616e-06)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.268194,0.0205051) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.550527,-0.0143662) , 
19, 0.019802, 1, 0, 0.484686,-0.00224972) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.651471,0.0351831) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.484427,2.16375e-05) , 
25, 0.000281707, 1, 0, 0.512927,0.00196314) , 
25, -0.00026588, 1, 0, 0.5,3.47793e-05)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471047,-0.00799519) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.614651,0.0115954) , 
3, 0.0237547, 1, 0, 0.506768,-0.00103595) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435857,0.00122196) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.642573,0.0905405) , 
14, 0.291095, 1, 0, 0.46838,0.00485229) , 
19, 0.663366, 1, 0, 0.5,2.1466e-06)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.377683,0.0299995) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473036,0.000814433) , 
7, 0.0524248, 1, 0, 0.460837,0.00142776) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.757183,-0.0648199) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.567894,-0.00214798) , 
26, 0.00879264, 1, 0, 0.597376,-0.00351797) , 
3, 0.0198009, 1, 0, 0.5,9.19351e-06)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.698051,-0.0271567) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.676925,0.0209573) , 
1, 0.301132, 1, 0, 0.680857,0.00393468) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430969,0.00165946) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444911,-0.0174137) , 
19, 0.584158, 1, 0, 0.435081,-0.00139006) , 
26, 0.00915837, 1, 0, 0.5,1.64173e-05)    );
  // itree = 125
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596751,-0.00278607) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.374735,0.0116158) , 
26, 0.0208811, 1, 0, 0.525037,0.000667448) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.310414,0.0305504) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358181,-0.0346089) , 
2, 0.00495209, 1, 0, 0.340422,-0.00419655) , 
1, 2.02952, 1, 0, 0.5,7.7958e-06)    );
  // itree = 126
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.653823,0.0265217) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.53406,-0.0247053) , 
24, 0.00778249, 1, 0, 0.628875,0.00503048) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499603,-0.00513997) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.334795,0.0197248) , 
22, 0.0354049, 1, 0, 0.480406,-0.000783961) , 
1, 0.321778, 1, 0, 0.5,-1.66216e-05)    );
  // itree = 127
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.31159,-0.0404379) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.413932,-0.00686229) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.548254,0.00501742) , 
2, 0.00297005, 1, 0, 0.505689,0.000413024) , 
24, -0.0882953, 1, 0, 0.5,1.0807e-06)    );
  // itree = 128
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.281681,-0.026324) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.521591,0.00233204) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.325678,-0.018501) , 
22, 0.050157, 1, 0, 0.507662,0.000298248) , 
25, -0.0070005, 1, 0, 0.5,-5.20216e-06)    );
  // itree = 129
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.32254,0.0280674) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.278772,-0.0110453) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.571068,0.00164221) , 
19, 0.168317, 1, 0, 0.506669,-0.000353669) , 
24, -0.0792835, 1, 0, 0.5,-4.70089e-06)    );
  // itree = 130
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.730932,0.0444134) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.585298,-0.00807373) , 
5, 0.366597, 1, 0, 0.595713,-0.00146184) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.219549,0.0506741) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.399315,-0.00339655) , 
12, 0.138609, 1, 0, 0.362763,0.00208214) , 
26, 0.0212474, 1, 0, 0.5,-5.72045e-06)    );
  // itree = 131
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266334,-0.0144633) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.39906,0.0401953) , 
17, 7.98446, 1, 0, 0.283767,-0.00221324) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.401443,0.0404426) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.688498,-0.00021604) , 
12, 0.402992, 1, 0, 0.658279,0.00157867) , 
12, 0.306921, 1, 0, 0.5,-2.38998e-05)    );
  // itree = 132
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.481056,-0.00748503) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.597604,0.0298222) , 
2, 0.0326609, 1, 0, 0.490738,-0.00144222) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.513365,0.0117868) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.537777,-0.047394) , 
2, 0.0326703, 1, 0, 0.515348,0.00233058) , 
19, 0.554456, 1, 0, 0.5,-2.23005e-05)    );
  // itree = 133
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490858,0.0223859) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.324536,-0.00873303) , 
22, 0.00583189, 1, 0, 0.397561,0.00213174) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.625068,0.0135388) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.523254,-0.0122759) , 
23, 0.0211461, 1, 0, 0.557497,-0.00119438) , 
0, 16.9558, 1, 0, 0.5,1.36758e-06)    );
  // itree = 134
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541474,0.0105778) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.68737,-0.0276111) , 
2, 0.00493477, 1, 0, 0.618404,-0.00278403) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.402292,0.0023356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305757,0.0531458) , 
1, 2.15328, 1, 0, 0.39297,0.00251672) , 
22, 0.00590083, 1, 0, 0.5,5.9501e-08)    );
  // itree = 135
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.414939,-0.00799086) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.482236,0.00910616) , 
13, 0.673259, 1, 0, 0.43154,-0.00132369) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.779624,-0.027516) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.74494,0.0278487) , 
5, 0.421708, 1, 0, 0.752883,0.00487708) , 
4, 5.96633, 1, 0, 0.5,-2.65848e-06)    );
  // itree = 136
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496886,-0.0154518) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.472266,0.00910305) , 
24, 0.00238349, 1, 0, 0.48685,-0.00182505) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509169,0.00334574) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60526,0.0483781) , 
7, 0.158555, 1, 0, 0.516728,0.00235606) , 
16, 0.840917, 1, 0, 0.5,1.51315e-05)    );
  // itree = 137
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.374942,0.000659819) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.818207,0.0459765) , 
12, 0.851104, 1, 0, 0.481958,0.00324119) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.25918,-0.0511187) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.525835,-0.00390684) , 
12, 0.059404, 1, 0, 0.511732,-0.00210373) , 
24, -0.0026825, 1, 0, 0.5,2.37853e-06)    );
  // itree = 138
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.194169,-0.0179526) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.3088,0.0173253) , 
19, 0.316832, 1, 0, 0.273104,0.00260959) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.356049,0.0216196) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.686269,-0.0104361) , 
19, 0.00990099, 1, 0, 0.626568,-0.00142797) , 
12, 0.237616, 1, 0, 0.5,1.77867e-05)    );
  // itree = 139
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.443457,0.00642495) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.725783,-0.0763235) , 
18, 0.0717004, 1, 0, 0.455167,0.00121019) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636048,-0.0015042) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420158,-0.038076) , 
25, 0.00274956, 1, 0, 0.599313,-0.00272368) , 
17, 5.03989, 1, 0, 0.5,-1.33399e-05)    );
  // itree = 140
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.403096,-0.00928952) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.532797,0.00221313) , 
2, 0.00297005, 1, 0, 0.491693,-0.000477765) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.77343,0.0562312) , 
18, 0.098588, 1, 0, 0.5,1.06653e-05)    );
  // itree = 141
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58643,0.00288852) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.364227,-0.021575) , 
22, 0.0174957, 1, 0, 0.535176,-0.000962319) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448232,-0.0464368) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34354,0.0264876) , 
22, 0.00295117, 1, 0, 0.36359,0.00377197) , 
25, 0.00239252, 1, 0, 0.5,8.22574e-06)    );
  // itree = 142
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.517002,0.00256496) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.32267,-0.0151861) , 
1, 2.12852, 1, 0, 0.499565,0.000262112) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.51693,-0.0292233) , 
3, 0.106925, 1, 0, 0.5,-1.88077e-05)    );
  // itree = 143
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480107,0.0128609) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.604349,-0.0271189) , 
3, 0.00792038, 1, 0, 0.543881,-0.00261014) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.489809,0.000796491) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.345597,0.0404904) , 
22, 0.0437392, 1, 0, 0.478056,0.0013021) , 
23, 0.0070487, 1, 0, 0.5,-2.11547e-06)    );
  // itree = 144
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.675156,0.0183225) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.46226,-0.00325244) , 
22, 0.00186953, 1, 0, 0.514872,0.000614275) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.277203,-0.0433377) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421107,0.0148638) , 
2, 0.0168271, 1, 0, 0.325261,-0.00723789) , 
22, 0.0472066, 1, 0, 0.5,-1.59923e-06)    );
  // itree = 145
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.40947,0.00340292) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475695,0.0520706) , 
0, 63.4205, 1, 0, 0.415088,0.00269019) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.538893,-0.000818515) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.4861,-0.0612422) , 
0, 79.5577, 1, 0, 0.536827,-0.00117445) , 
25, -0.00132924, 1, 0, 0.5,-5.35651e-06)    );
  // itree = 146
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456486,-0.0412471) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.584632,0.00016522) , 
24, -0.0207955, 1, 0, 0.573572,-0.00122461) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.356595,0.000421003) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439777,0.077668) , 
23, 0.155071, 1, 0, 0.363561,0.00225721) , 
22, 0.0118016, 1, 0, 0.5,-4.84143e-06)    );
  // itree = 147
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.486115,0.00501111) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.548209,-0.0167245) , 
13, 0.772268, 1, 0, 0.495837,0.000599524) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.641814,0.0123961) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.495177,-0.0707051) , 
8, 0.528459, 1, 0, 0.565936,-0.00968692) , 
23, 0.179742, 1, 0, 0.5,-1.13448e-05)    );
  // itree = 148
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.33461,-0.0205869) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.74087,0.00618175) , 
12, 0.316711, 1, 0, 0.595713,-0.00143698) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.386977,0.0151287) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.306953,-0.0161715) , 
22, 0.0161544, 1, 0, 0.362763,0.0020567) , 
26, 0.0212474, 1, 0, 0.5,-1.52352e-06)    );
  // itree = 149
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.320143,0.00160175) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404787,0.0595208) , 
0, 86.5133, 1, 0, 0.323861,0.0016143) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.689609,0.00482275) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.836713,-0.0368869) , 
0, 26.1643, 1, 0, 0.749326,-0.0023187) , 
12, 0.603941, 1, 0, 0.5,-1.39282e-05)    );
   return;
};
 
// Clean up
inline void ReadNCuts 100::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadNCuts 100::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
